### ISSUE TITLE
GUI just loadin forever

### ISSUE THREAD

**Issue by nick2be** [keybase/client#10053]
Keybase GUI Version: 1.0.38-20171221170044+4c1f9803e

Tried : $HOME/.config/Keybase/SingletonLock. Tried removing that file

Ran keybase status  : error: Got reply 500

Ran /opt/keybase/Keybase

/opt/keybase/Keybase
Error loading state: { Error: /home/USER/.config/Keybase/installer.json: ENOENT: no such file or directory, open '/home/USER/.config/Keybase/installer.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Object.readFileSync (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:525073)
    at p.default.promptedForCLI.t.default (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:524224)
    at p.default.promptedForCLI (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:412360)
    at Object.defineProperty.value (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:412356)
    at t (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:256)
    at Object.defineProperty.value (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:314362)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/USER/.config/Keybase/installer.json' }
Version: 1.0.38-20171221170044+4c1f9803e
Check bounds: { x: 2105, y: 447, width: 800, height: 600 } { x: 1920, y: 0, width: 1920, height: 1080 } { x: 1920, y: 0, width: 1920, height: 1080 }
Opened at login: false
Is restore: false
Open hidden: false
Hide main window: false
Hide dock icon: false
Error:  Error: No keybase bin path
    at t.default.e (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:412568)
    at EventEmitter.p.ipcMain.on (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:315757)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/opt/keybase/resources/electron.asar/browser/api/web-contents.js:247:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)
#Does not finish loading!

Seem like I 2 errors - running on Ubuntu 14.04 LTS
![selection_497](https://user-images.githubusercontent.com/6353731/34433165-a93c8e24-ec7d-11e7-83a4-c2ae752fcf3b.png)

**Comment by maxtaco** [comment]
Cc: @oconnor663
