### ISSUE TITLE
Reset keys, can't access teams

### ISSUE THREAD

**Issue by pengi** [keybase/client#10098]
I just tested out keybase, and messed around a bit with keys while learning. I've created some teams during that time too.

Then I gave ownership of those teams to a friend, so I could clean up my account with "Reset your keys & start from scratch"

I then got the ownership transferred back, but I'm not able to list the teams anymore.

In the terminal, I get:
```
$ keybase team list-memberships 
▶ ERROR multiple errors while loading team list
```

I guessed that the option -debug would add some debug output, and it seems to be stuck in a loop and gives up. I don't want to post the debug log, since I don't know if the device secret is there. But it seems like I get some
`- TeamLoader#loadUserForSigVerification(1) -> ERROR: Not found: User`
`- TeamLoader#load2(....., public:false) -> Not found: User`

My username is "pengi", and one of the teams I should be a member of is called "313"

**Comment by pengi** [comment]
The error also is visble from the GUI in the app, as:
```
GENERIC: ERROR CODE 218 - multiple errors while loading team list in method keybase.1.teams.teamList
at o.t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:384862)
at o (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:385168)
at a (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:384530)
at t.convertToError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:384728)
at _rpcClient.invoke.t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:354928)
at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:777671
at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:610643)
at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:610794
at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:610423)
at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:610753)
```

In version: Version 1.0.38-20171220205307+f5d54bc77 for mac

**Comment by pengi** [comment]
my log id: 6164c9e07a601c1003a0191c

**Comment by maxtaco** [comment]
there is no device secret in the debug logs

**Comment by pengi** [comment]
Hum... This makes it quite unstable for me. But it did help a bit to revoke my phone, uninstall and reinstall keybase app, and then link it back together. I don't get the error when listing teams, even though I lost membership of some teams afterwards. And I still have some broken team chats:

```
$ keybase chat ls
[1]  XXuserXX                [pengi 56m] X                                                                                                                                                                                                                        
[2]  a_small_team [#general]  [pengi 2h] .                                                                                                                                                                                                                                      
[3]  (unverified) 313              [???] error unboxing chat message: Not found: User                                                                                                                                                                                           
[4]  (unverified) XXteamXX         [???] error unboxing chat message: Not found: User                                                                                                                                                                                           
[5]  (unverified) op6              [???] error unboxing chat message: Not found: User                                                                                                                                                                                           
$ keybase team list-memberships       
Team            Role     Members
a_small_team    owner    1
$ keybase chat read            
There are 4 conversations. Please choose one:
[1] private XXuserXX,pengi                                                                                                                                                                                                                                                      
Please enter a number [1-4]: 3
▶ ERROR GetConversationForCLILocal error: error unboxing chat message: Not found: User
```
(where `XXuserXX` and `XXteamXX` is two team names censored)

log ID 1d05d114b0b49d1cebc3c81c

**Comment by maxtaco** [comment]
We'll look into it this sprint

**Comment by pengi** [comment]
Great!

Just contact me if you have any questions.

**Comment by maxtaco** [comment]
@pengi can you try `keybase db nuke` and then try again?

**Comment by pengi** [comment]
Seems to work much better now.

There are two things still (except some messages in the log history for some teams) that I notice:
- I have one team chat without name. I think it's from a team "note_to_self", which I removed. So it might be correct.
- I get errors when I look at the git page

I can't remember if I removed the team repositories I tested with, but I don't think so. So there should possibly be two repositories available under team 313

```
$ keybase git list
Error in repo: can't find device name for pengi's device ID 2f01dbe5a0593bfb55583925a65db518
Error in repo: can't find device name for pengi's device ID 2f01dbe5a0593bfb55583925a65db518
personal repos:
  upgp  keybase://private/pengi/upgp
team repos:
```
Log ID: f0e234e6e013f18c4691e81c

**Comment by maxtaco** [comment]
Cool, great, glad it works better.

That device `2f01dbe5a0593bfb55583925a65db518` is a pre-reset device, so it's likely an error we can tune down or ignore.

**Comment by pengi** [comment]
That was what I guessed. Since it appeared twice, I also thought it might be related to the two repositories I thought I had in a team previously.

Since I have no means (at least for what I know) to take any action on those error messages, tune it down would probably be nice :)

Thanks, and great work!
