### ISSUE TITLE
Attempt to paste file into chat results in ERROR CODE 1504

### ISSUE THREAD

**Issue by fleish** [keybase/client#10253]
I tried to paste a file (happened to be a shell script if that matters) into a several keybase chats (at different times) and an error popup that said "ERROR CDOE 1504 - RPC Error: STREAM_EOF in method chat.1.local.makePreview at o.t"

Full error message attached

<img width="794" alt="screen shot 2018-01-18 at 11 33 31 am" src="https://user-images.githubusercontent.com/2106430/35129518-d5f1ff50-fc70-11e7-8c0f-eab994df12d2.png">

**Comment by jagottf** [comment]
I encountered exactly the same error as mentioned above whenever I tried to add an _empty_ file. Adding any non empty file (text and binary, various formats) worked.

(Actually, another error (ERROR CODE 218) occurred when tried to add a file for which I had no permissions. This obviously can't work, but I expected a nicer error message. But I assume this is not directly related anyway, except if there is a bug in the general way such errors are handled.)

Version:
Client:  1.0.47-20180330162235+ea57e4c687
Service: 1.0.47-20180330162235+ea57e4c687

Environment:
4.4.0-116-generic x86_64 GNU/Linux

Error:
`ERROR CODE 1504 - RPC Error: STREAM_EOF in method chat.1.local.makePreview
STREAM_EOF: ERROR CODE 1504 - RPC Error: STREAM_EOF in method chat.1.local.makePreview at o.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:392692) at o (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:392998) at a (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:392360) at t.convertToError (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:392558) at _rpcClient.invoke.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:349717) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1012976 at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:663738) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:663889 at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:663518) at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:663848)`
