### ISSUE TITLE
Error code 218: GENERIC in method keybase.1.login.login

### ISSUE THREAD

**Issue by MichalGrabeQ** [keybase/client#10657]
![image](https://user-images.githubusercontent.com/36743168/36557910-d32b9664-1809-11e8-95df-3a35a5270709.png)
![image](https://user-images.githubusercontent.com/36743168/36558014-10c53624-180a-11e8-9ee8-4ac28af3c8f4.png)
![image](https://user-images.githubusercontent.com/36743168/36558046-245e91e4-180a-11e8-8749-89c7c673deb1.png)

**Comment by maxtaco** [comment]
Cc @zanderz

**Comment by bs1978ta** [comment]
Same problem here on windows 7. Buggy

**Comment by Extremeswank** [comment]
Not specific to Windows.  Getting same error on iOS.

**Comment by maxtaco** [comment]
Likely it is  different bug. Send feedback through the app on iOS.

**Comment by mmaxim** [comment]
We just launched a fix for this on all platforms, hopefully this will fix it for you after updating. Sorry for the trouble.

**Comment by NobbZ** [comment]
I do get that errorcode but with a different stack trace when I try to enter keybasefriends#general.

```
GENERIC: ERROR CODE 218 - Key path not found in method chat.1.local.getTLFConversationsLocal at o.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:394918) at o (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:395224) at a (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:394586) at t.convertToError (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:394784) at _rpcClient.invoke.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:367716) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:800721 at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:633846) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:633997 at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:633626) at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:633956)
```

Shall I open another bug for this one or can I track this one?

**Comment by maxtaco** [comment]
Which app version?

**Comment by NobbZ** [comment]
Both have been on 1.0.41.somerandomedatestringwithcommitid. After an update to 44, at least mobile is working again, laptop is currently out of physical reach.

**Comment by maxtaco** [comment]
@rorymbyrne send a screen shot and do a `keybase log send`

**Comment by puppycodes** [comment]
same:
<img width="787" alt="screen shot 2018-07-25 at 5 16 09 pm" src="https://user-images.githubusercontent.com/5248271/43234033-7c598204-902e-11e8-9a0d-c57dba6ff7d1.png">

my log id: 0d57ffdf3534aad2a1ac361c
