### ISSUE TITLE
ERROR CODE 2623: You are not a member of this team in method 

### ISSUE THREAD

**Issue by MLWALK3R** [keybase/client#11057]
Trying to message a friend on the client I get this error. reset my account the other day.

TEAM_READ_ERROR: ERROR CODE 2623 - You are not a member of this team in method chat.1.local.newConversationLocal at o.t (file:///C:/Users/Michael/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:394330) at o (file:///C:/Users/Michael/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:394636) at a (file:///C:/Users/Michael/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:393998) at t.convertToError (file:///C:/Users/Michael/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:394196) at _rpcClient.invoke.t (file:///C:/Users/Michael/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:367046) at file:///C:/Users/Michael/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:814464 at e.t.Deferrals.e._call (file:///C:/Users/Michael/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:638615) at file:///C:/Users/Michael/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:638766 at s (file:///C:/Users/Michael/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:638395) at e.t.Deferrals.e._fulfill (file:///C:/Users/Michael/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:638725)

**Comment by maxtaco** [comment]
cc @mmaxim

**Comment by nordi700** [comment]
Have same problem, can you help me too?

**Comment by notjrbauer** [comment]
same problem

**Comment by maxtaco** [comment]
Send a log via feedback and we can look
