### ISSUE TITLE
Cannot uninstall Keybase

### ISSUE THREAD

**Issue by zakiaziz** [keybase/client#11100]
After looking at issue #4226 I tried to run `keybase uninstall` but getting an error:
```
$ keybase uninstall
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4d9503b]

goroutine 1 [running]:
github.com/keybase/client/go/install.fallbackKillProcess(0x5d88ea0, 0xc420322380, 0x6b72070, 0xc420151540, 0x5328f93, 0xc, 0xc42001a240, 0x30, 0x0, 0x0, ...)
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:1219 +0x127b
github.com/keybase/client/go/install.UninstallKBFSServices(0x5d88ea0, 0xc420322380, 0x6b72070, 0xc420151540, 0xc420041a70, 0xc420041a60)
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:344 +0x151
github.com/keybase/client/go/install.UninstallKBFS(0x5d88ea0, 0xc420322380, 0xc420014660, 0x8, 0x1, 0x6b72070, 0xc420151540, 0x40358b4, 0xc420000180)
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:794 +0x67
github.com/keybase/client/go/install.Uninstall(0x5d88ea0, 0xc420322380, 0x5ea6de0, 0x8, 0x8, 0x6b72070, 0xc420151540, 0x0, 0x0, 0x0, ...)
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:689 +0x216e
github.com/keybase/client/go/client.(*CmdUninstall).Run(0xc42038be00, 0xc420332070, 0x5ea5360)
	/Users/build/go/src/github.com/keybase/client/go/client/cmd_install_osx.go:232 +0x113
main.mainInner(0xc420322380, 0x0, 0x0)
	/Users/build/go/src/github.com/keybase/client/go/keybase/main.go:165 +0x71b
main.main()
	/Users/build/go/src/github.com/keybase/client/go/keybase/main.go:70 +0xa6
```

**Comment by maxtaco** [comment]
@zakiaziz what version of the software is this?

**Comment by zakiaziz** [comment]
```
$ keybase --v
keybase version 1.0.45-20180305194145+3a1c65a05
```
