### ISSUE TITLE
The app crashes and exits by itself when using the Revoke Devices feature #bug

### ISSUE THREAD

**Issue by ahyar92** [keybase/client#11810]
#### Expected behavior
Supposedly, I can revoked the device

#### Actual behavior
When I enter the device menu, because I want to revoked device, and I clicked "Mobile Device", the application suddenly came out by itself.

#### How to reproduce
1. Install and register the account
2. Next do login
3. Then, go to **Settings> Devices**, and click on "Mobile Device", then you will find the error as I experienced.

----
- Device: Xiaomi Redmi 4X
- Operating system: Marshmallow, 6.0.1 mmb29m (CPU: Octa-core Max 1.9 GHz, RAM: 2 GB)
- Application Version: 1.0.19

#### Recording Of The Bug
https://www.youtube.com/watch?v=RdowmbKFIo4&feature=youtu.be

#### Logcat
<code>--------- beginning of crash
05-11 17:36:45.285  6926  7068 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
05-11 17:36:45.285  6926  7068 E AndroidRuntime: Process: io.keybase.ossifrage, PID: 6926
05-11 17:36:45.285  6926  7068 E AndroidRuntime: java.lang.RuntimeException: Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'ReactRawTextShadowNode' to a 'LayoutShadowNode')
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.addChildAt(ReactShadowNodeImpl.java:199)
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.addChildAt(ReactShadowNodeImpl.java:54)
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at com.facebook.react.uimanager.UIImplementation.setChildren(UIImplementation.java:482)
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerModule.setChildren(UIManagerModule.java:439)
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:742)
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
05-11 17:36:45.285  6926  7068 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818) 
</code>

**Comment by maxtaco** [comment]
Can you send feedback from the app? Seems like a new bug, we’ll fix it.
Thanks.
