### ISSUE TITLE
Can't chat with a user who reset their account

### ISSUE THREAD

**Issue by jiaaro** [keybase/client#11827]
A friend signed up for keybase long ago and had to reset their account to start using it again. I am not able to chat with them because a dialog is instructing me to check their proofs to speak with them in person (I've done both). When I click the "Let them in" button I see an error with the following content:
```
Error: ERROR CODE 218 - team load arg has invalid ID: 643c37dabc81ad1423152b20073c9616 in method chat.1.local.addTeamMemberAfterReset at new a (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:441743) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:442272 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:442311) at _rpcClient.invoke.t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:12053) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:1475433 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:671644) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:671795 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:671424) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:671754) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:670958)
```

See Log id: 99ae0160db9a6396cf6be71c

**Comment by maxtaco** [comment]
cc @mmaxim

**Comment by mmaxim** [comment]
Ugh, I don't think this works for upgraded KBFS convs...

**Comment by mattselph** [comment]
Experiencing same issue, what version is the fix in?

**Comment by mmaxim** [comment]
1.0.48, right now only available on desktop, mobile release coming soon

**Comment by thadeej** [comment]
I'm experiencing this issue as well. Both on Mac OS X 10.14 with client version 4.3.2, and iOS 12.4 with app version 4.3.0.

I had to reset my account because my old phone is no longer around to verify with.

Now I cannot chat: ERROR CODE 218 - newly created conversation fetch error: found 0 conversations in method chat.1.local.newConversationLocal (on Mac...and same code on iOS)

Sent log `Success! Your log ID is:

  1d7e70e16e7ec414aff8b51c`
