### ISSUE TITLE
Constantly getting rekey notifications and ERROR 218 after revoking a phone device and adding a new one

### ISSUE THREAD

**Issue by iamstev** [keybase/client#11937]
Constantly getting rekey notifications and ERROR 218 after revoking a phone device and adding a new one

my log id: c0535815aac2f1965f3cd11c

http://stev.link/1a3M3U452H2Q

http://stev.link/2J1o070V0K3G

**Comment by maxtaco** [comment]
thanks, it's likely a broken TLF that can't be rekeyed.

**Comment by strib** [comment]
That folder had some device-specific state that seems like it was the result of an old bug.  Specifically, this in the logs:

```
2018-05-18T20:57:56.288779-04:00 ▶ [DEBU kbfs(CR fb0dd4f7) conflict_resolver.go:3253] 0cb Finished conflict resolution: ran out of MD updates to unstage
github.com/keybase/kbfs/libkbfs.getUnmergedMDUpdates
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/md_util.go:338
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).getUnmergedMDUpdates
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:5145
github.com/keybase/kbfs/libkbfs.(*ConflictResolver).getMDs
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/conflict_resolver.go:309
github.com/keybase/kbfs/libkbfs.(*ConflictResolver).buildChainsAndPaths
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/conflict_resolver.go:1188
github.com/keybase/kbfs/libkbfs.(*ConflictResolver).doResolve
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/conflict_resolver.go:3251
github.com/keybase/kbfs/libkbfs.(*ConflictResolver).processInput.func3
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/conflict_resolver.go:213
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:2361 [tags:CRID=qJ_pZVec5J7wlEYmwS0xYA]
panic: doResolve: head is nil (should be impossible)

goroutine 289 [running]:
github.com/keybase/kbfs/libkbfs.(*ConflictResolver).doResolve.func2(0xc420bd05a0, 0xc422749ee0, 0xc422748fc8, 0xc4228e4360)
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/conflict_resolver.go:3166 +0x518
github.com/keybase/kbfs/libkbfs.(*ConflictResolver).doResolve(0xc420bd05a0, 0x52cc700, 0xc42286ecc0, 0x3, 0x0)
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/conflict_resolver.go:3253 +0x1bb3
github.com/keybase/kbfs/libkbfs.(*ConflictResolver).processInput.func3(0xc420bd05a0, 0xc420dc0c60, 0xc4228dc030, 0x3, 0x0, 0xc420dc1aa0)
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/conflict_resolver.go:213 +0x207
created by github.com/keybase/kbfs/libkbfs.(*ConflictResolver).processInput
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/conflict_resolver.go:201 +0x26e
```

This caused a panic, leading to an endless restart for the kbfsfuse process.  The device in question was provisioned over a year ago, and I wonder if it's been having this problem since then (the logs don't go back that far).  I have vague memories of similar bugs, relating to conflicts happening on the first revision of a folder, that have long since been fixed.  But in any case, uninstallation would have fixed it and it shouldn't happen again, so all is good.  Thanks for the report and the followup.
