### ISSUE TITLE
Go in "Device Menu" and do click on my device, then the application Crash.

### ISSUE THREAD

**Issue by rezamusic881** [keybase/client#11944]
#### Project Information
* ###### Repository : https://github.com/keybase/client
* ###### Title App : Keybase
* ###### Publisher App : Keybase, Inc

***

#### Expected behavior
Supposedly, The app does not stop when the user clicks on "Devices connected in the app".

#### Actual behavior
When I go in "Device Menu" and do click on my device, then the application Crash.

#### How to reproduce
1. Instal App [here]( https://play.google.com/store/apps/details?id=io.keybase.ossifrage)
2. Run the Application
3. Go to "Device Menu"
4. Click on your device connected to the app, Then the application will Crash.

#### Environment
* ###### Device : Redmi Note 5A
* ###### System Operating : 7.1.0 Nougat
* ###### App Version : 1.0.19

***
***

#### <center>Recording Of The Issues</center>

https://youtu.be/Rt0je9Hy7XU

***

#### Logcat
```
05-21 22:57:20.272 12448 12494 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
05-21 22:57:20.272 12448 12494 E AndroidRuntime: Process: io.keybase.ossifrage, PID: 12448
05-21 22:57:20.272 12448 12494 E AndroidRuntime: java.lang.RuntimeException: Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'ReactRawTextShadowNode' to a 'LayoutShadowNode')
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.addChildAt(ReactShadowNodeImpl.java:199)
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.addChildAt(ReactShadowNodeImpl.java:54)
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at com.facebook.react.uimanager.UIImplementation.setChildren(UIImplementation.java:482)
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerModule.setChildren(UIManagerModule.java:439)
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:754)
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:163)
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
05-21 22:57:20.272 12448 12494 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:760)
```

###### [Submit in github](http://www.github.com/rezamusic881)

**Comment by maxtaco** [comment]
Please "send feedback" from the app so we can see the logs.

thanks!

cc: @keybase/react-hackers
