### ISSUE TITLE
The application crashes when clicking the image being Encrypting

### ISSUE THREAD

**Issue by ahyar92** [keybase/client#11979]
#### Expected behavior
Supposedly, when I click on the image being encrypted the application will not crash.

#### Actual behavior
Initially, when I send a picture via "Choose from Library" and still in Encrypting process, I click on the image to ensure it, the application suddenly crashes and exits by itself.

#### How to reproduce
1. Install apps and lists
2. Next go to the team menu, and do "Create team" or "Join the team". 
3. Next go to the chat page
4. Next do image sending via "Choose from Library"
5. While the image is in the process of Encrypting, click on the image, then the application will crash.

----
- Device: Xiaomi Redmi 4X
- Operating system: Marshmallow, 6.0.1 mmb29m (CPU: Octa-core Max 1.9 GHz, RAM: 2 GB)
- Application Version: 

#### Recording Of The Bug
https://www.youtube.com/watch?v=0Pf_zIqPdbk

#### Logcat
```
05-23 01:31:43.529 32016 32072 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
05-23 01:31:43.529 32016 32072 E AndroidRuntime: Process: io.keybase.ossifrage, PID: 32016
05-23 01:31:43.529 32016 32072 E AndroidRuntime: java.lang.RuntimeException: Cannot add a child that doesn't have a YogaNode to a parent without a measure function! (Trying to add a 'ReactRawTextShadowNode' to a 'LayoutShadowNode')
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.addChildAt(ReactShadowNodeImpl.java:199)
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at com.facebook.react.uimanager.ReactShadowNodeImpl.addChildAt(ReactShadowNodeImpl.java:54)
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at com.facebook.react.uimanager.UIImplementation.setChildren(UIImplementation.java:482)
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at com.facebook.react.uimanager.UIManagerModule.setChildren(UIManagerModule.java:439)
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:742)
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
05-23 01:31:43.529 32016 32072 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
05-23 01:31:43.576 32016 32072 E MQSEventManagerDelegate: failed to get MQSService.
```

**Comment by BlueHatbRit** [comment]
I'm just going to hop on the back of this, I'm not sure if my issue is related or not but I often have trouble uploading a photo in a similar scenario. Either taking a photo or upload from library, during the encryption phase it'll do one of the following. Fall over, fail to encrypt and send the image and the recipient will either see a blank square where the image should be, or never receive the message at all.

I've noticed on Android this happens more frequently when I sleep the device by tapping the power button. This suggests to me that the encryption / sending process is being run in the foreground and so any interaction with the message, or tombstoning of the application, seems to break the entire process.

If this seems unrelated then I'll happily open a new ticket, but I have a feeling it may be related.
