### ISSUE TITLE
missing installer.json causes empty window

### ISSUE THREAD

**Issue by prmam** [keybase/client#12124]
I just upgraded to F28. When I launch the desktop app in Fedora, I get only a frame and the white background. I think that I am missing the installer.json file

[sbb@dingo ~]$ /opt/keybase/Keybase 
Error loading state: { Error: /home/sbb/.config/Keybase/installer.json: ENOENT: no such file or directory, open '/home/sbb/.config/Keybase/installer.json'
    at Object.fs.openSync (fs.js:652:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:508:29)
    at Object.readFileSync (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:17468)
    at Xf.promptedForCLI.Xf (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:243518)
    at Xf.promptedForCLI (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:243669)
    at Object.e.version (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:243665)
    at r (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:265)
    at /opt/keybase/resources/app/desktop/dist/main.bundle.js:1:680
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/sbb/.config/Keybase/installer.json' }
Only one instance of keybase GUI allowed, bailing!
[sbb@dingo ~]$ ls ~/.config/Keybase/
app-state.json   Cookies-journal  SingletonCookie  
Cache/           GPUCache/        SingletonLock    
Cookies          Preferences      SS

**Comment by maxtaco** [comment]
cc: @keybase/react-hackers

**Comment by chrisnojima** [comment]
that error message is benign. The real issue is likely this
`Only one instance of keybase GUI allowed, bailing!`. it thinks you have another instance running

**Comment by prmam** [comment]
If I do have another instance of keybase running it is not visible on any workspace. How do I force keybase to believe that it is the only instance running? I have rebooted. And the error persists. See log id 027ec5d885597b8f98ca3e1c.

**Comment by prmam** [comment]
Well, two updates later, the same problem still persists. The logs are different. It is no longer complaining about only one instance of keybase. I still get the white screen. On occasion, it does launch correctly. I haven't been able to find a pattern.

Another log:
Quit through before-quit
Quit the app
Exec (null) not available for platform: darwin != linux
Done with ctlstop
Browser window crashed:  { preventDefault: [Function: preventDefault],
  sender: 
   WebContents {
     webContents: [Circular],
     history: [ 'file:///opt/keybase/resources/app/desktop/renderer/renderer.html?menubar' ],
     currentIndex: 0,
     pendingIndex: -1,
     inPageIndex: -1,
     _events: 
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'pepper-context-menu': [Function],
        'devtools-reload-page': [Function],
        'will-navigate': [Function],
        'did-navigate': [Function],
        destroyed: [Object],
        'devtools-opened': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        move: [Function],
        activate: [Function],
        'page-title-updated': [Function],
        crashed: [Function],
        'did-finish-load': [Function: callIntoRenderer],
        'render-view-deleted': [Function: listener],
        'context-menu': [Function: callIntoRenderer] },
     _eventsCount: 19,
     _maxListeners: 0,
     browserWindowOptions: 
      { show: false,
        frame: false,
        index: 'file:///opt/keybase/resources/app/desktop/renderer/renderer.html?menubar',
        nodeIntegration: false,
        width: 320,
        height: 350,
        resizable: false,
        hasShadow: true,
        transparent: true,
        preloadWindow: true,
        icon: '/opt/keybase/resources/app/images/menubarIcon/icon-keybase-menubar-regular-white-22@2x.png',
        showDockIcon: true,
        dir: '/opt/keybase/resources/app',
        windowPosition: 'trayCenter',
        tooltip: '' } } }
Browser window crashed:  { preventDefault: [Function: preventDefault],
  sender: 
   WebContents {
     webContents: [Circular],
     history: [ 'file:///opt/keybase/resources/app/desktop/renderer/renderer.html?mainWindow' ],
     currentIndex: 0,
     pendingIndex: -1,
     inPageIndex: -1,
     _events: 
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'pepper-context-menu': [Function],
        'devtools-reload-page': [Function],
        'will-navigate': [Function],
        'did-navigate': [Function],
        destroyed: [Object],
        'devtools-opened': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        move: [Function],
        activate: [Function],
        'page-title-updated': [Function],
        crashed: [Function],
        'did-finish-load': [Function],
        'render-view-deleted': [Function: listener],
        'context-menu': [Function: callIntoRenderer] },
     _eventsCount: 19,
     _maxListeners: 0,
     browserWindowOptions: 
      { show: false,
        backgroundThrottling: false,
        height: 600,
        minHeight: 400,
        minWidth: 600,
        width: 845,
        x: 2974,
        y: 410 } } }
Login item settings changed! now true
Error loading state: { Error: /home/sbb/.config/Keybase/installer.json: ENOENT: no such file or directory, open '/home/sbb/.config/Keybase/installer.json'
    at Object.fs.openSync (fs.js:652:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:172:20)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:508:29)
    at Object.readFileSync (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:17468)
    at Xf.promptedForCLI.Xf (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:243570)
    at Xf.promptedForCLI (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:243721)
    at Object.e.version (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:243717)
    at r (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:265)
    at /opt/keybase/resources/app/desktop/dist/main.bundle.js:1:680
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/sbb/.config/Keybase/installer.json' }
Version: 2.0.0-20180604163022+f899a761a7
Check bounds: { height: 600, width: 845, x: 2974, y: 410 } { x: 1920, y: 0, width: 1920, height: 1080 } { x: 1920, y: 0, width: 1920, height: 1080 }
Setting login item due to user pref
Opened at login: false
Is restore: false
Open hidden: false
Hide main window: false
Login item settings changed! now true
Hide dock icon: false
Error:  Error: No keybase bin path
    at Zf (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:243926)
    at EventEmitter.s.on (/opt/keybase/resources/app/desktop/dist/main.bundle.js:1:249959)
    at emitOne (events.js:115:13)
    at EventEmitter.emit (events.js:210:7)
    at WebContents.<anonymous> (/opt/keybase/resources/electron.asar/browser/api/web-contents.js:266:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
Login item settings changed! now true

**Comment by maxtaco** [comment]
If you `keybase log send` we can take a look

**Comment by prmam** [comment]
Success! Your log ID is: 6ed1c111995ae59f9048661c

**Comment by maxtaco** [comment]
thanks cc @zanderz

**Comment by maxtaco** [comment]
cc @oconnor663  looks like a linux crasher.  or maybe @cjb, it's in electron?

**Comment by oconnor663** [comment]
The easiest way to get rid of the running instance is `killall /opt/keybase/Keybase`. If you try that, and then rerun `/opt/keybase/Keybase` from your terminal, what happens?

**Comment by majorgreys** [comment]
Another log while an empty window was up: 5f3f2eb5f84a93895d921e1c

**Comment by maxtaco** [comment]
cc @keybase/react-hackers with new logs

**Comment by oconnor663** [comment]
I'm playing with a Fedora 28 vm right now. There's at least one major issue there: the latest version of Gnome no longer shows tray icons by default. For me to get my tray icons back, I need to install the "topicons" Gnome plugin and reconfigure my entire session to run under "Gnome on X11". I hate this situation, but it seems like something [Electron and Gnome are going to have to figure out between themselves](https://github.com/electron/electron/issues/10427).

But this doesn't sound quite like the issue people are reporting here. When I run `run_keybase`, I see the full Keybase GUI window appear, whether or not the tray icons are working. Folks in this thread, what happens when you run `run_keybase`? Is there any difference if you try `KEYBASE_SYSTEMD=0 run_keybase`?

**Comment by oconnor663** [comment]
To clarify, there are two apparent errors in the GUI log output that are really just ignored:

- `installer.json: ENOENT: no such file or directory`
- `Error: No keybase bin path`

Those two aren't the problem.

**Comment by oconnor663** [comment]
I'd also love to know more about the machines everyone's running, particularly graphics cards (white screens in Electron could be a graphics issue). If you get a chance, could you write in:

- `cat /etc/os-release`
- `uname -a`
- `lspci | grep -i vga` (or whatever reveals your graphics card)
- `glxinfo | grep -i vendor` (or whatever reveals your driver, something different for Wayland)

**Comment by majorgreys** [comment]
@oconnor663 sure hope this helps:

```
[tbutt@mantis ~]$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
[tbutt@mantis ~]$ uname -a
Linux mantis 4.16.13-2-ARCH #1 SMP PREEMPT Fri Jun 1 18:46:11 UTC 2018 x86_64 GNU/Linux
[tbutt@mantis ~]$ lspci | grep -i vga
00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)
[tbutt@mantis ~]$ glxinfo | grep -i intel
    GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
```

**Comment by prmam** [comment]
```
$ cat /etc/os-release 
NAME=Fedora
VERSION="28 (Workstation Edition)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
$ uname -a
Linux dingo 4.16.13-300.fc28.x86_64 #1 SMP Wed May 30 14:31:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lspci | grep -i vga
01:00.0 VGA compatible controller: NVIDIA Corporation GM204M [GeForce GTX 970M] (rev a1)
$ glxinfo | grep -i vendor
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: VMware, Inc. (0xffffffff)
OpenGL vendor string: VMware, Inc.
```

**Comment by prmam** [comment]
I still have the same problem with build keybase-2.1.0.20180607041058.2c3323537e-1.x86_64
I enabled debug and uploaded the log. Log ID is: 814f1fd75adfe026dd99fb1c
My poor recollection says that it worked fine for the first few updates to F28. Then it started failing. It does work on rare occasions. When it does, I will try to capter a log so that you have it for comparison.
