### ISSUE TITLE
Keybase crashes on GCM message on KK

### ISSUE THREAD

**Issue by Avamander** [keybase/client#12735]
For the last few Keybase updates the Android client crashes on every startup and sometimes even in the background rendering the app unusable. 

Android: Kitkat (LineageOS 11)
Phone: LG D605

```
07-07 14:40:18.323 32438 32438 E AndroidRuntime: FATAL EXCEPTION: main

07-07 14:40:18.323 32438 32438 E AndroidRuntime: Process: io.keybase.ossifrage, PID: 32438

07-07 14:40:18.323 32438 32438 E AndroidRuntime: java.lang.RuntimeException: Unable to create application io.keybase.ossifrage.MainApplication: java.lang.IllegalArgumentException: The GcmTaskService class you provided com.evernote.android.job.gcm.PlatformGcmService does not seem to support receiving com.google.android.gms.gcm.ACTION_TASK_READY

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4476)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:136)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5146)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at java.lang.reflect.Method.invokeNative(Native Method)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:515)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at dalvik.system.NativeStart.main(Native Method)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: The GcmTaskService class you provided com.evernote.android.job.gcm.PlatformGcmService does not seem to support receiving com.google.android.gms.gcm.ACTION_TASK_READY

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at com.google.android.gms.gcm.GcmNetworkManager.zze(Unknown Source)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at com.google.android.gms.gcm.GcmNetworkManager.schedule(Unknown Source)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at com.evernote.android.job.gcm.JobProxyGcm.plantPeriodic(JobProxyGcm.java:86)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at com.evernote.android.job.JobManager.scheduleWithApi(JobManager.java:239)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at com.evernote.android.job.JobManager.schedule(JobManager.java:197)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at com.evernote.android.job.JobRequest.schedule(JobRequest.java:436)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at io.keybase.ossifrage.modules.BackgroundSyncJob.scheduleJob(BackgroundSyncJob.java:30)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at io.keybase.ossifrage.MainApplication.onCreate(MainApplication.java:39)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4473)

07-07 14:40:18.323 32438 32438 E AndroidRuntime: 	... 10 more

07-07 14:40:18.343   640  1282 W ActivityManager:   Force finishing activity io.keybase.ossifrage/.MainActivity
```

**Comment by joshblum** [comment]
fixed via https://github.com/keybase/client/pull/12579
