### ISSUE TITLE
Keybase KBFS Panic

### ISSUE THREAD

**Issue by Jabbslad** [keybase/client#12821]
```
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
keybase version 2.3.0-20180710171051+64615d6258
my log id: 5e9efa9ee4a2dd8052ce741c
```

KBFS services panic when processing gheet docs. 

Also, haven't found a way to remove the files so I can access my other files on kbfs. Any ideas?

```
2018-07-15T17:49:11.448749+01:00 ▶ [DEBU kbfs(FBO 2ce9810f) folder_branch_ops.go:2389] 0ee Final op: rm budget-planner.gsheet
panic: Unknown ID suffix  0

goroutine 370 [running]:
github.com/keybase/kbfs/tlf.ID.Type(0x0, 0x0, 0x0)
	/Users/build/go/src/github.com/keybase/kbfs/tlf/id.go:252 +0x65
github.com/keybase/kbfs/libkbfs.buildCanonicalPathForTlf(0x0, 0x0, 0xc422b0d0b8, 0x1, 0x1, 0x1, 0x1)
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/path.go:72 +0x2b
github.com/keybase/kbfs/libkbfs.path.CanonicalPathString(0x0, 0x0, 0x0, 0x0, 0xc420240af0, 0x1, 0x1, 0x0, 0xc3e987)
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/path.go:162 +0x92
github.com/keybase/kbfs/libkbfs.(*rmOp).ToEditNotification(0xc422d38d00, 0xcf, 0x26f90750, 0xed2dd6b24, 0x5c57b60, 0xc420c4c2d0, 0x46, 0xc4205247e0, 0x20, 0xd9fa5b930f81e92c, ...)
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/ops.go:641 +0x604
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).makeEditNotifications(0xc420800800, 0x535e000, 0xc42059d620, 0xc42054a600, 0xc420514450, 0x21, 0xc420c4c2d0, 0x46, 0x2809deb8, 0xed2dd6b24, ...)
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:2390 +0x79f
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).handleUnflushedEditNotifications(0xc420800800, 0x535e000, 0xc42059d620, 0xc42054a600, 0xc420514450, 0x21, 0xc420c4c2d0, 0x46, 0x2809deb8, 0xed2dd6b24, ...)
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:2427 +0xca
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).setHeadLocked(0xc420800800, 0x535e000, 0xc42059d620, 0xc420463e50, 0xc42054a400, 0xc4205a0c60, 0x21, 0xc420c4c2d0, 0x46, 0x310170c2, ...)
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:817 +0xb0d
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).setInitialHeadTrustedLocked(0xc420800800, 0x535e000, 0xc42059d620, 0xc421e3ce50, 0xc42054a400, 0xc4205a0c60, 0x21, 0xc420c4c2d0, 0x46, 0x310170c2, ...)
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:924 +0x16f
github.com/keybase/kbfs/libkbfs.(*folderBranchOps).SetInitialHeadFromServer.func2(0x0, 0x0)
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:1763 +0x5d8
github.com/keybase/kbfs/libkbfs.runUnlessCanceled.func1(0xc4214ec300, 0xc423a49300)
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/util.go:28 +0x27
created by github.com/keybase/kbfs/libkbfs.runUnlessCanceled
	/Users/build/go/src/github.com/keybase/kbfs/libkbfs/util.go:27 +0x77
2018-07-15T17:49:20.502433+01:00 ▶ [INFO kbfs init.go:446] 001 KBFS version 1.0.2-20180710171142+420f4044
```

**Comment by strib** [comment]
Logs: 5e9efa9ee4a2dd8052ce741c

This is a dup of #12817.  Let's track it there.  I'll have a fix out soon I hope.
