### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by ofek** [keybase/client#12876]
```
Service:                                                              
    status:    running                                                
    version:   2.3.0-20180710101247+64615d6258                        
    log:       C:\Users\Ofek\AppData\Local\Keybase\keybase.service.log
                                                                      
Updater:                                                              
    log:       C:\Users\Ofek\AppData\Local\Keybase\keybase.updater.log
                                                                      
Platform Information:                                                 
    OS:        windows                                                
    OS vers:   Microsoft Windows [Version 6.1.7601]                   
    Runtime:   go1.10.3                                               
    Arch:      386                                                    
                                                                      
Client:                                                               
    version:   2.3.0-20180710101247+64615d6258                        
                                                                      
Desktop app:                                                          
    status:    running                                                
    version:   2.3.0-20180710101818+64615d6258                        
    log:       C:\Users\Ofek\AppData\Local\Keybase\Keybase.app.log    
```

```
Error: ERROR CODE 201 - no sessionArgs available since no login path worked in method keybase.1.home.homeMarkViewed at new i (file:///C:/Users/Ofek/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:420688) at file:///C:/Users/Ofek/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:421217 at s (file:///C:/Users/Ofek/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:421256) at _rpcClient.invoke.t (file:///C:/Users/Ofek/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:229672) at file:///C:/Users/Ofek/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1743390 at e.t.Deferrals.e._call (file:///C:/Users/Ofek/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1628073) at file:///C:/Users/Ofek/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1628224 at s (file:///C:/Users/Ofek/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1627853) at e.t.Deferrals.e._fulfill (file:///C:/Users/Ofek/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1628183) at s (file:///C:/Users/Ofek/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1627387)
```

**Comment by ofek** [comment]
It appears the gui prevents the cli login gtk window from opening. Quitting the gui then `keybase login user` works.

However, when typing the pw in the pop-up I still get `- WARNING fixHeaders: session required, but error getting sessionArgs: Login required: no sessionArgs available since no login path worked [tags:API=xxkIpLyzr__R]` every ~15 seconds in the terminal (cmd).
