### ISSUE TITLE
Error logging into Keybase for windows

### ISSUE THREAD

**Issue by desbest** [keybase/client#13216]
I tried to login with keybase for windows and I got an error.

my log id: aaa48d6513cf838b28b92a1c

**Error details**

> TypeError: e.createDataURL is not a function

**Stack trace**

```
TypeError: e.createDataURL is not a function
    at _.render (file:///C:/Users/User/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1678151)
    at vo (file:///C:/Users/User/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1857290)
    at Co (file:///C:/Users/User/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1862174)
    at lr (file:///C:/Users/User/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1871751)
    at ur (file:///C:/Users/User/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1872058)
    at Hr (file:///C:/Users/User/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1875632)
    at Ur (file:///C:/Users/User/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1875103)
    at Lr (file:///C:/Users/User/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1874929)
    at Rr (file:///C:/Users/User/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1874302)
    at mr (file:///C:/Users/User/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:1873549)
```

**Component stack trace**

```
in _
    in div
    in _
    in T
    in div
    in _
    in div
    in _
    in O
    in F
    in Connect(F)
    in d
    in div
    in l
    in w
    in div
    in l
    in w
    in F
    in Connect(F)
    in d
    in g
    in F
    in Connect(F)
    in div
    in a
    in l
    in Unknown
```

**Comment by zanderz** [comment]
Thanks for the report, we've been seeing this today. Would you care to try out our fix for this problem?
https://prerelease.keybase.io/windows/Keybase_2.5.0-20180808100530%2B40640f25ff.386.msi

**Comment by desbest** [comment]
Now I just tried to scan the qr code with my phone so I could login on windows and it's not recognising the qr code.
