### ISSUE TITLE
Error 218 when trying to open KBFS folder in keybase-gui

### ISSUE THREAD

**Issue by virtualdxs** [keybase/client#13322]
When trying to open a KBFS folder in keybase-gui on Arch Linux, fully updated as of now, I get:

    Error: ERROR CODE 218 - method 'simpleFSListRecursiveToDepth' not found in protocol 'keybase.1.SimpleFS' in method keybase.1.SimpleFS.simpleFSListRecursiveToDepth 
        at new r (file:///usr/share/keybase-app/desktop/dist/index.bundle.js:1:448413) 
        at file:///usr/share/keybase-app/desktop/dist/index.bundle.js:1:448942 at u (file:///usr/share/keybase-app/desktop/dist/index.bundle.js:1:448981) 
        at _rpcClient.invoke.t (file:///usr/share/keybase-app/desktop/dist/index.bundle.js:1:252523) at file:///usr/share/keybase-app/desktop/dist/index.bundle.js:1:1748538 
        at e.t.Deferrals.e._call (file:///usr/share/keybase-app/desktop/dist/index.bundle.js:1:1648635) 
        at file:///usr/share/keybase-app/desktop/dist/index.bundle.js:1:1648786 
        at s (file:///usr/share/keybase-app/desktop/dist/index.bundle.js:1:1648415) 
        at e.t.Deferrals.e._fulfill (file:///usr/share/keybase-app/desktop/dist/index.bundle.js:1:1648745) 
        at s (file:///usr/share/keybase-app/desktop/dist/index.bundle.js:1:1647949)

**Comment by strib** [comment]
cc: @jzila @songgao.  You might be running an updated GUI process, without having updated (or restarted) KBFS?

**Comment by virtualdxs** [comment]
That's almost certainly it. I'll restart kbfs and report back.

**Comment by jzila** [comment]
Yep that's definitely it.

**Comment by virtualdxs** [comment]
Yep, that did it. Thanks!
