### ISSUE TITLE
Android background crash in libkb.GlobalContext.Trace

### ISSUE THREAD

**Issue by eliasnaur** [keybase/client#13334]
I saw this crash in my adb logcat output today:

```
08-17 15:02:31.837  5276  5276 E oid.apps.photo: Not starting debugger since process cannot load the jdwp agent.
08-17 15:02:31.889  5299  5299 E ndroid.contact: Not starting debugger since process cannot load the jdwp agent.
08-17 15:02:31.896  5287  5287 E id.partnersetu: Not starting debugger since process cannot load the jdwp agent.
08-17 15:02:31.897  5294  5294 E ybase.ossifrag: Not starting debugger since process cannot load the jdwp agent.
08-17 15:02:31.926  5315  5315 E le.android.kee: Not starting debugger since process cannot load the jdwp agent.
08-17 15:02:32.366  5299  5401 E ndroid.contact: The String#value field is not present on Android versions >= 6.0
08-17 15:02:32.799  5294     0 E Go      : panic: runtime error: invalid memory address or nil pointer dereference
08-17 15:02:32.799  5294     0 E Go      : [signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0xd5d88c10]
08-17 15:02:32.799  5294     0 E Go      : 
08-17 15:02:32.799  5294     0 E Go      : goroutine 17 [running, locked to thread]:
08-17 15:02:32.799  5294     0 E Go      : github.com/keybase/client/go/libkb.(*GlobalContext).Trace(0x0, 0xd668b604, 0xe, 0xd74b0db8, 0x9173a03c)
08-17 15:02:32.799  5294     0 E Go      : 	/tmp/go-android/src/github.com/keybase/client/go/libkb/util.go:509 +0x14
08-17 15:02:32.799  5294     0 E Go      : github.com/keybase/client/go/bind.BackgroundSync()
08-17 15:02:32.799  5294     0 E Go      : 	/tmp/go-android/src/github.com/keybase/client/go/bind/keybase.go:354 +0x44
08-17 15:02:32.799  5294     0 E Go      : _/var/folders/4g/mh1d9tz91d3f9p5p716dkdd40000gn/T/gomobile-work-849699548/gomobile_bind.proxykeybase__BackgroundSync()
08-17 15:02:32.799  5294     0 E Go      : 	/var/folders/4g/mh1d9tz91d3f9p5p716dkdd40000gn/T/gomobile-work-849699548/gomobile_bind/go_keybasemain.go:326 +0x14
08-17 15:02:32.799  5294     0 E Go      : _/var/folders/4g/mh1d9tz91d3f9p5p716dkdd40000gn/T/gomobile-work-849699548/gomobile_bind._cgoexpwrap_b7f20329c467_proxykeybase__BackgroundSync()
08-17 15:02:32.799  5294     0 E Go      : 	_/var/folders/4g/mh1d9tz91d3f9p5p716dkdd40000gn/T/gomobile-work-849699548/gomobile_bind/_obj/_cgo_gotypes.go:506 +0x14
```

I'm running 2.5.0-20180815151913+8eb2dbfe76 according to the "About" screen.

**Comment by maxtaco** [comment]
thanks for the report

cc @keybase/react-hackers  and @mmaxim

**Comment by maxtaco** [comment]
can you send feedback from the app, so we can see the rest of the log? Thanks

**Comment by mmaxim** [comment]
Thanks for the report @eliasnaur, we have been trying to track this down.
