### ISSUE TITLE
[2.7.0][Error][React] Scrolling chats list causes error.

### ISSUE THREAD

**Issue by junderw** [keybase/client#13749]
It looks like it might have something to do with my Big Teams.

I have a ton of Big Teams... and this Error doesn't occur when I expand my private chats (also lots) and scroll around the private chats... once I start scrolling up and down around my big teams, the error occurs.

my log id: b20965c409da4477a981b91c

**Comment by junderw** [comment]
The logs shown in my Keybase window:
```
Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2709045
    at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2709148)
    at Ao (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2786146)
    at Object.enqueueSetState (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2755047)
    at t.y.setState (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2802492)
    at t.value (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:570780)
    at t.value (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:574585)
    at t.value (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:573449)
    at t.value (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:570626)
    at gs (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2792482)
```

```
 in ReactList
    in div
    in div
    in F
    in I_
    in t
    in Inbox
    in Connect(Inbox)
    in div
    in zm
    in _
    in div
    in l
    in F
    in div
    in l
    in F
    in y
    in Connect(y)
    in _
    in g
    in y
    in Connect(y)
    in div
    in a
    in l
    in Unknown
```
