### ISSUE TITLE
msgpack decode error + macOS Error Code 1601 when verifying new device

### ISSUE THREAD

**Issue by 2075** [keybase/client#14649]
I don't know if it is a duplicate issue or not.

I am running macOS Mojave, 10.14.1

When trying to add and verify another machine running Arch, I get errors on both ends:

arch linux: 
```************************************************************
* Name your new device!                                    *
************************************************************

Enter a public name for this device: machine

Type this verification code into your other device:

a b c d e f g h

If you are using the command line client on your other device, run this command:

	keybase device add

It will then prompt you for the verification code above.

▶ ERROR {-} Error in transport: msgpack decode error [pos 0]: API network error: doRetry failed, attempts: 5, timeout 10s, last err: Get https://api-0.core.keybaseapi.com/_/api/1.0/kex2/receive.json?I=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&low=1&poll=5000&receiver=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy EOF
```
macos: klick "add new..."

```Error: ERROR CODE 1601 - API network error: Get https://api-0.core.keybaseapi.com/_/api/1.0/merkle/path.json?last=3941183&load_deleted=1&load_reset_chain=1&poll=10&sig_hints_low=7&uid=xxxxxxxxxxxxxxxxxxxxxxxx: EOF in method keybase.1.device.deviceAdd at new d (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:449485) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:450014 at u (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:450053) at _rpcClient.invoke.t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:471658) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~unlock-folders.bundle.js:1:881573 at e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~unlock-folders.bundle.js:1:826452) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~unlock-folders.bundle.js:1:826592 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~unlock-folders.bundle.js:1:826232) at e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~unlock-folders.bundle.js:1:826562) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~unlock-folders.bundle.js:1:825763)
```

after trying many times, macos client responds with:

```Error: ERROR CODE 504 - RPC error 504: Error: DB error in method keybase.1.device.deviceAdd at new d (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:449485) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:450014 at u (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:450053) at _rpcClient.invoke.t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:471658) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~unlock-folders.bundle.js:1:881573 at e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~unlock-folders.bundle.js:1:826452) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~unlock-folders.bundle.js:1:826592 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~unlock-folders.bundle.js:1:826232) at e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~unlock-folders.bundle.js:1:826562) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~unlock-folders.bundle.js:1:825763)
```

**Comment by maxtaco** [comment]
We just had a little bit of downtime, can you try it again?  Back out to the start on both machines. Thanks

**Comment by Kugiemon** [comment]
I am getting this same Error code now. Can someone please help me with this?! Error code 4207

ERROR CODE 4207 - Sorry, you do not qualify. in method stellar.1.local.airdropRegisterLocal

n@index.android.bundle:2628:721
f@index.android.bundle:2628:1267
convertToError@index.android.bundle:2628:172
index.android.bundle:4276:4221
index.android.bundle:2665:597
_call@index.android.bundle:2634:1029
index.android.bundle:2634:1173
c@index.android.bundle:2634:808
_fulfill@index.android.bundle:2634:1139
h@index.android.bundle:2634:349
handler@index.android.bundle:4280:2610
index.android.bundle:4280:991
index.android.bundle:2643:3130
index.android.bundle:2643:3068
_call@index.android.bundle:2634:1029
index.android.bundle:2634:1173
c@index.android.bundle:2634:808
_fulfill@index.android.bundle:2634:1139
h@index.android.bundle:2634:349
_call_cb@index.android.bundle:2643:1843
_dispatch_handle_response@index.android.bundle:2643:1675
_dispatch@index.android.bundle:2643:1479
_get_msg@index.android.bundle:2644:1529
packetize_data@index.android.bundle:2644:1833
index.android.bundle:4279:474
value@index.android.bundle:44:1268
value@index.android.bundle:21:3504
index.android.bundle:21:754
value@index.android.bundle:21:2710
value@index.android.bundle:21:726
value@[native code]

**Comment by Kugiemon** [comment]
I get all checks in green on the verifier page.
