### ISSUE TITLE
Failure to start kbfs

### ISSUE THREAD

**Issue by d4gg4d** [keybase/client#15774]
Failure to fusermount to unmount /run/user/1000/keybase/kbfs folder during startup (linux-ubuntu-18.04.1).

```
  Active: failed (Result: exit-code) since Wed 2019-01-30 11:08:54 EET; 5min ago
  Process: 28198 ExecStart=/usr/bin/kbfsfuse -debug -log-to-file (code=exited, status=2)
  Process: 28180 ExecStartPre=/bin/sh -c fusermount -uz "$(keybase config get -d -b mountdir)" (code=exited, status=1/FAILURE)
 Main PID: 28198 (code=exited, status=2)

```

fusermount failure message is following

```
~ > /bin/sh -c fusermount -uz "$(keybase config get -d -b mountdir)"
fusermount: missing mountpoint argument
~ > keybase config get -d -b mountdir
/run/user/1000/keybase/kbfs
```
and that folder is empty

```
ls -la "$(keybase config get -d -b mountdir)"
total 0
drwxrwxr-x 2 <user> <user>  40 tammi 30 09:56 .
drwxrwxr-x 3 <user> <user> 180 tammi 30 11:08 ..
```

my log id: 9394b649798ebcf0f6f0e71c

**Comment by d4gg4d** [comment]
Hmm, seems that the kbfsfuse goes belly up:

```
~ > kbfsfuse
▶ INFO KBFS version 1.0.2-20190125162145+5b9b6acf43
panic: Could not open conflict resolver DB: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000033]

goroutine 12 [running]:
github.com/keybase/client/go/kbfs/libkbfs.openCRDB(0x5585a91334e0, 0xc420320700, 0xc4200b8240)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/kbfs/libkbfs/conflict_resolver.go:3613 +0xf4
github.com/keybase/client/go/kbfs/libkbfs.NewConfigLocal(0x5585a912d4c0, 0x5585a9ab5cc8, 0xc42000d820, 0xc420044cf0, 0x23, 0x1, 0x5585a9126840, 0xc42004e900, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/kbfs/libkbfs/config_local.go:475 +0x64d
github.com/keybase/client/go/kbfs/libkbfs.doInit(0x5585a911ee60, 0xc4200d4030, 0x5585a9126840, 0xc42004e900, 0x0, 0x5585a8759124, 0x87, 0x5585a87591ab, 0x8b, 0x0, ...)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/kbfs/libkbfs/init.go:610 +0x2f9
github.com/keybase/client/go/kbfs/libkbfs.InitWithLogPrefix.func2(0x5585a911ee60, 0xc4200d4030, 0x5585a9126840, 0xc42004e900, 0xc420310ea0, 0x0, 0x0, 0x5585a912a400, 0xc42004ef00, 0x5585a86f77aa, ...)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/kbfs/libkbfs/init.go:551 +0xf8
created by github.com/keybase/client/go/kbfs/libkbfs.InitWithLogPrefix
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/kbfs/libkbfs/init.go:549 +0x261
```

**Comment by d4gg4d** [comment]
found solution `rm ~/.local/share/keybase`

**Comment by strib** [comment]
For the record, you only need to remove one directory in there.  See #15751.
