### ISSUE TITLE
Crash on Android KK

### ISSUE THREAD

**Issue by Avamander** [keybase/client#16187]
On Android KK 4.4 LG D605 I'm now experiencing a crash with this stacktrace:
```
02-22 12:25:46.815 20263 20654 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=io.keybase.ossifrage/.MainActivity (has extras)} from pid 20622

02-22 12:25:47.166 20263 20769 I ActivityManager: Start proc io.keybase.ossifrage for activity io.keybase.ossifrage/.MainActivity: pid=9947 uid=10039 gids={50039, 3003, 1006, 1028, 1015}

02-22 12:25:47.316  9947  9947 I FirebaseInitProvider: FirebaseApp initialization unsuccessful

02-22 12:25:47.326  9947  9947 I dalvikvm: Could not find method android.content.Context.getExternalMediaDirs, referenced from method android.support.v4.content.FileProvider.parsePathStrategy

02-22 12:25:47.326  9947  9947 W dalvikvm: VFY: unable to resolve virtual method 832: Landroid/content/Context;.getExternalMediaDirs ()[Ljava/io/File;

02-22 12:25:47.336  9947  9947 I iKBNativeLogger: [1550802287347,"MainApplication created"]

02-22 12:25:47.346  9947  9947 I fb-UnpackingSoSource: dso store is up-to-date: /data/data/io.keybase.ossifrage/lib-main

02-22 12:25:47.356  9947  9947 W dalvikvm: Unable to resolve superclass of Lcom/evernote/android/job/v21/PlatformJobService; (78)

02-22 12:25:47.356  9947  9947 W dalvikvm: Link of class 'Lcom/evernote/android/job/v21/PlatformJobService;' failed

02-22 12:25:47.356  9947  9947 E dalvikvm: Could not find class 'com.evernote.android.job.v21.PlatformJobService', referenced from method com.evernote.android.job.JobApi.isSupported

02-22 12:25:47.356  9947  9947 W dalvikvm: VFY: unable to resolve const-class 3497 (Lcom/evernote/android/job/v21/PlatformJobService;) in Lcom/evernote/android/job/JobApi;

02-22 12:25:47.356  9947  9947 W dalvikvm: Unable to resolve superclass of Lcom/evernote/android/job/v21/PlatformJobService; (78)

02-22 12:25:47.356  9947  9947 W dalvikvm: Link of class 'Lcom/evernote/android/job/v21/PlatformJobService;' failed

02-22 12:25:47.356  9947  9947 E dalvikvm: Could not find class 'com.evernote.android.job.v21.PlatformJobService', referenced from method com.evernote.android.job.JobApi.isSupported

02-22 12:25:47.356  9947  9947 W dalvikvm: VFY: unable to resolve const-class 3497 (Lcom/evernote/android/job/v21/PlatformJobService;) in Lcom/evernote/android/job/JobApi;

02-22 12:25:47.356  9947  9947 W dalvikvm: Unable to resolve superclass of Lcom/evernote/android/job/v21/PlatformJobService; (78)

02-22 12:25:47.356  9947  9947 W dalvikvm: Link of class 'Lcom/evernote/android/job/v21/PlatformJobService;' failed

02-22 12:25:47.356  9947  9947 E dalvikvm: Could not find class 'com.evernote.android.job.v21.PlatformJobService', referenced from method com.evernote.android.job.JobApi.isSupported

02-22 12:25:47.356  9947  9947 W dalvikvm: VFY: unable to resolve const-class 3497 (Lcom/evernote/android/job/v21/PlatformJobService;) in Lcom/evernote/android/job/JobApi;

02-22 12:25:47.366  9947  9947 I dalvikvm: Could not find method android.app.NotificationManager.getNotificationChannel, referenced from method com.google.android.gms.common.GoogleApiAvailability.zaa

02-22 12:25:47.366  9947  9947 W dalvikvm: VFY: unable to resolve virtual method 410: Landroid/app/NotificationManager;.getNotificationChannel (Ljava/lang/String;)Landroid/app/NotificationChannel;

02-22 12:25:47.376  9947  9947 I dalvikvm: Could not find method android.app.NotificationManager.getNotificationChannel, referenced from method com.google.android.gms.common.GoogleApiAvailability.setDefaultNotificationChannelId

02-22 12:25:47.376  9947  9947 W dalvikvm: VFY: unable to resolve virtual method 410: Landroid/app/NotificationManager;.getNotificationChannel (Ljava/lang/String;)Landroid/app/NotificationChannel;

02-22 12:25:47.386  9947  9947 I dalvikvm: Could not find method android.content.pm.PackageManager.getPackageInstaller, referenced from method com.google.android.gms.common.GooglePlayServicesUtilLight.isUninstalledAppPossiblyUpdating

02-22 12:25:47.386  9947  9947 W dalvikvm: VFY: unable to resolve virtual method 994: Landroid/content/pm/PackageManager;.getPackageInstaller ()Landroid/content/pm/PackageInstaller;

02-22 12:25:47.386  9947  9947 I dalvikvm: Could not find method android.content.pm.PackageManager.isInstantApp, referenced from method com.google.android.gms.common.wrappers.PackageManagerWrapper.isCallerInstantApp

02-22 12:25:47.386  9947  9947 W dalvikvm: VFY: unable to resolve virtual method 1000: Landroid/content/pm/PackageManager;.isInstantApp (Ljava/lang/String;)Z

02-22 12:25:47.406  9947  9947 W dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/JobIntentService$JobServiceEngineImpl; (79)

02-22 12:25:47.406  9947  9947 W dalvikvm: Link of class 'Landroid/support/v4/app/JobIntentService$JobServiceEngineImpl;' failed

02-22 12:25:47.416  9947  9947 E dalvikvm: Could not find class 'android.support.v4.app.JobIntentService$JobServiceEngineImpl', referenced from method android.support.v4.app.JobIntentService.onCreate

02-22 12:25:47.416  9947  9947 W dalvikvm: VFY: unable to resolve new-instance 797 (Landroid/support/v4/app/JobIntentService$JobServiceEngineImpl;) in Landroid/support/v4/app/JobIntentService;

02-22 12:25:47.416  9947  9947 W dalvikvm: Unable to resolve superclass of Landroid/support/v4/app/JobIntentService$JobServiceEngineImpl; (79)

02-22 12:25:47.416  9947  9947 W dalvikvm: Link of class 'Landroid/support/v4/app/JobIntentService$JobServiceEngineImpl;' failed

02-22 12:25:47.486  9947  9947 I dalvikvm: Could not find method android.app.Activity.requestPermissions, referenced from method com.facebook.react.ReactActivityDelegate.requestPermissions

02-22 12:25:47.486  9947  9947 W dalvikvm: VFY: unable to resolve virtual method 133: Landroid/app/Activity;.requestPermissions ([Ljava/lang/String;I)V

02-22 12:25:47.506  9947  9947 E dalvikvm: Could not find class 'android.security.keystore.KeyPermanentlyInvalidatedException', referenced from method io.keybase.ossifrage.KeyStore.retrieveSecret

02-22 12:25:47.506  9947  9947 W dalvikvm: VFY: unable to resolve instanceof 474 (Landroid/security/keystore/KeyPermanentlyInvalidatedException;) in Lio/keybase/ossifrage/KeyStore;

02-22 12:25:47.556  9947  9947 I iKBNativeLogger: [1550802287564,"KeyStore: initialized"]

02-22 12:25:48.327  9947  9968 I GoLog   : Go: Initializing: home: /data/data/io.keybase.ossifrage/files mobileSharedHome: 

02-22 12:25:48.347  9947  9963 I GoLog   : Go: Using log: /data/data/io.keybase.ossifrage/files/service.log

02-22 12:25:48.347  9947  9963 I GoLog   : Go: Using eklog: /data/data/io.keybase.ossifrage/files/service.log.ek

02-22 12:25:48.347  9947  9963 I GoLog   : Go: setting GOMAXPROCS to: 1 previous: 2

02-22 12:25:48.347  9947  9963 I GoLog   : Go: DNS Server: 1.1.1.1

02-22 12:25:48.567  9947  9947 I iKBNativeLogger: [1550802288572,"KeyStore: setting up key store for keybase:"]

02-22 12:25:48.587   303   303 W keystore: Could not read CACERT_keybase_keybase-rsa-wrapper_

02-22 12:25:48.587  9947  9947 I iKBNativeLogger: [1550802288598,"KeyStore: finished setting up key store for keybase:"]

02-22 12:25:48.597  9947  9947 I iKBNativeLogger: [1550802288603,"KeyStore: retrieving secret for keybase:avamander"]

02-22 12:25:48.597   303   303 W keystore: Could not read CACERT_keybase_keybase-rsa-wrapper_

02-22 12:25:48.637  9947  9947 I iKBNativeLogger: [1550802288642,"KeyStore: retrieved 32-byte secret for keybase:avamander"]

02-22 12:25:50.279  9947  9977 E dalvikvm: dlopen("/data/app-lib/io.keybase.ossifrage-1/libreactnativejni.so") failed: dlopen failed: could not load library "libjsc.so" needed by "libreactnativejni.so"; caused by cannot locate symbol "signal" referenced by "libjsc.so"...

02-22 12:25:50.279  9947  9977 E SoLoader: couldn't find DSO to load: libreactnativejni.so caused by: dlopen failed: could not load library "libjsc.so" needed by "libreactnativejni.so"; caused by cannot locate symbol "signal" referenced by "libjsc.so"...

02-22 12:25:50.279  9947  9977 W dalvikvm: Exception Ljava/lang/UnsatisfiedLinkError; thrown while initializing Lcom/facebook/react/bridge/NativeMap;

02-22 12:25:50.279  9947  9977 W dalvikvm: threadid=12: thread exiting with uncaught exception (group=0x4180ace0)

02-22 12:25:50.279  9947  9977 E AndroidRuntime: FATAL EXCEPTION: Thread-5103

02-22 12:25:50.279  9947  9977 E AndroidRuntime: Process: io.keybase.ossifrage, PID: 9947

02-22 12:25:50.279  9947  9977 E AndroidRuntime: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libreactnativejni.so caused by: dlopen failed: could not load library "libjsc.so" needed by "libreactnativejni.so"; caused by cannot locate symbol "signal" referenced by "libjsc.so"...

02-22 12:25:50.279  9947  9977 E AndroidRuntime: at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:703)

02-22 12:25:50.279  9947  9977 E AndroidRuntime: at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:564)

02-22 12:25:50.279  9947  9977 E AndroidRuntime: at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:500)

02-22 12:25:50.279  9947  9977 E AndroidRuntime: at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:455)

02-22 12:25:50.279  9947  9977 E AndroidRuntime: at com.facebook.react.bridge.ReactBridge.staticInit(ReactBridge.java:18)

02-22 12:25:50.279  9947  9977 E AndroidRuntime: at com.facebook.react.bridge.NativeMap.<clinit>(NativeMap.java:19)

02-22 12:25:50.279  9947  9977 E AndroidRuntime: at com.facebook.react.bridge.JSCJavaScriptExecutorFactory.create(JSCJavaScriptExecutorFactory.java:21)

02-22 12:25:50.279  9947  9977 E AndroidRuntime: at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:917)

02-22 12:25:50.279  9947  9977 E AndroidRuntime: at java.lang.Thread.run(Thread.java:841)

02-22 12:25:50.289 20263 20274 W ActivityManager:   Force finishing activity io.keybase.ossifrage/.MainActivity
```

**Comment by the-exodus** [comment]
Guessing introduced by #79303bd ?

**Comment by Avamander** [comment]
It's possible that it was introduced by 79303bd but I can't check any longer.

**Comment by Avamander** [comment]
The bug still exists even on the latest Keybase version.

**Comment by Avamander** [comment]
They said this isn't going to be fixed.
