### ISSUE TITLE
Cannot cancel or remove a failed stellar transaction

### ISSUE THREAD

**Issue by ddombrowsky** [keybase/client#16350]
In my stellar wallet in keybase, I have a failed transaction

```
Account does not exist on the network because it does not have minimum balance (tx_no_source_account)
```

Cancelling it fails with 

```
Error: ERROR CODE 218 - Account does not exist on the network because it does not have minimum balance (tx_no_source_account) in method stellar.1.local.cancelPaymentLocal at new s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:675882) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:676411 at d (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:676450) at _rpcClient.invoke.t (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:668341) at file:///opt/keybase/resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~tracker2~unlock-folders.bundle.js:1:872802 at e._call (file:///opt/keybase/resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~tracker2~unlock-folders.bundle.js:1:820962) at file:///opt/keybase/resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~tracker2~unlock-folders.bundle.js:1:821102 at s (file:///opt/keybase/resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~tracker2~unlock-folders.bundle.js:1:820742) at e._fulfill (file:///opt/keybase/resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~tracker2~unlock-folders.bundle.js:1:821072) at s (file:///opt/keybase/resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker~tracker2~unlock-folders.bundle.js:1:820273)
```

How can I get this transaction to go away from the UI?

my log id: 499d5916f149c8c5022d461c

**Comment by strib** [comment]
cc: @patrickxb
