### ISSUE TITLE
Panic on attempting to sign or PGP sign with message

### ISSUE THREAD

**Issue by ethindp** [keybase/client#16841]
Whenever attempting to use commands such as:
```
keybase pgp sign -i file -m "message"
```
Or
```
keybase sign -i file -m "message"
```
The following panic occurs:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x18bfecb]

goroutine 1 [running]:
github.com/keybase/client/go/client.(*UnixFilter).Close(0xc042248468, 0x225cd60, 0xc0422f1310, 0x0, 0x225cd60)
        c:/work/src/github.com/keybase/client/go/client/files.go:373 +0x3b
github.com/keybase/client/go/client.(*CmdSign).Run(0xc042248460, 0xc0422481c0, 0x30a6420)
        c:/work/src/github.com/keybase/client/go/client/cmd_sign.go:102 +0x21a
main.mainInner(0xc042159000, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/work/src/github.com/keybase/client/go/keybase/main.go:247 +0x77e
main.main()
        c:/work/src/github.com/keybase/client/go/keybase/main.go:71 +0xcb
```
My log ID for this issue is is 8621bc30d1ff112558f8b21c.

**Comment by zapu** [comment]
Thank you, we will look into it
