### ISSUE TITLE
Cannot view message history for user on desktop client

### ISSUE THREAD

**Issue by eblanton** [keybase/client#17183]
I have received a message from a keybase user that I cannot receive in the desktop Linux keybase client.  I can read it fine on the mobile client.  On the desktop client I get the following error at the top:

```
Error: ERROR CODE 205 - Unable to decrypt chat message (transient): Not found: Key for user in method chat.1.local.getThreadNonblock at new s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:712052) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:712581 at c (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:712620) at _rpcClient.invoke.t (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:1056471) at file:///opt/keybase/resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker2~unlock-folders.bundle.js:1:1384165 at e._call (file:///opt/keybase/resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker2~unlock-folders.bundle.js:1:903918) at file:///opt/keybase/resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker2~unlock-folders.bundle.js:1:904058 at s (file:///opt/keybase/resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker2~unlock-folders.bundle.js:1:903698) at e._fulfill (file:///opt/keybase/resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker2~unlock-folders.bundle.js:1:904028) at s (file:///opt/keybase/resources/app/desktop/dist/vendors~main~menubar~pinentry~tracker2~unlock-folders.bundle.js:1:903229)
```

I have restarted the Keybase client with `run_keybase` and the message history with this user remains unreadable.  The mobile client reads it all fine.

my log id: b2697a7f73b120a321c3bb1c

**Comment by ennorehling** [comment]
I have the same problem after changing computers. I've never used the mobile client, but switched first from Windows to macOS, then to Linux.
