### ISSUE TITLE
Keybase on MacOS Catalina, 10.15 Beta (19A471t)

### ISSUE THREAD

**Issue by BigElectricCat** [keybase/client#17835]
[write something useful and descriptive here]

my log id: 5009374845712c56b197fc1c

**Comment by jgreever** [comment]
OS: 10.15 Beta (19A471t) (Catalina)

Error when starting the app for the first time after the OS upgrade. Worked on MacOS 10.14 (Mojave)

```
Keybase Install Error
We were unable to load KBFS (Fuse kext). This may be due to a limitation in MacOS where there aren't any device slots available. Device slots can be taken up by apps such as VMWare, VirtualBox, anti-virus programs, VPN programs and Intel HAXM.

Please run `keybase log send` to report the error.
```

Unable to manually enable Keybase in Finder

`Error: /keybase is unavailable. Please try again. at _o.a.readdir (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:3034045) at FSReqWrap.oncomplete (fs.js:141:20)`

my log id: 1e972c0365c32d325d3e0c1c

**Comment by tav** [comment]
I also have the same issue on 10.15 beta — my log ID is `4fa470c470f83241a97d791c`.

I've tried the tricks that used to work in the past to free up device slots:

```
sudo kextunload -b com.apple.filesystems.smbfs
sudo kextunload -b com.intel.kext.intelhaxm
```

I've also added Keybase to the list of apps with "Full Disk Access" under the Privacy tab of System Preferences / Security & Privacy. But nothing seems to work :(

Any idea what might be going wrong? And anything I can do to help debug the issue?

**Comment by ukd1** [comment]
there is a "working" fix in #17796 btw

**Comment by strib** [comment]
Catalina support will be arriving in the next release, hopefully out next week sometime.

**Comment by ssx** [comment]
@strib can you ping this issue when the Catalina compatible version is released, please! 😇

**Comment by strib** [comment]
Keybase 4.4.0 (out today) has better file system support for Catalina now.  Please let us know if you have more problems with it.  Note that the `/keybase` mount point is no longer viable on fresh installs of Catalina due to macOS namespace restrictions, so now we mount at `/Volumes/Keybase` if `/keybase` does not already exist.

**Comment by klevermonicker** [comment]
Still getting this error on Catalina 10.15 Beta (19A558d) using version 4.4.2 freshly installed as of two days ago.

My log ID is: e13f003b3cfad7a4111ef51c

**Comment by strib** [comment]
@klevermonicker is `/Volumes/Keybase` working for you ok?  And does `/keybase` exist at all?

**Comment by klevermonicker** [comment]
@strib At the time I wrote it wasn't even attempted to use /Volumes/Keybase and /keybase didn't exist. About a day after I posted this an update hit to 4.5.0 and the problem resolved itself with a keybase-redirector showing up in my mount list and files existing in the /Volumes path

**Comment by jms1voalte** [comment]
Just upgraded ... `/keybase/` was apparently moved to a "Security" folder, and KBFS mounted itself on `/Volumes/Keybase/`, which is a royal pain ... just trying to figure out how many scripts I'm going to have to update now because of this.

Thanks. Apple.
