### ISSUE TITLE
crash when parsing (fuzzed) pgp key

### ISSUE THREAD

**Issue by kjk** [keybase/client#18944]
I was exploring adding continuous fuzzing integration with https://fuzzit.dev and found the following crash by running a fuzzer.

I built `github.com/keybase/client/go/fuzz/pgp_key_read` with libFuzzer and ran `./pgp-key-read-fuzzer go/fuzz/pgp_key_read/corpus`

I got the following crash:
```
github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp/packet.(*PrivateKey).parsePrivateKey(0xc00052f180, 0xc0002e8000, 0x15, 0x600, 0x15, 0x600)
	/go2/src/github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp/packet/private_key.go:426 +0x2f4
github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp/packet.(*PrivateKey).parse(0xc00052f180, 0x1a40920, 0xc000227560, 0x22, 0x1a40920)
	/go2/src/github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp/packet/private_key.go:158 +0x442
github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp/packet.Read(0x1a3ff80, 0xc0003a6450, 0xc00005fb01, 0xc0003a6480, 0xc00005fb70, 0x4697ff)
	/go2/src/github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp/packet/packet.go:378 +0x27a
github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp/packet.(*Reader).Next(0xc00005fd50, 0xc00055a600, 0x0, 0x1a40280, 0xc0000ae060)
	/go2/src/github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp/packet/reader.go:38 +0xd8
github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp.ReadEntity(0xc00005fd50, 0xc0004cdf70, 0xc0000ae050, 0x1a27d00)
	/go2/src/github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp/keys.go:416 +0x9c
github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp.ReadKeyRing(0x1a3ff80, 0xc0003a6450, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go2/src/github.com/keybase/client/go/vendor/github.com/keybase/go-crypto/openpgp/keys.go:355 +0x144
github.com/keybase/client/go/libkb.ReadOneKeyFromBytes(0x4096ee0, 0x31, 0x31, 0xc00005fea0, 0x462ac5, 0xc000092058, 0xc0000ae060)
	/go2/src/github.com/keybase/client/go/libkb/pgp_key.go:491 +0xa5
github.com/keybase/client/go/fuzz/pgp_key_read.Fuzz(0x4096ee0, 0x31, 0x31, 0xc000318040)
	/go2/src/github.com/keybase/client/go/fuzz/pgp_key_read/fuzz.go:11 +0x5b
main.LLVMFuzzerTestOneInput(0x4096ee0, 0x31, 0x1a258a8)
	/tmp/go-fuzz-build409463758/gopath/src/github.com/keybase/client/go/fuzz/pgp_key_read/go.fuzz.main/main.go:35 +0x66
main._cgoexpwrap_3f86fdd83110_LLVMFuzzerTestOneInput(0x4096ee0, 0x31, 0x401fae0)
	_cgo_gotypes.go:64 +0x37
==5849== ERROR: libFuzzer: deadly signal
    #0 0x45c1f0 in __sanitizer_print_stack_trace (/go2/src/github.com/keybase/client/pgp-key-read-fuzzer+0x45c1f0)
    #1 0x43b87b in fuzzer::PrintStackTrace() (/go2/src/github.com/keybase/client/pgp-key-read-fuzzer+0x43b87b)
    #2 0x422203 in fuzzer::Fuzzer::CrashCallback() (/go2/src/github.com/keybase/client/pgp-key-read-fuzzer+0x422203)
    #3 0x7fc0e11cc72f  (/lib/x86_64-linux-gnu/libpthread.so.0+0x1272f)
    #4 0x4b71e0 in runtime.raise /tmp/go-fuzz-build409463758/goroot/src/runtime/sys_linux_amd64.s:149

NOTE: libFuzzer has rudimentary signal handlers.
      Combine libFuzzer with AddressSanitizer or similar for better crash reports.
SUMMARY: libFuzzer: deadly signal
MS: 3 ChangeASCIIInt-ShuffleBytes-ChangeBit-; base unit: dbf7acdc587252526f0f7da8a809c5b4a29d99ca
0xc7,0x22,0x4,0x39,0x4,0xe5,0x43,0x14,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x36,0x65,0x67,0x65,0x56,0x65,0x65,0x3b,0xc2,0x0,0x4,0x7f,0x37,0x46,0x69,0x6c,0x65,0x20,0x53,0xa7,0xc7,0x22,0x4,0x2e,0x4,0xe5,0x43,0x1,0x0,0x0,0x0,0x0,0x0,
\xc7\"\x049\x04\xe5C\x14\x00\x00\x00\x00\x00\x00\x00\x006egeVee;\xc2\x00\x04\x7f7File S\xa7\xc7\"\x04.\x04\xe5C\x01\x00\x00\x00\x00\x00
artifact_prefix='./'; Test unit written to ./crash-dbb2cc756343dab4310817515d415838c2058972
Base64: xyIEOQTlQxQAAAAAAAAAADZlZ2VWZWU7wgAEfzdGaWxlIFOnxyIELgTlQwEAAAAAAA==
```

What it says is that if the `xyIEOQTlQxQAAAAAAAAAADZlZ2VWZWU7wgAEfzdGaWxlIFOnxyIELgTlQwEAAAAAAA==` data (after base64-decoding) is fed to `Fuzz()` function in `go/fuzz/pgp_key_read/fuzz.go` then there will be a crash.

If you want to reproduce all the steps:

Run docker because `libFuzzer` is only supported in Linux:

```shell
docker run -v`pwd`:/go2/src/github.com/keybase/client -it golang:1.12.7-buster /bin/bash
```

Inside docker, run:

```shell
# install clang
echo "deb http://apt.llvm.org/buster/ llvm-toolchain-buster main" >> /etc/apt/sources.list
echo "deb-src http://apt.llvm.org/buster/ llvm-toolchain-buster main" >> /etc/apt/sources.list
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -
apt update && apt install -y clang-9 lldb-9 lld-9

## setup go inside the container
# to access code, we've mounted host's $GOPATH under /go2
export GOPATH=/go2
echo $GOPATH
# ensure binaries installed with go get are in $PATH
export PATH="$PATH":/go2/bin
echo $PATH

## run fuzzing locally to make sure it works
# go-fuzz doesn't support Go modules, so let's explicitly turn them off
export GO111MODULE=off

go get -u github.com/dvyukov/go-fuzz/go-fuzz github.com/dvyukov/go-fuzz/go-fuzz-build
```

The build fuzz targets and run with corpus:

```shell
cd /go2/src/github.com/keybase/client

TARGET=nacl-enc-fuzzer
go-fuzz-build -libfuzzer -o ${TARGET}.a github.com/keybase/client/go/fuzz/nacl_enc
clang-9 -fsanitize=fuzzer ${TARGET}.a -o ${TARGET}

# run with corpus
./${TARGET} go/fuzz/nacl_enc/corpus

TARGET=pgp-key-read-fuzzer
go-fuzz-build -libfuzzer -o ${TARGET}.a github.com/keybase/client/go/fuzz/pgp_key_read
clang-9 -fsanitize=fuzzer ${TARGET}.a -o ${TARGET}

# run with corpus
./${TARGET} go/fuzz/pgp_key_read/corpus
```

`./${TARGET} go/fuzz/pgp_key_read/corpus` should crash.

**Comment by maxtaco** [comment]
Thanks for this report, we'll take a look!

**Comment by heronhaye** [comment]
Should be fixed now
