### ISSUE TITLE
ERR 505

### ISSUE THREAD

**Issue by manhito** [keybase/client#19647]
Error: ERROR CODE 505 - DB error in method stellar.1.local.airdropRegisterLocal at new s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:561326) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:561922 at u (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:561961) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:1242674 at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:3018596 at e._call (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2580395) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2580535 at s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2580175) at e._fulfill (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2580505) at s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2579706)
![Screenshot from 2019-09-14 14-18-24](https://user-images.githubusercontent.com/44461740/64904884-acc0df00-d6fa-11e9-9b2f-2cc10dd82ef4.png)

**Comment by Rotehut** [comment]
me too

**Comment by kenorb** [comment]
Related:
- #19644
- #19572
- #19548
- #19515

**Comment by kenorb** [comment]
Related:
- https://github.com/keybase/client/issues/15257#issuecomment-531395333
- #19515
- #19531
- #19548
- #19572
- #19642
- #19644
- #19646
- #19647

**Comment by kenorb** [comment]
Solved: #19718

**Comment by hamzabouajaj** [comment]
Hi Admin,
I'm getting this issue. Please help me
Error 4207
