### ISSUE TITLE
Error Code 218

### ISSUE THREAD

**Issue by deadrong** [keybase/client#19883]
Keybase GUI Version: 4.5.0-20190919040131+93e889ab01

I keep receiving an error code: 218 every time I update files on keybase. The error displays the following message:

Error: ERROR CODE 218 - Keybase services aren't running - KBFS client not found. in method keybase.1.SimpleFS.simpleFSSyncStatus at new s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:570509) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:571105 at c (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:571144) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1262481 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:3053670 at e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2616431) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2616571 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2616211) at e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2616541) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2615742)

**Comment by noah-witt** [comment]
I have the same issue 
`Error: ERROR CODE 218 - method 'GetPreferredMountDirs' not found in protocol 'keybase.1.kbfsMount' in method keybase.1.kbfsMount.GetPreferredMountDirs at new s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:570509) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:571105 at c (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:571144) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:1262481 at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:3053670 at e._call (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2616431) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2616571 at s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2616211) at e._fulfill (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2616541) at s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2615742)`

For me KBFS does not work and no profile pictures appear. 

Here is Info on my setup

> keybase version 4.3.1

>  OS: openSUSE 20191002
>  Kernel: x86_64 Linux 5.3.1-1-default
>  Uptime: 7m
>  Packages: 2449
>  Shell: bash 5.0.11
>  Resolution: 1920x1080
>  DE: KDE 5.62.0 / Plasma 5.16.5
>  WM: KWin
>  GTK Theme: Breeze [GTK3]
>  CPU: Intel Core i7-8750H @ 12x 4.1GHz
>  GPU: GeForce GTX 1050 Ti with Max-Q Design
>  RAM: 3019MiB / 15626MiB

**Comment by deadrong** [comment]
I don't know if it will actually help you. I ended up nuking the database and uninstalling. It has appeared to workout after the reinstall. But still waiting to hear an official type solution from keybase.

**Comment by noah-witt** [comment]
I did the same...
