### ISSUE TITLE
Error 4206

### ISSUE THREAD

**Issue by drewlawson1** [keybase/client#20219]
When trying to join the Stellar airdrop, I am getting the following error message:

> Error: ERROR CODE 4206 - Sorry, you do not qualify. in method stellar.1.local.airdropRegisterLocal at new s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:570509) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:571105 at c (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:571144) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1262481 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:3053670 at e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2616431) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2616571 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2616211) at e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2616541) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2615742)

Anyone else seeing this?

**Comment by joseleoncio** [comment]
`Error: ERROR CODE 4206 - Sorry, you do not qualify. in method stellar.1.local.airdropRegisterLocal at new s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:570509) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:571105 at c (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:571144) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:1262481 at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:3053670 at e._call (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2616431) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2616571 at s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2616211) at e._fulfill (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2616541) at s (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2615742)`

I'm using Linux!

**Comment by anggabae** [comment]
Same like me, i dont know why?

Anyone have a solution please help us

**Comment by catubayjhon** [comment]
yeah me too i dont get why we all fall on this error at the first time i register before september 9 its all well but after keybase that they attack by the scammers it will turn like this now.

**Comment by xrillex** [comment]
same

**Comment by DeadStarr** [comment]
same here :(

**Comment by toogee** [comment]
Same here

**Comment by AkiraYuuji** [comment]
Same heree 😭

**Comment by wilbit** [comment]
I see the same ERROR CODE 4206 on Windows and Android apps

**Comment by joseleoncio** [comment]
Maybe some people are blacklisted.

**Comment by LaBugne** [comment]
i have the same problem but i clicked on "leave airdrop" and i can't change it....

**Comment by Jaoss82** [comment]
Same here as well :-(

**Comment by Nphox** [comment]
I get a similar error too

Error: ERROR CODE 4207 - Sorry, you do not qualify. in method stellar.1.local.airdropRegisterLocal

**Comment by droslean** [comment]
Are there any updates?
