### ISSUE TITLE
Airdrop: Error: ERROR CODE 4206

### ISSUE THREAD

**Issue by 2ge** [keybase/client#20226]
Hi,

got last Keybase: Version 4.5.0-20190919040131+93e889ab01 

after clicking on "Become lucky airdropee"
![image](https://user-images.githubusercontent.com/1067032/66452821-3363a480-ea8c-11e9-87ee-1f07e638aebb.png)

I see this message:

```
Error: ERROR CODE 4206 - Sorry, you do not qualify. in method stellar.1.local.airdropRegisterLocal at new s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:570509) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:571105 at c (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:571144) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1262481 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:3053670 at e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2616431) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2616571 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2616211) at e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2616541) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2615742)
```

OS: OSX

**Comment by m-faccin** [comment]
Same problem for me as well

**Comment by kapishona** [comment]
Hi ,same problem for me

**Comment by Luna1200** [comment]
Hi same problem : /
Help!

**Comment by Luna1200** [comment]
Hi, same problem here, I would like to fix it as soon as possible :/

**Comment by wilbit** [comment]
This is a copy of issue #20219
