### ISSUE TITLE
AirDrop Joinning Bug

### ISSUE THREAD

**Issue by tonicol13** [keybase/client#20241]
While trying to join AirDrop, after the check for qualification, all 3 categories are checked, and the "You are qualified to join" message is shown.  

However, at the top of the window I get this message: 

Error: ERROR CODE 4206 - Sorry, you do not qualify. in method stellar.1.local.airdropRegisterLocal at new s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:550669) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:551265 at d (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:551304) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1223905 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2974754 at e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2558372) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2558512 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2558152) at e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2558482) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2557683)

I've restarted the application but the error keeps showing. 

my log id: e1e194b592288e9bf71e471c

**Comment by yann-Solol** [comment]
I've get same error...

**Comment by joaosmv** [comment]
Me too

**Comment by rustem42** [comment]
{
  "body": {
    "key": {
      "eldest_kid": "0120a1cdfde870478e12d18619248289e677f54acfdcc40621448c5b4ff08ece2f280a",
      "host": "keybase.io",
      "kid": "0120a1cdfde870478e12d18619248289e677f54acfdcc40621448c5b4ff08ece2f280a",
      "uid": "d72a75ab3ced8444144f949b371e2619",
      "username": "rusya"
    },
    "merkle_root": {
      "ctime": 1570335120,
      "hash": "684ecee05f6f9ff5cf0dad42937e342a2a89a5cf4ec57ae9022eb5e8104f4b943d63708e25bb241a67fd763e2774f3172d5fad53b20687ac19684188b1adad27",
      "hash_meta": "1d99cc1249d38e0521b298b28438bd608afc9237da0219235ebeb0d4773fa5a7",
      "seqno": 7880974
    },
    "service": {
      "entropy": "YfFvKaSBJHEYWEc6YNtJK4o2",
      "name": "github",
      "username": "rustem42"
    },
    "type": "web_service_binding",
    "version": 2
  },
  "client": {
    "name": "keybase.io go client",
    "version": "4.5.0"
  },
  "ctime": 1570320695,
  "expire_in": 504576000,
  "prev": "ad4b787062a6833d4b0c34fce5978cb582cb471ed397e5d369b2c9bd4b683557",
  "seqno": 9,
  "tag": "signature"
}

**Comment by rustem42** [comment]
Rusya

**Comment by encloinc** [comment]
https://github.com/keybase/client/blob/3736a05e06a5486efd74f28ea60651bfff15630d/go/systests/stellar_client_test.go

**Comment by encloinc** [comment]
line 634, i think you guys forgot a "res" because right now it says
`return err`
instead of
`return res, err`
like the other methods

**Comment by wilbit** [comment]
This is a copy of issue #20219
