### ISSUE TITLE
Error: ERROR CODE 218 - Keybase services aren't running - KBFS client not found

### ISSUE THREAD

**Issue by heeboA** [keybase/client#21463]
I'll start off by saying that i tried to search the issues here for a solution, but none of the suggestions for this or similar issues worked. The issue possibly started after an osx update, but i can't be quite sure of that.

Some information:
    OS:        darwin
    OS vers:   10.14.6-18G1012
    Runtime:   go1.13
    Arch:      amd64

`keybase launchd list`:
keybase.service: Running (pid=13625) [Keybase]
keybase.kbfs: Running (pid=14422) [KBFS]
keybase.updater: Running (pid=13616) [Updater]

A snippet from the end of keybase.kbfs.log:

```
panic: Only dirs can have child names

goroutine 942 [running]:
github.com/keybase/client/go/kbfs/libkbfs.(*nodeStandard).ChildName(0xc0033bcaf0, 0xc009a0102f, 0x11, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/build/go/src/github.com/keybase/client/go/kbfs/libkbfs/node.go:158 +0x100
github.com/keybase/client/go/kbfs/libkbfs.(*folderBranchOps).doPartialSync(0xc000186f00, 0x5988c20, 0xc00669c300, 0x0, 0xc009a46600, 0x17, 0x20, 0xc00019f8c0, 0xc003311e60, 0x21, ...)
        /Users/build/go/src/github.com/keybase/client/go/kbfs/libkbfs/folder_branch_ops.go:1214 +0x769
github.com/keybase/client/go/kbfs/libkbfs.(*folderBranchOps).kickOffPartialSync.func1()
        /Users/build/go/src/github.com/keybase/client/go/kbfs/libkbfs/folder_branch_ops.go:1275 +0x1b1
github.com/keybase/client/go/kbfs/libkbfs.(*folderBranchOps).goTracked.func1(0xc000186f00, 0xc0067d8630)
        /Users/build/go/src/github.com/keybase/client/go/kbfs/libkbfs/folder_branch_ops.go:522 +0x5f
created by github.com/keybase/client/go/kbfs/libkbfs.(*folderBranchOps).goTracked
        /Users/build/go/src/github.com/keybase/client/go/kbfs/libkbfs/folder_branch_ops.go:520 +0x69
```

logs id: 409e881e42dfa9a08c4ffb1c

**Comment by heeboA** [comment]
Fixed in a new release.
