### ISSUE TITLE
build error with desktop client on arm64

### ISSUE THREAD

**Issue by fuzzy** [keybase/client#23605]
The build_binaries.sh script tries to fetch electron even if it is found on the system. This breaks builds on aarch64 as those distfiles don't exist. I installed electron both globally and locally, and the build_binaries.sh script appears to find it, it just also appears not to care.

```
...
KB: Babel config detected caller:  @babel/node
KB babel.config.js for Electron
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
Missing 'saltpack.icns' from yarn package arguments. Need an icon to associate ".saltpack" files with Electron on macOS, Windows, and Linux.
Finding electron version
Found electron version: 8.0.2
Starting webpack build
Injecting __VERSION__:  5.4.0-20200409032345+09a8a753da
Flags:  { isDev: false, isHot: false }
Injecting defines:  { __DEV__: false,
  __HOT__: false,
  __STORYBOOK__: false,
  __STORYSHOT__: false,
  __VERSION__: '"5.4.0-20200409032345+09a8a753da"' }
Packaging to /home/fuzzy/.local/golang/path/src/github.com/keybase/client/shared/desktop/release/linux-arm64
{ HTTPError: Response code 404 (Not Found)
    at EventEmitter.emitter.on.response (/home/fuzzy/.local/golang/path/src/github.com/keybase/client/shared/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:189:13)
    at module.exports (/home/fuzzy/.local/golang/path/src/github.com/keybase/client/shared/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/home/fuzzy/.local/golang/path/src/github.com/keybase/client/shared/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:277:13)
    at ClientRequest.emit (events.js:194:15)
    at ClientRequest.origin.emit.args [as emit] (/home/fuzzy/.local/golang/path/src/github.com/keybase/client/shared/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at TLSSocket.Readable.push (_stream_readable.js:220:10)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:94:17)
  name: 'HTTPError',
  host: 'kbelectron.keybase.pub',
  hostname: 'kbelectron.keybase.pub',
  method: 'GET',
  path: '/electron-download/v8.0.2/electron-v8.0.2-linux-arm64.zip',
  socketPath: undefined,
  protocol: 'https:',
  url:
   'https://kbelectron.keybase.pub/electron-download/v8.0.2/electron-v8.0.2-linux-arm64.zip',
  gotOptions:
   { path: '/electron-download/v8.0.2/electron-v8.0.2-linux-arm64.zip',
     protocol: 'https:',
     slashes: true,
     auth: null,
     host: 'kbelectron.keybase.pub',
     port: null,
     hostname: 'kbelectron.keybase.pub',
     hash: null,
     search: null,
     query: null,
     pathname: '/electron-download/v8.0.2/electron-v8.0.2-linux-arm64.zip',
     href:
      'https://kbelectron.keybase.pub/electron-download/v8.0.2/electron-v8.0.2-linux-arm64.zip',
     retry:
      { retries: [Function],
        methods: [Set],
        statusCodes: [Set],
        errorCodes: [Set] },
     headers:
      { 'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
        'accept-encoding': 'gzip, deflate' },
     hooks:
      { beforeRequest: [],
        beforeRedirect: [],
        beforeRetry: [],
        afterResponse: [],
        beforeError: [],
        init: [] },
     decompress: true,
     throwHttpErrors: true,
     followRedirect: true,
     stream: true,
     form: false,
     json: false,
     cache: false,
     useElectronNet: false,
     method: 'GET' },
  statusCode: 404,
  statusMessage: 'Not Found',
  headers:
   { date: 'Thu, 09 Apr 2020 03:33:13 GMT',
     'content-type': 'text/plain; charset=utf-8',
     'content-length': '9',
     connection: 'close',
     server: 'nginx/1.14.0 (Ubuntu)',
     'content-security-policy': 'frame-ancestors https://keybase.pub',
     'x-frame-options': 'ALLOW-FROM https://keybase.pub',
     'x-xss-protection': '1; mode=block',
     'x-content-type-options': 'nosniff',
     'x-robots-tag': 'noarchive, nofollow',
     etag: 'W/"9-0gXL1ngzMqISxa6S1zx3F4wtLyg"' },
  body: undefined }
...
```

**Comment by fuzzy** [comment]
For reference:

```

$ electron -v
v8.2.1
$ npm -v
5.8.0
$ node -v
v10.15.2
$ yarn -v
1.22.4
```

**Comment by heronhaye** [comment]
In `shared/desktop/package.desktop.tsx`, can you try removing the `download` key pointing at kbelectron.keybase.pub? Does it work after that?

The script doesn't support this use case right now but it can be modified.

**Comment by ThatGeoGuy** [comment]
I can confirm that removing the `download` key from `shared/desktop/package.desktop.tsx` allowed me to build the client, kbfs, gui, and everything on arm64 (done on a pinebook pro!). 

That said, I also encountered a few other bumps along the way. I've attached a diff below that should help with building a debian package from the final build artefacts:

```
diff --git a/packaging/linux/deb/control.template b/packaging/linux/deb/control.template
index 7e25f2da0a..f8e042ec0d 100644
--- a/packaging/linux/deb/control.template
+++ b/packaging/linux/deb/control.template
@@ -5,5 +5,4 @@ Installed-Size: @@SIZE@@
 Maintainer: Keybase Bugs <bugs@keybase.io>
 Section: misc
 Priority: optional
-@@DEPENDENCIES@@
 Description: The Keybase Go client, filesystem, and GUI
diff --git a/packaging/linux/deb/package_binaries.sh b/packaging/linux/deb/package_binaries.sh
index 1cd6b0f785..726b922685 100755
--- a/packaging/linux/deb/package_binaries.sh
+++ b/packaging/linux/deb/package_binaries.sh
@@ -95,8 +95,11 @@ build_one_architecture() {
   fakeroot dpkg-deb --build "$dest/build" "$dest/$name-$version-$debian_arch.deb"
 }
 
-export debian_arch=amd64
+export debian_arch=arm64
 build_one_architecture
 
-export debian_arch=i386
-build_one_architecture
+# export debian_arch=amd64
+# build_one_architecture
+#
+# export debian_arch=i386
+# build_one_architecture
diff --git a/shared/desktop/package.desktop.tsx b/shared/desktop/package.desktop.tsx
index b10bb10295..47c239be6f 100644
--- a/shared/desktop/package.desktop.tsx
+++ b/shared/desktop/package.desktop.tsx
@@ -52,11 +52,6 @@ const packagerOpts: any = {
   buildVersion: String(appVersion) + String(comment),
   darwinDarkModeSupport: true,
   dir: desktopPath('./build'),
-  download: {
-    mirrorOptions: {
-      mirror: 'https://kbelectron.keybase.pub/electron-download/',
-    },
-  },
   electronVersion: 0,
   // macOS file association to saltpack files
   extendInfo: {
```

From this I ran the following command from the keybase-client directory:

`KEYBASE_BUILD_ARM_ONLY=1 ./packaging/linux/build_binaires.sh prerelease ~/tmp/keybase-build`

and then to package a deb file:

`./packaging/linux/package_binaries.sh ~/tmp/keybase-build`

And then installed the deb in `~/tmp/keybase-build/deb/arm64/`

Thanks for the tip @heronhaye, this actually helped a lot! I think there's a couple different things going on in my patch above, but if there's interest I could clean it up and submit a proper PR.

**Comment by heronhaye** [comment]
Sure, go ahead. Can you reuse the ARM_ONLY var for  package_binaries and then add a KEYBASE_USE_LOCAL_ELECTRON?

Tag me on the PR

**Comment by ThatGeoGuy** [comment]
@heronhaye I'm almost wrapped up with a PR, I have one last thing to add to `package.desktop.tsx` (KEYBASE_USE_LOCAL_ELECTRON). 

Unfortunately I'm a C++ developer by trade and don't know how much about Typescript. I'm trying to add:

```
downloadOptions: any = {
    mirrorOptions: {
      mirror: 'https://kbelectron.keybase.pub/electron-download/',
    },
}

if (package.env['KEYBASE_USE_LOCAL_ELECTRON'] == 1) {
    downloadOptions = {}
}
```

This seems incorrect as I am getting build errors with this, although I suspect this would work in regular Javascript. Any tips for what I should do to change this? `downloadOptions` is an object that I am planning to conditionally insert into the `packagerOpts`, to dispatch on local / non-local electron.

**Comment by heronhaye** [comment]
It's hard to say without the exact error. You may need to define the type of `downloadOptions` as `{ mirrorOptions?: any }`, e.g., indicating its an optional key.

**Comment by kaycoinsUSA** [comment]
Great job team!
