### ISSUE TITLE
Can't rename or delete folder on public folder

### ISSUE THREAD

**Issue by tubedude** [keybase/client#24236]
I'm MacOs 10.15.5 (19F101)
And Keybase app: Version 5.5.0-20200526170801+139bb348af (5.5.0-20200526170801+139bb348af)

I've just created a folder on my `public` folder. But now I cannot delete it or rename it.

After some time hung, the GUI will display this error message:

```
Error: ERROR CODE 218 - context deadline exceeded in method keybase.1.SimpleFS.simpleFSStat at new RPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1063260) at convertToRPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1064147) at convertToError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1064206) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2539243 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:204647 at Deferrals._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:11095) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:11287 at trampoline (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:10823) at Deferrals._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:11240) at ret (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:10236)
```

And it looks that I'm also unable to send you feedback through the app. The GUI also locks and display this error:

```
API_NETWORK_ERROR: ERROR CODE 1601 - API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers) in method keybase.1.config.logSend
Error: ERROR CODE 1601 - API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers) in method keybase.1.config.logSend at new RPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1063260) at convertToRPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1064147) at convertToError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1064206) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2539243 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:204647 at Deferrals._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:11095) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:11287 at trampoline (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:10823) at Deferrals._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:11240) at ret (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:10236)
{ "code": 1601, "fields": null, "desc": "API network error: Post https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json: net/http: request canceled (Client.Timeout exceeded while awaiting headers)", "details": "Error code 1601: API_NETWORK_ERROR in method keybase.1.config.logSend" }
```

**Comment by tubedude** [comment]
I removed the Finder integration, and added again and it seems to be working fine.
