### ISSUE TITLE
Failing to audit a team

### ISSUE THREAD

**Issue by Avamander** [keybase/client#24273]
For some reason my client constantly throws up this error in the logs:

```
Action,2020-07-20T23:30:25.452Z,type: config:globalError:  {"payload":{"err":"Global Error: Keybase had a problem loading a team, please report this with `keybase log send`: failed to successfully reaudit team 67c99659bdc24920b56ccec3a42dd424 in box audit jail after 3 retries: There were multiple errors: audit failed fatally; will not be retried until requested: failed to load team: net/http: request canceled (Client.Timeout exceeded while reading body); audit failed fatally; will not be retried until requested: failed to load team: API network error: context canceled; audit failed fatally; will not be retried until requested: failed to load team: API network error: context canceled; audit failed fatally; will not be retried until requested: failed to load team: API network error: context canceled Error: Keybase had a problem loading a team, please report this with `keybase log send`: failed to successfully reaudit team 67c99659bdc24920b56ccec3a42dd424 in box audit jail after 3 retries: There were multiple errors: audit failed fatally; will not be retried until requested: failed to load team: net/http: request canceled (Client.Timeout exceeded while reading body); audit failed fatally; will not be retried until requested: failed to load team: API network error: context canceled; audit failed fatally; will not be retried until requested: failed to load team: API network error: context canceled; audit failed fatally; will not be retried until requested: failed to load team: API network error: context canceled\n    at receivedBoxAuditError (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:4205432)\n    at runCallEffect (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:540966)\n    at runEffect (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:549100)\n    at digestEffect (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:550880)\n    at next (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:550048)\n    at proc (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:549517)\n    at file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:542359\n    at immediately (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:534875)\n    at runForkEffect (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:542325)\n    at runEffect (file:///opt/keybase/resources/app/desktop/dist/vendors~main.bundle.js:2:549100)"},"type":"config:globalError"}
```

(Also `keybase log send` still doesn't work because it times out too soon on slow upload speeds)

**Comment by heronhaye** [comment]
Do these errors manifest in the app with "black bars"? Is your internet very slow or unreliable?

**Comment by Avamander** [comment]
In the app they appear as those white warning bars. 

My internet is very reliable and is not very slow, but it is an asymmetrical connection with 5Mbps upload.

**Comment by Avamander** [comment]
@heronhaye 

The errors manifest in the app as those white bars.

My internet is reliable but it is asymmetrical with 5Mbps upload. It works fine for pretty much everything else.

**Comment by heronhaye** [comment]
I see. Could you try sending a log a few more times? If that still doesn't work, could you message keybase.io/modalduality? Thanks.

**Comment by Avamander** [comment]
I have tried that numerous times, log sending just doesn't work. I will send the message.

**Comment by Avamander** [comment]
@heronhaye I changed the timeout to 4 minutes (as requested) and that fixed the issue.
