### ISSUE TITLE
Cannot write to sub team after its renaming

### ISSUE THREAD

**Issue by sapran** [keybase/client#24596]
There is an issue after renaming a subteam. All members can use it, but one cannot. He can read the messages and react to them, but cannot write. Removing/adding did not help, as well as promoting to admin.

Is that a known issue?

**Comment by im4tb** [comment]
`Error: ERROR CODE 218 - error loading parent: adding new subteam: cannot add to subteam log out of order: 63 < 94 in method keybase.1.SimpleFS.simpleFSSubscribePath at new RPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1064492) at convertToRPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1065369) at convertToError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1065428) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2540801 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:199147 at Deferrals._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:11095) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:11287 at trampoline (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:10823) at Deferrals._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:11240) at ret (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:10236)`

**Comment by waynew** [comment]
I'm having the exact same issue - 
```
▶ ERROR error loading parent: adding new subteam: cannot add to subteam log out of order: 54 < 76
```

**Comment by waynew** [comment]
I'm not sure if this is a server-side issue or the client is broken and won't update to the latest log

**Comment by waynew** [comment]
Update! I blew away the local db on my phone and now I can send messages. Not sure if I'll have to do the same on other devices...

**Comment by waynew** [comment]
Update: Yes - looks like doing a db nuke on every device is required. I'm not sure how to do it from the command line, but currently in the UI it's under settings > advanced

**Comment by waynew** [comment]
Update: Yes - looks like doing a db nuke on every device is required. I'm not sure how to do it from the command line, but currently in the UI it's under settings > advanced
