### ISSUE TITLE
ERROR CODE 2806 - MDServer Unauthorized

### ISSUE THREAD

**Issue by 1smii** [keybase/client#24767]
Hello team,

A few months ago, the users aren't able to access their own folders in the different teams.
It was due to a bug/error and the resolution was restarting some slow servers.

In another hand the error we're getting is:
`Error: ERROR CODE 2806 - MDServer Unauthorized in method keybase.1.SimpleFS.simpleFSSubscribePath at new RPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1064492) at convertToRPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1065369) at convertToError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:1065428) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2540801 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:199147 at Deferrals._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:11095) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:11287 at trampoline (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:10823) at Deferrals._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:11240) at ret (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/vendors~main.bundle.js:2:10236)g`

It was the last ticket:
https://github.com/keybase/client/issues/24602

We are using day-to-day Keybase and this error blocks our work!

Please help in order to solve this issue!

FYI: @strib 
Kindly Regards,
Ismael

**Comment by samsonquantifi** [comment]
Hello,

I'm running into this same issue with team team repos. 


log ID 92541542465f1c03dc813a1c

```
Error: ERROR CODE 2806 - MDServer Unauthorized in method keybase.1.SimpleFS.simpleFSSubscribePath at new RPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:3860882) at convertToRPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:3861769) at convertToError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:3861828) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2347958 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/822.bundle.js:2:324318 at Deferrals._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/822.bundle.js:2:417479) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/822.bundle.js:2:417671 at trampoline (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/822.bundle.js:2:417207) at Deferrals._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/822.bundle.js:2:417624) at ret (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/822.bundle.js:2:416617)
```

using `git`

```
git clone keybase://team/REDACTED_TEAM/REDACTED_REPO_NAME
Cloning into 'REDACTED'...
Initializing Keybase... done.
Syncing with Keybase... MDServer Unauthorized
git-remote-keybase error: (1) MDServer Unauthorized
```

**Comment by AhmadAliyev** [comment]
I am also having exact same error

**Comment by wiltonmaddams** [comment]
Same here... My admin added me to our team account, I then went to clone our repo, and kept receiving this error.

**Comment by bruceoutdoors** [comment]
I have the same issue too!

**Comment by paweldaborowski** [comment]
same here. issue occurs despite user being part of the group.

**Comment by BrettHoyer** [comment]
Same here. I was added as a new member to a team and repeatedly hit `MDServer Unauthorized`.

**Comment by BrettHoyer** [comment]
@strib Is there any chance you need to refresh a server as in https://github.com/keybase/client/issues/24602#issuecomment-918478113?

**Comment by kangxie-colorado** [comment]
Same here.

**Comment by Sharply4786** [comment]
I am seeing this error for a new user added to my team. Please advise @strib  🙏

**Comment by dnmvisser** [comment]
Same here... I hope this does not spell the end of Keybase...
