### ISSUE TITLE
trying to build for arm64

### ISSUE THREAD

**Issue by thepixelmonk** [keybase/client#25126]
```
Building Electron client for arm64...
+ cd /home/thepixelmonk/git/client/shared
+ yarn run package -- --platform linux --arch arm64 --appVersion 6.1.0-20220724022337+6e84112 --network-concurrency 8
yarn run v1.22.19
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ yarn run _helper package --platform linux --arch arm64 --appVersion 6.1.0-20220724022337+6e84112 --network-concurrency 8
$ yarn run _node desktop/yarn-helper package --platform linux --arch arm64 --appVersion 6.1.0-20220724022337+6e84112 --network-concurrency 8
$ cross-env-shell babel-node --extensions='.tsx' --extensions='.js'  desktop/yarn-helper package --platform linux --arch arm64 --appVersion 6.1.0-20220724022337+6e84112 --network-concurrency 8
$ cross-env-shell babel-node --extensions='.tsx' --extensions='.js'  desktop/package.desktop.tsx --platform linux --arch arm64 --appVersion 6.1.0-20220724022337+6e84112 --network-concurrency 8
Missing 'saltpack.icns' from yarn package arguments. Need an icon to associate ".saltpack" files with Electron on macOS, Windows, and Linux.
Finding electron version
Found electron version: 19.0.4
Starting webpack build
Injecting __VERSION__:  6.1.0-20220724022337+6e84112
Flags:  { isDev: false, isHot: false }
Injecting defines:  {
  __DEV__: false,
  __HOT__: false,
  __STORYBOOK__: false,
  __STORYSHOT__: false,
  __VERSION__: '"6.1.0-20220724022337+6e84112"'
}
Killed
error Command failed with exit code 137.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
node:child_process:894
    throw err;
    ^

Error: Command failed: yarn _node  desktop/package.desktop.tsx --platform linux --arch arm64 --appVersion 6.1.0-20220724022337+6e84112 --network-concurrency 8
    at checkExecSyncError (node:child_process:820:11)
    at execSync (node:child_process:891:15)
    at exec (/home/thepixelmonk/git/client/shared/desktop/yarn-helper/index.tsx:81:5)
    at main (/home/thepixelmonk/git/client/shared/desktop/yarn-helper/index.tsx:148:5)
    at Object.<anonymous> (/home/thepixelmonk/git/client/shared/desktop/yarn-helper/index.tsx:156:1)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._compile (/home/thepixelmonk/git/client/shared/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Object.newLoader [as .tsx] (/home/thepixelmonk/git/client/shared/node_modules/pirates/lib/index.js:141:7) {
  status: 137,
  signal: null,
  output: [ null, null, null ],
  pid: 16286,
  stdout: null,
  stderr: null
}

Node.js v18.6.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any ideas on what the issue might be?

**Comment by thepixelmonk** [comment]
from what i can tell this is actually just the laptop running out of memory >_<
