### ISSUE TITLE
"There was an error trying to run the install (2). Please run 'keybase log send' to report the error."

### ISSUE THREAD

**Issue by elisboa** [keybase/client#25565]
Keybase GUI Version: 6.0.4-20230113195947+6e1343b357

Here's the command output when I ran ./Keybase from a terminal:

```
❯ echo $HOME
/Users/ecl                                                                                                                                               /0,0s
❯ ./Keybase
Version: 6.0.4-20230113195947+6e1343b357
Executing: '/Applications/Keybase.app/Contents/SharedSupport/bin/keybase' --debug install-auto --format=json --timeout=30s
Exec (stderr): 2023-03-19T08:50:23.111055-03:00 ▶ [DEBU keybase json.go:71] 001 + loading "config" file: /Users/ecl/Library/Application Support/Keybase/config.json
2023-03-19T08:50:23.111639-03:00 ▶ [DEBU keybase json.go:64] 002 No "config" file found; tried /Users/ecl/Library/Application Support/Keybase/config.json
2023-03-19T08:50:23.111864-03:00 ▶ [DEBU keybase json.go:71] 003 + loading "gui config" file: /Users/ecl/Library/Application Support/Keybase/gui_config.json
2023-03-19T08:50:23.111907-03:00 ▶ [DEBU keybase json.go:106] 004 - successfully loaded gui config file
2023-03-19T08:50:23.112033-03:00 ▶ [DEBU keybase json.go:71] 005 + loading "updater config" file: /Users/ecl/Library/Application Support/Keybase/updater.json
2023-03-19T08:50:23.112048-03:00 ▶ [DEBU keybase json.go:64] 006 No "updater config" file found; tried /Users/ecl/Library/Application Support/Keybase/updater.json
2023-03-19T08:50:23.112170-03:00 ▶ [DEBU keybase socket_nix.go:149] 007 Connecting to socket with dialFiles=[/Users/ecl/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock /Users/ecl/Library/Caches/Keybase/keybased.sock], bindFiles=/Users/ecl/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
2023-03-19T08:50:23.112431-03:00 ▶ [DEBU keybase globals.go:606] 008 Created Identify2Cache, max age: 5m0s
2023-03-19T08:50:23.112998-03:00 ▶ [DEBU keybase globals.go:609] 009 Created LinkCache, max size: 4000, clean dur: 1m0s
2023-03-19T08:50:23.113095-03:00 ▶ [DEBU keybase globals.go:611] 00a Created CardCache, max age: 5m0s
2023-03-19T08:50:23.113101-03:00 ▶ [DEBU keybase globals.go:629] 00b made a new full self cache
2023-03-19T08:50:23.113209-03:00 ▶ [DEBU keybase globals.go:631] 00c made a new cached UPAK loader (timeout=10m0s)
2023-03-19T08:50:23.113938-03:00 ▶ [DEBU keybase network_instrumenter.go:96] 00d + DiskInstrumentationStorage: Start
2023-03-19T08:50:23.114187-03:00 ▶ [DEBU keybase globals.go:991] 00e - DiskInstrumentationStorage: Start -> ok [time=1.959µs]
2023-03-19T08:50:23.114277-03:00 ▶ [DEBU keybase network_instrumenter.go:96] 00f + DiskInstrumentationStorage: Start
2023-03-19T08:50:23.114285-03:00 ▶ [DEBU keybase globals.go:992] 010 - DiskInstrumentationStorage: Start -> ok [time=2.083µs]
2023-03-19T08:50:23.115769-03:00 ▶ [DEBU keybase ui.go:622] 011 Can't set GPG_TTY; discover failed
2023-03-19T08:50:23.116237-03:00 ▶ [DEBU keybase globals.go:540] 012 Keybase CLI 6.0.4-20230113195947+6e1343b357
2023-03-19T08:50:23.116332-03:00 ▶ [DEBU keybase globals.go:540] 013 - Built with go1.19.4
2023-03-19T08:50:23.116336-03:00 ▶ [DEBU keybase globals.go:540] 014 - Visit https://keybase.io for more details
2023-03-19T08:50:23.116457-03:00 ▶ [DEBU keybase main.go:272] 015 + configureProcesses
2023-03-19T08:50:23.116466-03:00 ▶ [DEBU keybase main.go:386] 016 + configureLogging
2023-03-19T08:50:23.116470-03:00 ▶ [DEBU keybase main.go:395] 017 Disabling log forwarding
2023-03-19T08:50:23.116474-03:00 ▶ [DEBU keybase main.go:388] 018 - configureLogging
2023-03-19T08:50:23.116480-03:00 ▶ [DEBU keybase main.go:274] 019 - configureProcesses -> <nil>
2023-03-19T08:50:23.116513-03:00 ▶ [DEBU keybase install_darwin.go:492] 01a Installing components: [cli updater service kbfs kbnm]
2023-03-19T08:50:23.116859-03:00 ▶ [INFO keybase install_darwin.go:673] 01b Checking /usr/local/bin/keybase (/Applications/Keybase.app/Contents/SharedSupport/bin/keybase)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x104035414]

goroutine 1 [running]:
github.com/keybase/client/go/install.installCommandLineForBinPath({0x14000694a00, 0x3c}, {0x1400013c8d0, 0x16}, 0x1, {0x12def6358, 0x14000161e40})
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:711 +0x74
github.com/keybase/client/go/install.installCommandLine({0x1043ab05b?, 0x3?}, {0x0?, 0x5?}, 0x1?, {0x12def6358, 0x14000161e40})
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:674 +0x154
github.com/keybase/client/go/install.Install({0x104ff7870, 0x140002ef080}, {0x0, 0x0}, {0x0, 0x0}, {0x140001168c0, 0x5, 0x5}, 0x2?, ...)
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:495 +0x144
github.com/keybase/client/go/install.InstallAuto({0x104ff7870, 0x140002ef080}, {0x0, 0x0}, {0x0, 0x0}, 0x1043c6a08?, {0x12def6358, 0x14000161e40})
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:442 +0x1f8
github.com/keybase/client/go/client.(*cmdInstallAuto).Run(0x140007feec0)
	/Users/build/go/src/github.com/keybase/client/go/client/cmd_install_osx.go:361 +0x98
main.mainInner(0x140002ef080, {0x0, 0x0, 0x0})
	/Users/build/go/src/github.com/keybase/client/go/keybase/main.go:248 +0x678
main.main()
	/Users/build/go/src/github.com/keybase/client/go/keybase/main.go:71 +0x88

Exec (err): Error: Command failed: '/Applications/Keybase.app/Contents/SharedSupport/bin/keybase' --debug install-auto --format=json --timeout=30s
2023-03-19T08:50:23.111055-03:00 ▶ [DEBU keybase json.go:71] 001 + loading "config" file: /Users/ecl/Library/Application Support/Keybase/config.json
2023-03-19T08:50:23.111639-03:00 ▶ [DEBU keybase json.go:64] 002 No "config" file found; tried /Users/ecl/Library/Application Support/Keybase/config.json
2023-03-19T08:50:23.111864-03:00 ▶ [DEBU keybase json.go:71] 003 + loading "gui config" file: /Users/ecl/Library/Application Support/Keybase/gui_config.json
2023-03-19T08:50:23.111907-03:00 ▶ [DEBU keybase json.go:106] 004 - successfully loaded gui config file
2023-03-19T08:50:23.112033-03:00 ▶ [DEBU keybase json.go:71] 005 + loading "updater config" file: /Users/ecl/Library/Application Support/Keybase/updater.json
2023-03-19T08:50:23.112048-03:00 ▶ [DEBU keybase json.go:64] 006 No "updater config" file found; tried /Users/ecl/Library/Application Support/Keybase/updater.json
2023-03-19T08:50:23.112170-03:00 ▶ [DEBU keybase socket_nix.go:149] 007 Connecting to socket with dialFiles=[/Users/ecl/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock /Users/ecl/Library/Caches/Keybase/keybased.sock], bindFiles=/Users/ecl/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
2023-03-19T08:50:23.112431-03:00 ▶ [DEBU keybase globals.go:606] 008 Created Identify2Cache, max age: 5m0s
2023-03-19T08:50:23.112998-03:00 ▶ [DEBU keybase globals.go:609] 009 Created LinkCache, max size: 4000, clean dur: 1m0s
2023-03-19T08:50:23.113095-03:00 ▶ [DEBU keybase globals.go:611] 00a Created CardCache, max age: 5m0s
2023-03-19T08:50:23.113101-03:00 ▶ [DEBU keybase globals.go:629] 00b made a new full self cache
2023-03-19T08:50:23.113209-03:00 ▶ [DEBU keybase globals.go:631] 00c made a new cached UPAK loader (timeout=10m0s)
2023-03-19T08:50:23.113938-03:00 ▶ [DEBU keybase network_instrumenter.go:96] 00d + DiskInstrumentationStorage: Start
2023-03-19T08:50:23.114187-03:00 ▶ [DEBU keybase globals.go:991] 00e - DiskInstrumentationStorage: Start -> ok [time=1.959µs]
2023-03-19T08:50:23.114277-03:00 ▶ [DEBU keybase network_instrumenter.go:96] 00f + DiskInstrumentationStorage: Start
2023-03-19T08:50:23.114285-03:00 ▶ [DEBU keybase globals.go:992] 010 - DiskInstrumentationStorage: Start -> ok [time=2.083µs]
2023-03-19T08:50:23.115769-03:00 ▶ [DEBU keybase ui.go:622] 011 Can't set GPG_TTY; discover failed
2023-03-19T08:50:23.116237-03:00 ▶ [DEBU keybase globals.go:540] 012 Keybase CLI 6.0.4-20230113195947+6e1343b357
2023-03-19T08:50:23.116332-03:00 ▶ [DEBU keybase globals.go:540] 013 - Built with go1.19.4
2023-03-19T08:50:23.116336-03:00 ▶ [DEBU keybase globals.go:540] 014 - Visit https://keybase.io for more details
2023-03-19T08:50:23.116457-03:00 ▶ [DEBU keybase main.go:272] 015 + configureProcesses
2023-03-19T08:50:23.116466-03:00 ▶ [DEBU keybase main.go:386] 016 + configureLogging
2023-03-19T08:50:23.116470-03:00 ▶ [DEBU keybase main.go:395] 017 Disabling log forwarding
2023-03-19T08:50:23.116474-03:00 ▶ [DEBU keybase main.go:388] 018 - configureLogging
2023-03-19T08:50:23.116480-03:00 ▶ [DEBU keybase main.go:274] 019 - configureProcesses -> <nil>
2023-03-19T08:50:23.116513-03:00 ▶ [DEBU keybase install_darwin.go:492] 01a Installing components: [cli updater service kbfs kbnm]
2023-03-19T08:50:23.116859-03:00 ▶ [INFO keybase install_darwin.go:673] 01b Checking /usr/local/bin/keybase (/Applications/Keybase.app/Contents/SharedSupport/bin/keybase)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x104035414]

goroutine 1 [running]:
github.com/keybase/client/go/install.installCommandLineForBinPath({0x14000694a00, 0x3c}, {0x1400013c8d0, 0x16}, 0x1, {0x12def6358, 0x14000161e40})
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:711 +0x74
github.com/keybase/client/go/install.installCommandLine({0x1043ab05b?, 0x3?}, {0x0?, 0x5?}, 0x1?, {0x12def6358, 0x14000161e40})
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:674 +0x154
github.com/keybase/client/go/install.Install({0x104ff7870, 0x140002ef080}, {0x0, 0x0}, {0x0, 0x0}, {0x140001168c0, 0x5, 0x5}, 0x2?, ...)
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:495 +0x144
github.com/keybase/client/go/install.InstallAuto({0x104ff7870, 0x140002ef080}, {0x0, 0x0}, {0x0, 0x0}, 0x1043c6a08?, {0x12def6358, 0x14000161e40})
	/Users/build/go/src/github.com/keybase/client/go/install/install_darwin.go:442 +0x1f8
github.com/keybase/client/go/client.(*cmdInstallAuto).Run(0x140007feec0)
	/Users/build/go/src/github.com/keybase/client/go/client/cmd_install_osx.go:361 +0x98
main.mainInner(0x140002ef080, {0x0, 0x0, 0x0})
	/Users/build/go/src/github.com/keybase/client/go/keybase/main.go:248 +0x678
main.main()
	/Users/build/go/src/github.com/keybase/client/go/keybase/main.go:71 +0x88

    at ChildProcess.exithandler (node:child_process:406:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12) {
  killed: false,
  code: 2,
  signal: null,
  cmd: "'/Applications/Keybase.app/Contents/SharedSupport/bin/keybase' --debug install-auto --format=json --timeout=30s"
}
Quit the app
Executing: '/Applications/Keybase.app/Contents/SharedSupport/bin/keybase' ctl stop --exclude=app
Exec (stderr): 2023-03-19T08:52:21.128811-03:00 ▶ [INFO keybase launchd.go:154] 001 Nothing to stop (keybase.service)
2023-03-19T08:52:21.132859-03:00 ▶ [INFO keybase launchd.go:154] 002 Nothing to stop (homebrew.mxcl.keybase)
2023-03-19T08:52:21.132943-03:00 ▶ [INFO keybase install_darwin.go:961] 003 UninstallKBFSOnStop: uninstalling from mountdir: /Volumes/Keybase (ecl)
2023-03-19T08:52:21.134696-03:00 ▶ [INFO keybase launchd.go:154] 004 Nothing to stop (keybase.kbfs)
2023-03-19T08:52:21.136398-03:00 ▶ [INFO keybase launchd.go:154] 005 Nothing to stop (homebrew.mxcl.kbfs)
2023-03-19T08:52:21.136427-03:00 ▶ [INFO keybase install_darwin.go:967] 006 Uninstalled mount: /Volumes/Keybase (ecl)
2023-03-19T08:52:21.262969-03:00 ▶ [INFO keybase launchd.go:154] 007 Nothing to stop (keybase.updater)
2023-03-19T08:52:21.263962-03:00 ▶ [INFO keybase cmd_ctl_stop_osx.go:99] 008 ctlStop: expected error when trying to shutdown service post-uninstall: There were multiple errors: dial unix /Users/ecl/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/ecl/Library/Caches/Keybase/keybased.sock: connect: no such file or directory

Done with ctlstop
exiting app
```

The computer is a Mac Mini M1 with 8 GB of RAM and 512 of disk. Operating System version is Ventura 13.2.1

**Comment by elisboa** [comment]
I was able to install the version from the App Store. But none of the downloaded versions (ARM and Intel) worker.
