### ISSUE TITLE
Unable to login or resolve usernames. Linux and Android clients

### ISSUE THREAD

**Issue by fuzzy** [keybase/client#26091]
Cannot send feedback through the client, finally got an actual error msg when trying that however.

Could not send log
```
API_NETWORK_ERROR: ERROR CODE 1601 - API network error: Post "https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json": tls: failed to verify certificate: x509: certificate signed by unknown authority in method keybase.1.config.logSend
```

Stack
```
Error: ERROR CODE 1601 - API network error: Post "https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json": tls: failed to verify certificate: x509: certificate signed by unknown authority in method keybase.1.config.logSend at new RPCError (file:///usr/share/keybase-app/desktop/dist/main.bundle.js:1:3860882) at convertToRPCError (file:///usr/share/keybase-app/desktop/dist/main.bundle.js:1:3861769) at convertToError (file:///usr/share/keybase-app/desktop/dist/main.bundle.js:1:3861828) at file:///usr/share/keybase-app/desktop/dist/main.bundle.js:1:2347958 at file:///usr/share/keybase-app/desktop/dist/822.bundle.js:2:324318 at Deferrals._call (file:///usr/share/keybase-app/desktop/dist/822.bundle.js:2:417479) at file:///usr/share/keybase-app/desktop/dist/822.bundle.js:2:417671 at trampoline (file:///usr/share/keybase-app/desktop/dist/822.bundle.js:2:417207) at Deferrals._fulfill (file:///usr/share/keybase-app/desktop/dist/822.bundle.js:2:417624) at ret (file:///usr/share/keybase-app/desktop/dist/822.bundle.js:2:416617)
```

Error Dump
```
{ "code": 1601, "fields": null, "desc": "API network error: Post \"https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json\": tls: failed to verify certificate: x509: certificate signed by unknown authority", "details": "Error code 1601: API_NETWORK_ERROR in method keybase.1.config.logSend" }
```

**Comment by gene1wood** [comment]
See #26088 #26089 and keybase/keybase-issues#4219

**Comment by fuzzy** [comment]
https://github.com/keybase/keybase-issues/issues/4219 held the answer. I don't see the release in the github releases, but the AUR has an updated PKGBUILD for any Arch(-based) users out there.
