### ISSUE TITLE
can't connect to keybase because x509 certificate signed by unknown auth

### ISSUE THREAD

**Issue by dschneiderch** [keybase/client#26102]
I cant do anything with keybase right now after the most recent macOS update.
I saw several issues with the same error message but I don't see any easy solution. no firewall or proxy, WFH.
any suggestions?

this is from the gui from the people tab but the cli gives the same certificate error. 
```API_NETWORK_ERROR: ERROR CODE 1601 - API network error: Post "https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json": x509: certificate signed by unknown authority in method keybase.1.config.logSend
Error: ERROR CODE 1601 - API network error: Post "https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json": x509: certificate signed by unknown authority in method keybase.1.config.logSend at new RPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:4125048) at convertToRPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:4102243) at convertToError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:4102334) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2473166 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/105.bundle.js:2:215977 at Deferrals._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/105.bundle.js:2:894539) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/105.bundle.js:2:894731 at trampoline (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/105.bundle.js:2:894267) at Deferrals._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/105.bundle.js:2:894684) at ret (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/105.bundle.js:2:893677)
{ "code": 1601, "fields": null, "desc": "API network error: Post \"https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json\": x509: certificate signed by unknown authority", "details": "Error code 1601: API_NETWORK_ERROR in method keybase.1.config.logSend" }```

**Comment by kallisti5** [comment]
Same error seen here under Linux.

I have a few files I need to pull off of kbfs.  If Zoom isn't going to maintain these servers anymore, they should fix the cert, and issue a shutdown notice.

**Comment by dschneiderch** [comment]
Keybase had an expired certificate authority and an issue with the auto updater so you’ll need to download and install keybase from https://keybase.io/docs/the_app/install_macos to be able to access keybase again

I see this after updating
![Screenshot 2024-01-02 at 12 21 30](https://github.com/keybase/client/assets/7461221/6f2b4ec3-0ea7-4ce1-b1d6-041530887bcd)
