### ISSUE TITLE
Service Outage ?

### ISSUE THREAD

**Issue by soltrinox** [keybase/client#26134]
Is there a service outage for Keybase at this time?

**Comment by soltrinox** [comment]
It looks like the SSL Certs have expired. The self signed certs are saying the service is experiencing bad things.

**Comment by soltrinox** [comment]
API_NETWORK_ERROR: ERROR CODE 1601 - API network error: Post "https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json": x509: certificate signed by unknown authority in method keybase.1.config.logSend
Error: ERROR CODE 1601 - API network error: Post "https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json": x509: certificate signed by unknown authority in method keybase.1.config.logSend at new RPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:4125048) at convertToRPCError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:4102243) at convertToError (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:4102334) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:1:2473166 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/105.bundle.js:2:215977 at Deferrals._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/105.bundle.js:2:894539) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/105.bundle.js:2:894731 at trampoline (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/105.bundle.js:2:894267) at Deferrals._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/105.bundle.js:2:894684) at ret (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/105.bundle.js:2:893677)
{ "code": 1601, "fields": null, "desc": "API network error: Post \"https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json\": x509: certificate signed by unknown authority", "details": "Error code 1601: API_NETWORK_ERROR in method keybase.1.config.logSend" }

**Comment by zapu** [comment]
We had to replace an SSL cert in the client after it expired last year, please download and install a new version from the usual places (keybase.io, app stores, linux repositories etc.).

**Comment by cristobal** [comment]
I have the same error, i just downloaded a new version but it does not seem to be the latest for MacOS or the download links still referer to an old version on Mac?
![Screenshot 2024-01-09 at 13 14 42](https://github.com/keybase/client/assets/155505/fc98bd88-e6e6-4a9b-9409-7f90e831fa7d)

**Comment by cristobal** [comment]
Managed to get the latest version 6.2.5, everything works fine now 👌🏽
