### ISSUE TITLE
ERROR API network error: Post "https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json": x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by poppingtonic** [keybase/client#26151]
This occurs when I'm trying to send logs using
```
keybase log send
```

```
API_NETWORK_ERROR: ERROR CODE 1601 - API network error: Post "https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json": x509: certificate signed by unknown authority in method keybase.1.config.logSend
Error: ERROR CODE 1601 - API network error: Post "https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json": x509: certificate signed by unknown authority in method keybase.1.config.logSend at new RPCError (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:4125048) at convertToRPCError (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:4102243) at convertToError (file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:4102334) at file:///opt/keybase/resources/app/desktop/dist/main.bundle.js:1:2473166 at file:///opt/keybase/resources/app/desktop/dist/105.bundle.js:2:215977 at Deferrals._call (file:///opt/keybase/resources/app/desktop/dist/105.bundle.js:2:894539) at file:///opt/keybase/resources/app/desktop/dist/105.bundle.js:2:894731 at trampoline (file:///opt/keybase/resources/app/desktop/dist/105.bundle.js:2:894267) at Deferrals._fulfill (file:///opt/keybase/resources/app/desktop/dist/105.bundle.js:2:894684) at ret (file:///opt/keybase/resources/app/desktop/dist/105.bundle.js:2:893677)
{ "code": 1601, "fields": null, "desc": "API network error: Post \"https://api-0.core.keybaseapi.com/_/api/1.0/logdump/send.json\": x509: certificate signed by unknown authority", "details": "Error code 1601: API_NETWORK_ERROR in method keybase.1.config.logSend" }
```

**Comment by poppingtonic** [comment]
fixed by update
