### ISSUE TITLE
Uncaught Exception: Error: Object has been destroyed

### ISSUE THREAD

**Issue by stephenyeargin** [keybase/client#3232]
Got this when clicking on menu bar icon. Worth noting that at the time, there was a Dock icon that doesn't seem to return on a relaunch of the application.

![screen shot 2016-06-27 at 10 25 37 pm](https://cloud.githubusercontent.com/assets/80459/16402981/7686d84a-3cb6-11e6-9628-dfc4e55165fb.png)

```
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at sendWrapper (/Applications/Keybase.app/Contents/Resources/electron.asar/browser/api/web-contents.js:107:24)
    at /Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:76:934
    at Array.forEach (native)
    at EventEmitter.<anonymous> (/Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:76:905)
    at emitNone (events.js:86:13)
    at EventEmitter.emit (events.js:185:7)
    at f (/Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:76:8493)
    at Tray.n (/Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:76:8124)
    at emitTwo (events.js:106:13)
  ```

---

Keybase GUI Version: 1.0.16-20160624110018+8ca7e60
my log id: 73a4c69922abccf2b36bc21c

**Comment by cjb** [comment]
Thanks, we'll get a fixed build out soon. (In the meantime you could use Keybase by killing and relaunching it, and avoiding cmd-q.)

**Comment by cjb** [comment]
Hi, the build containing this fix is live now.  (You can run "keybase update check" and run the longer command it mentions to get it immediately.)  Let us know if you have any more problems!

**Comment by stephenyeargin** [comment]
👍
