### ISSUE TITLE
Crash after quitting?

### ISSUE THREAD

**Issue by aredridel** [keybase/client#3233]
Hit command-q on one of those popup windows for accessing a stranger's files

Clicking on the keybase icon in the menu bar then gave me a javascript stack trace

```
Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at sendWrapper (/Applications/Keybase.app/Contents/Resources/electron.asar/browser/api/web-contents.js:107:24)
    at /Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:76:934
    at Array.forEach (native)
    at EventEmitter.<anonymous> (/Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:76:905)
    at emitNone (events.js:86:13)
    at EventEmitter.emit (events.js:185:7)
    at f (/Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:76:8493)
    at Tray.n (/Applications/Keybase.app/Contents/Resources/app/desktop/dist/main.bundle.js:76:8124)
    at emitTwo (events.js:106:13)
```

my log id: aacd16e2e30841b466286d1c

**Comment by twof** [comment]
I was able to reproduce by simply clicking the keybase icon in the bar at the top and hitting command q

088a21760fc64adbc057e71c

**Comment by cjb** [comment]
Thanks folks. We'll get a fixed build out soon. (In the meantime you could use Keybase by killing and relaunching it, and avoiding cmd-q.)

**Comment by aredridel** [comment]
(just what I did!)

**Comment by cjb** [comment]
Hi, the build containing this fix is live now.  (You can run "keybase update check" and run the longer command it mentions to get it immediately.)  Let us know if you have any more problems!

**Comment by aredridel** [comment]
Thank you! All good!
