### ISSUE TITLE
Keybase GUI can't connect to socket (fresh installation)

### ISSUE THREAD

**Issue by robertlemke** [keybase/client#3265]
I use a fresh download of Keybase GUI Version: 1.0.16-20160627110020+11e6f10.

When I start the application and try to login with my username, the Keybase GUI will try to connect endlessly.

In the console I can see that Keybase tries to connect to a socket, but for some reason can't:

```
log: Wed Jun 29 2016 13:27:57 GMT+0200 (CEST) (1467199677746): RPC [I] localhost: connecting (attempt 49)
log: Wed Jun 29 2016 13:27:57 GMT+0200 (CEST) (1467199677747): RPC [W] localhost: Error: connect ENOENT /Users/--redacted--/Library/Caches/Keybase/keybased.sock
From Keybase: log: Wed Jun 29 2016 13:27:57 GMT+0200 (CEST) (1467199677833): RPC [I] localhost: connecting (attempt 48)
From Keybase: log: Wed Jun 29 2016 13:27:57 GMT+0200 (CEST) (1467199677833): RPC [W] localhost: Error: connect ENOENT /Users/--redacted--/Library/Caches/Keybase/keybased.sock
From Keybase: log: Wed Jun 29 2016 13:27:58 GMT+0200 (CEST) (1467199678141): RPC [I] localhost: connecting (attempt 45)
From Keybase: log: Wed Jun 29 2016 13:27:58 GMT+0200 (CEST) (1467199678141): RPC [W] localhost: Error: connect ENOENT /Users/--redacted--/Library/Caches/Keybase/keybased.sock
```

When I stop Keybase (which I launched in a Terminal) with CTRL+c, I see the following output:

```
^Clog: Wed Jun 29 2016 13:27:58 GMT+0200 (CEST) (1467199678281): Installer (stdout):
log: Wed Jun 29 2016 13:27:58 GMT+0200 (CEST) (1467199678281): Installer (stderr): 06.29.2016 13:27:09.476 KBInstaller:27[DEBG] Installables: (
    "<KBHelperTool: 0x7fa812f24d50>",
    "<KBUpdaterService: 0x7fa812c6e0e0>",
    "<KBService: 0x7fa812c75cc0>",
    "<KBFuseComponent: 0x7fa812f4b210>",
    "<KBFSService: 0x7fa812f4bcf0>",
    "<KBCommandLine: 0x7fa812f4c250>"
)
06.29.2016 13:27:09.476 KBInstaller:32[DEBG] Install: Privileged Helper
06.29.2016 13:27:09.596 KBInstaller:32[DEBG] Install: Updater
06.29.2016 13:27:09.596 KBTask:44[DEBG] Task: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater

log: Wed Jun 29 2016 13:27:58 GMT+0200 (CEST) (1467199678281): Installer (err): { Error: Command failed: /Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app --run-mode=prod
06.29.2016 13:27:09.476 KBInstaller:27[DEBG] Installables: (
    "<KBHelperTool: 0x7fa812f24d50>",
    "<KBUpdaterService: 0x7fa812c6e0e0>",
    "<KBService: 0x7fa812c75cc0>",
    "<KBFuseComponent: 0x7fa812f4b210>",
    "<KBFSService: 0x7fa812f4bcf0>",
    "<KBCommandLine: 0x7fa812f4c250>"
)
06.29.2016 13:27:09.476 KBInstaller:32[DEBG] Install: Privileged Helper
06.29.2016 13:27:09.596 KBInstaller:32[DEBG] Install: Updater
06.29.2016 13:27:09.596 KBTask:44[DEBG] Task: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater

    at ChildProcess.exithandler (child_process.js:214:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: true,
  code: null,
  signal: 'SIGINT',
  cmd: '/Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app --run-mode=prod' }
log: Wed Jun 29 2016 13:27:58 GMT+0200 (CEST) (1467199678282): Error:  { Error: Command failed: /Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app --run-mode=prod
06.29.2016 13:27:09.476 KBInstaller:27[DEBG] Installables: (
    "<KBHelperTool: 0x7fa812f24d50>",
    "<KBUpdaterService: 0x7fa812c6e0e0>",
    "<KBService: 0x7fa812c75cc0>",
    "<KBFuseComponent: 0x7fa812f4b210>",
    "<KBFSService: 0x7fa812f4bcf0>",
    "<KBCommandLine: 0x7fa812f4c250>"
)
06.29.2016 13:27:09.476 KBInstaller:32[DEBG] Install: Privileged Helper
06.29.2016 13:27:09.596 KBInstaller:32[DEBG] Install: Updater
06.29.2016 13:27:09.596 KBTask:44[DEBG] Task: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater

    at ChildProcess.exithandler (child_process.js:214:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: true,
  code: null,
  signal: 'SIGINT',
  cmd: '/Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/MacOS/Keybase --app-path=/Applications/Keybase.app --run-mode=prod' }
```

**Comment by cjb** [comment]
Launching it from the terminal may have caused the problem.  Please try:

drag Keybase.app into /Applications
double click it

If it still fails, please type `keybase log send` and send us the result.  Thanks!

**Comment by madkins** [comment]
I get the same errors in Console.app when opening from the GUI app:
```
log: Tue Aug 23 2016 02:22:09 GMT-0400 (EDT) (1471933329291): RPC [I] localhost: connecting (attempt 24)
log: Tue Aug 23 2016 02:22:09 GMT-0400 (EDT) (1471933329292): RPC [W] localhost: Error: connect ENOENT /Users/madkins/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Aug 23 2016 02:22:09 GMT-0400 (EDT) (1471933329379): RPC [I] localhost: connecting (attempt 23)
From Keybase: log: Tue Aug 23 2016 02:22:09 GMT-0400 (EDT) (1471933329381): RPC [W] localhost: Error: connect ENOENT /Users/madkins/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Aug 23 2016 02:22:10 GMT-0400 (EDT) (1471933330224): RPC [I] localhost: connecting (attempt 21)
From Keybase: log: Tue Aug 23 2016 02:22:10 GMT-0400 (EDT) (1471933330224): RPC [W] localhost: Error: connect ENOENT /Users/madkins/Library/Caches/Keybase/keybased.sock
log: Tue Aug 23 2016 02:22:10 GMT-0400 (EDT) (1471933330293): RPC [I] localhost: connecting (attempt 25)
log: Tue Aug 23 2016 02:22:10 GMT-0400 (EDT) (1471933330294): RPC [W] localhost: Error: connect ENOENT /Users/madkins/Library/Caches/Keybase/keybased.sock
From Keybase: log: Tue Aug 23 2016 02:22:10 GMT-0400 (EDT) (1471933330383): RPC [I] localhost: connecting (attempt 24)
From Keybase: log: Tue Aug 23 2016 02:22:10 GMT-0400 (EDT) (1471933330384): RPC [W] localhost: Error: connect ENOENT /Users/madkins/Library/Caches/Keybase/keybased.sock
```
I'd send the log results, but running `keybase {anything}` just returns `keybase: command not found`, so I'm guessing something's just failing with the install prior to making that binary available?

**Comment by gabriel** [comment]
Can you run this:

```sh
/Applications/Keybase.app/Contents/SharedSupport/bin/keybase log send
```

Thanks for the bug report!

**Comment by gabriel** [comment]
We have a new build which might resolve installer flakiness, in this build if you want to try it out:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160830185045%2B1a947f1.dmg

**Comment by gabriel** [comment]
Known issue we are working on getting fix into release channel. See https://github.com/keybase/client/issues/4150 for more info. 

If you encounter this bug, this build resolves it temporarily:
https://keybase.pub/gabrielh/Keybase-1.0.17-20160830185045%2B1a947f1.dmg
