### ISSUE TITLE
out of memory error trying to prove http

### ISSUE THREAD

**Issue by lygaret** [keybase/client#3926]
my log id: cf27d9310f703bdae818251c

```bash
$ keybase prove http
Web site to check: accidental.cc
You will be asked to post a file to:
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x14c08d0, 0x16)
	/usr/local/go/src/runtime/panic.go:530 +0x90
runtime.sysMap(0xca43910000, 0xe0730000, 0x0, 0x1c055b8)
	/usr/local/go/src/runtime/mem_linux.go:206 +0x9b
runtime.(*mheap).sysAlloc(0x1be9760, 0xe0730000, 0x3)
	/usr/local/go/src/runtime/malloc.go:429 +0x191
runtime.(*mheap).grow(0x1be9760, 0x70398, 0x0)
	/usr/local/go/src/runtime/mheap.go:651 +0x63
runtime.(*mheap).allocSpanLocked(0x1be9760, 0x70394, 0x7f4f730748d8)
	/usr/local/go/src/runtime/mheap.go:553 +0x4f6
runtime.(*mheap).alloc_m(0x1be9760, 0x70394, 0xffffff0100000000, 0x7f4f6a65ce10)
	/usr/local/go/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0x7f4f6a65ce28)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x1be9760, 0x70394, 0x10100000000, 0xc8201fad80)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.largeAlloc(0xe0727ff0, 0x0, 0xc820264401)
	/usr/local/go/src/runtime/malloc.go:766 +0xb3
runtime.mallocgc.func3()
	/usr/local/go/src/runtime/malloc.go:664 +0x33
runtime.systemstack(0xc8201fb840)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1048

goroutine 38 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc82004d130 sp=0xc82004d128
runtime.mallocgc(0xe0727ff0, 0xed2b20, 0xc800000000, 0x18)
	/usr/local/go/src/runtime/malloc.go:665 +0x9eb fp=0xc82004d208 sp=0xc82004d130
runtime.newarray(0xed2b20, 0x95a1aaa, 0xc8201f6400)
	/usr/local/go/src/runtime/malloc.go:798 +0xc9 fp=0xc82004d248 sp=0xc82004d208
runtime.growslice(0xed25e0, 0xc8204ae000, 0x77b4800, 0x77b4800, 0x77b4801, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/slice.go:100 +0x2c1 fp=0xc82004d2b8 sp=0xc82004d248
github.com/keybase/client/go/vendor/github.com/kr/text.WrapWords(0xc820268660, 0x1, 0x1, 0x1, 0x33, 0x186a0, 0x0, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/kr/text/wrap.go:82 +0x54f fp=0xc82004d3a8 sp=0xc82004d2b8
github.com/keybase/client/go/vendor/github.com/kr/text.WrapBytes(0xc820224980, 0x36, 0x40, 0x33, 0x0, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/kr/text/wrap.go:26 +0x1c3 fp=0xc82004d4f0 sp=0xc82004d3a8
github.com/keybase/client/go/client.Paragraph.Output(0xc820224880, 0x36, 0x40, 0x1, 0x39, 0xc820222800, 0x3, 0x7f4f730b7320, 0xc820030010)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/markup.go:73 +0x157 fp=0xc82004d658 sp=0xc82004d4f0
github.com/keybase/client/go/client.(*Renderer).FlushParagraph(0xc820226b10)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/markup.go:130 +0x53 fp=0xc82004d6a8 sp=0xc82004d658
github.com/keybase/client/go/client.(*Renderer).RenderNode(0xc820226b10, 0xc8202a85b0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/markup.go:193 +0x29b fp=0xc82004d748 sp=0xc82004d6a8
github.com/keybase/client/go/client.(*Renderer).RenderNode(0xc820226b10, 0xc8202a8540)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/markup.go:185 +0x1af fp=0xc82004d7e8 sp=0xc82004d748
github.com/keybase/client/go/client.(*Renderer).RenderNode(0xc820226b10, 0xc8202a83f0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/markup.go:185 +0x1af fp=0xc82004d888 sp=0xc82004d7e8
github.com/keybase/client/go/client.(*Renderer).RenderNode(0xc820226b10, 0xc8202a8310)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/markup.go:185 +0x1af fp=0xc82004d928 sp=0xc82004d888
github.com/keybase/client/go/client.(*Renderer).RenderNode(0xc820226b10, 0xc8202a82a0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/markup.go:185 +0x1af fp=0xc82004d9c8 sp=0xc82004d928
github.com/keybase/client/go/client.(*Renderer).RenderNodes(0xc820226b10, 0xc8202b0030, 0x1, 0x1)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/markup.go:107 +0x65 fp=0xc82004da10 sp=0xc82004d9c8
github.com/keybase/client/go/client.Render(0x7f4f730b7320, 0xc820030010, 0xc8202227e0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/markup.go:218 +0x39d fp=0xc82004db60 sp=0xc82004da10
github.com/keybase/client/go/client.RenderText(0x7f4f730b7320, 0xc820030010, 0xc8202aa1a0, 0xc4, 0x1)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/markup.go:226 +0x19e fp=0xc82004dc08 sp=0xc82004db60
github.com/keybase/client/go/client.ProveUI.render(0xc8201a1710, 0x0, 0xc8202aa1a0, 0xc4, 0x1)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/ui.go:608 +0x95 fp=0xc82004dc68 sp=0xc82004dc08
github.com/keybase/client/go/client.ProveUI.PreProofWarning(0xc8201a1710, 0x0, 0x7f4f730baf08, 0xc820224700, 0x0, 0xc8202aa1a0, 0xc4, 0x1, 0xc8202268d0, 0x0, ...)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/ui.go:617 +0x61 fp=0xc82004dcb0 sp=0xc82004dc68
github.com/keybase/client/go/client.(*ProveUI).PreProofWarning(0xc82029c520, 0x7f4f730baf08, 0xc820224700, 0x0, 0xc8202aa1a0, 0xc4, 0x1, 0xe8ce00, 0x0, 0x0)
	<autogenerated>:334 +0xee fp=0xc82004dd10 sp=0xc82004dcb0
github.com/keybase/client/go/protocol.ProveUiProtocol.func8(0x7f4f730baf08, 0xc820224700, 0xe8ce00, 0xc8202684e0, 0x0, 0x0, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/protocol/prove_ui.go:130 +0x18e fp=0xc82004ddb8 sp=0xc82004dd10
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*callRequest).Serve(0xc8202269c0, 0x7f4f730ba6a8, 0xc820224500, 0xc820268560, 0x1679c90)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/request.go:76 +0x24a fp=0xc82004df40 sp=0xc82004ddb8
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*receiveHandler).handleReceiveDispatch.func1(0x7f4f730baf48, 0xc8202269c0, 0xc82021c7e0, 0xc820268560, 0x1679c90)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/receiver.go:121 +0x57 fp=0xc82004df78 sp=0xc82004df40
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82004df80 sp=0xc82004df78
created by github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*receiveHandler).handleReceiveDispatch
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/receiver.go:123 +0x3cf

goroutine 1 [select, 1 minutes]:
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*dispatch).Call(0xc820224540, 0x7f4f730ba8a8, 0xc8200103e8, 0x14f0b80, 0x1a, 0xedcae0, 0xc820286a00, 0xea07e0, 0xc82029c660, 0x7f4f730ba820, ...)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/dispatch.go:70 +0xb1a
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*Client).Call(0xc820286980, 0x7f4f730ba8a8, 0xc8200103e8, 0x14f0b80, 0x1a, 0xedcae0, 0xc820286a00, 0xea07e0, 0xc82029c660, 0x0, ...)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/client.go:37 +0x259
github.com/keybase/client/go/protocol.ProveClient.StartProof(0x7f4f730ba850, 0xc820286980, 0x7f4f730ba8a8, 0xc8200103e8, 0x0, 0x7ffccdcff16e, 0x4, 0x0, 0x0, 0x100, ...)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/protocol/prove.go:86 +0x23c
github.com/keybase/client/go/client.(*CmdProve).Run(0xc82001ae60, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/cmd_prove.go:93 +0x48e
main.mainInner(0xc8201b4000, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/keybase/main.go:131 +0xbba
main.main()
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/keybase/main.go:52 +0x1ab

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 5 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x132
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x37

goroutine 7 [select]:
github.com/keybase/client/go/libkb.(*LoginState).requests(0xc8201a1560)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/login_state.go:887 +0x81b
created by github.com/keybase/client/go/libkb.NewLoginState
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/login_state.go:114 +0x2a0

goroutine 8 [chan receive, 1 minutes]:
main.HandleSignals()
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/keybase/main.go:292 +0x1ef
created by main.main
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/keybase/main.go:51 +0x19d

goroutine 34 [select, 1 minutes, locked to thread]:
runtime.gopark(0x167c408, 0xc820028728, 0x13b3478, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc820028728, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc820028728)
	/usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 9 [running]:
	goroutine running on other thread; stack unavailable
created by github.com/keybase/client/go/vendor/stathat.com/c/ramcache.New
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/stathat.com/c/ramcache/ramcache.go:44 +0x161

goroutine 10 [select]:
github.com/keybase/client/go/vendor/stathat.com/c/ramcache.(*Ramcache).cleanup(0xc82001ce40)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/stathat.com/c/ramcache/ramcache.go:164 +0x12d
created by github.com/keybase/client/go/vendor/stathat.com/c/ramcache.New
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/stathat.com/c/ramcache/ramcache.go:44 +0x161

goroutine 11 [select]:
github.com/keybase/client/go/vendor/stathat.com/c/ramcache.(*Ramcache).cleanup(0xc82001cf00)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/stathat.com/c/ramcache/ramcache.go:164 +0x12d
created by github.com/keybase/client/go/vendor/stathat.com/c/ramcache.New
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/stathat.com/c/ramcache/ramcache.go:44 +0x161

goroutine 12 [select]:
github.com/keybase/client/go/libkb.(*LinkCache).handle(0xc82001d200)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/link_cache.go:136 +0x11f2
created by github.com/keybase/client/go/libkb.NewLinkCache
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/link_cache.go:49 +0x310

goroutine 13 [select]:
github.com/keybase/client/go/libkb.(*LinkCache).periodic(0xc82001d200)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/link_cache.go:204 +0x11d
created by github.com/keybase/client/go/libkb.NewLinkCache
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/link_cache.go:50 +0x332

goroutine 14 [select, 1 minutes]:
github.com/keybase/client/go/service.(*logFwd).process(0xc820258fc0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/service/log_fwd.go:63 +0x46f
created by github.com/keybase/client/go/service.newLogFwd
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/service/log_fwd.go:40 +0x1b6

goroutine 35 [select, 1 minutes]:
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*framedMsgpackEncoder).writerLoop(0xc820224500)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/codec.go:141 +0x20a
created by github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.newFramedMsgpackEncoder
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/codec.go:76 +0x1d0

goroutine 36 [select, 1 minutes]:
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*receiveHandler).taskLoop(0xc82021c7e0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/receiver.go:55 +0x3ee
created by github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.newReceiveHandler
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/receiver.go:48 +0x255

goroutine 37 [IO wait, 1 minutes]:
net.runtime_pollWait(0x7f4f730ba0e8, 0x72, 0xc8202b2000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8202a8220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8202a8220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8202a81c0, 0xc8202b2000, 0x1000, 0x1000, 0x0, 0x7f4f730b3050, 0xc820010188)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8202b0000, 0xc8202b2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc82021c240)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadByte(0xc82021c240, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:229 +0x7a
github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec.(*ioDecReader).readn1(0xc8202b4370, 0x3)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec/decode.go:286 +0x41
github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec.(*msgpackDecDriver).readNextBd(0xc8202ac0f0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec/msgpack.go:560 +0x3a
github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec.(*msgpackDecDriver).TryDecodeAsNil(0xc8202ac0f0, 0xc81ffecb00)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec/msgpack.go:587 +0x2f
github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec.(*Decoder).decode(0xc8202b4300, 0xea8dc0, 0xc8202227b0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec/decode.go:1512 +0x73
github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec.(*Decoder).Decode(0xc8202b4300, 0xea8dc0, 0xc8202227b0, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec/decode.go:1421 +0x74
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*packetHandler).loadNextFrame(0xc820224580, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/packetizer.go:61 +0xb6
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*packetHandler).NextFrame(0xc820224580, 0x0, 0x0, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/packetizer.go:34 +0x54
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*transport).receiveFramesLoop(0xc8202a4400)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/transport.go:145 +0x94
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*transport).receiveFrames.func1(0xc8202a4400)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/transport.go:117 +0x21
created by github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc.(*transport).receiveFrames
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/transport.go:118 +0x66
```

**Comment by maxtaco** [comment]
Urg, never seen this one before.  Which OS are you on?

**Comment by lygaret** [comment]
Ubuntu 16.10, 16Gb RAM on this machine.

Possibly interesting: https proof worked right off, and accidental.cc does a http -> https redirect on connect.
