### ISSUE TITLE
KBFS is not mounted correctly - Transport endpoint is not connected.

### ISSUE THREAD

**Issue by Flat** [keybase/client#4813]
Keybase GUI Version: 1.0.18-20161027231452+7894c1f

When trying to to access / or /keybase an error is shown.
```
Error when getting information for file '/keybase': Transport endpoint is not connected.
```

**Comment by strib** [comment]
Can you please do a `keybase log send` and let us know the resulting ID?  Thanks.

**Comment by Flat** [comment]
Seems that function is a little wonky for me as well.

```
This command will send recent keybase log entries to keybase.io
for debugging purposes only.

These logs don’t include your private keys or encrypted data,
but they will include filenames and other metadata keybase normally
can’t read, for debugging purposes.

runtime: nelems=256 nfree=0 nalloc=256 previous allocCount=254 nfreed=65534
fatal error: sweep increased allocation count

runtime stack:
runtime.throw(0x108cfd3, 0x20)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.(*mspan).sweep(0x7ff0283224e0, 0x500000000, 0xc400000001)
	/usr/local/go/src/runtime/mgcsweep.go:287 +0x7ab
runtime.sweepone(0x433c56)
	/usr/local/go/src/runtime/mgcsweep.go:112 +0xfe
runtime.gosweepone.func1()
	/usr/local/go/src/runtime/mgcsweep.go:124 +0x2b
runtime.systemstack(0xc420020000)
	/usr/local/go/src/runtime/asm_amd64.s:298 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1079

goroutine 3 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:252 fp=0xc42002cf48 sp=0xc42002cf40
runtime.gosweepone(0x0)
	/usr/local/go/src/runtime/mgcsweep.go:125 +0x4a fp=0xc42002cf78 sp=0xc42002cf48
runtime.bgsweep(0xc42005c000)
	/usr/local/go/src/runtime/mgcsweep.go:66 +0xbb fp=0xc42002cfb8 sp=0xc42002cf78
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42002cfc0 sp=0xc42002cfb8
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:195 +0x61

goroutine 1 [runnable]:
syscall.Syscall(0x0, 0x8, 0xc42038c000, 0xfda, 0xfda, 0xfda, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0x8, 0xc42038c000, 0xfda, 0x1000, 0xf01, 0x100000000000000, 0x0)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:783 +0x55
syscall.Read(0x8, 0xc42038c000, 0xfda, 0x1000, 0xc420051520, 0x434921, 0xc4200001a0)
	/usr/local/go/src/syscall/syscall_unix.go:161 +0x49
os.(*File).read(0xc420280000, 0xc42038c000, 0xfda, 0x1000, 0x8, 0x8, 0x2ce80c)
	/usr/local/go/src/os/file_unix.go:228 +0x4f
os.(*File).Read(0xc420280000, 0xc42038c000, 0xfda, 0x1000, 0x0, 0x2ce80c, 0x0)
	/usr/local/go/src/os/file.go:101 +0x59
io.ReadAtLeast(0x1670d00, 0xc420280000, 0xc42038c000, 0xfda, 0x1000, 0xfda, 0x103bfc0, 0x0, 0x1670d00)
	/usr/local/go/src/io/io.go:307 +0xa4
io.ReadFull(0x1670d00, 0xc420280000, 0xc42038c000, 0xfda, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/keybase/client/go/vendor/github.com/rogpeppe/rog-go/reverse.(*Scanner).fillbuf(0xc42042a700, 0x7e, 0xc4203a2400)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/rogpeppe/rog-go/reverse/scan.go:103 +0x2a1
github.com/keybase/client/go/vendor/github.com/rogpeppe/rog-go/reverse.(*Scanner).Scan(0xc42042a700, 0xc42038c026)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/rogpeppe/rog-go/reverse/scan.go:181 +0x5e
github.com/keybase/client/go/libkb.tail(0x1687460, 0xc420136600, 0xc4202e8690, 0x29, 0x186a0, 0x1, 0x6a60a)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/log_send.go:127 +0x123
github.com/keybase/client/go/libkb.(*LogSendContext).LogSend(0xc420051b98, 0xc420330000, 0xd02, 0x186a0, 0xc4202e8630, 0x2a, 0xc4202e85d0, 0x2d)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/log_send.go:152 +0x3d8
github.com/keybase/client/go/client.(*CmdLogSend).Run(0xc4202a2020, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/cmd_log_send.go:90 +0x31f
main.mainInner(0xc42015ca00, 0x1117188, 0x1063bf5)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/keybase/main.go:132 +0x5b2
main.main()
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/keybase/main.go:56 +0x8b

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x157
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 18 [select]:
github.com/keybase/client/go/libkb.(*LoginState).requests(0xc4202331a0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/login_state.go:900 +0x6b5
created by github.com/keybase/client/go/libkb.NewLoginState
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/login_state.go:112 +0x242

goroutine 19 [chan receive]:
main.HandleSignals()
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/keybase/main.go:293 +0x175
created by main.main
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/keybase/main.go:55 +0x7d

goroutine 7 [select, locked to thread]:
runtime.gopark(0x1117938, 0x0, 0x1067bc5, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:259 +0x13a
runtime.selectgoImpl(0xc42002ef30, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:423 +0x11d9
runtime.selectgo(0xc42002ef30)
	/usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal1_unix.go:304 +0x2f3
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 20 [select]:
github.com/keybase/client/go/vendor/stathat.com/c/ramcache.(*Ramcache).cleanup(0xc42013ec60)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/stathat.com/c/ramcache/ramcache.go:164 +0x13f
created by github.com/keybase/client/go/vendor/stathat.com/c/ramcache.New
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/stathat.com/c/ramcache/ramcache.go:44 +0x179

goroutine 21 [select]:
github.com/keybase/client/go/vendor/stathat.com/c/ramcache.(*Ramcache).cleanup(0xc42013ed20)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/stathat.com/c/ramcache/ramcache.go:164 +0x13f
created by github.com/keybase/client/go/vendor/stathat.com/c/ramcache.New
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/stathat.com/c/ramcache/ramcache.go:44 +0x179

goroutine 22 [select]:
github.com/keybase/client/go/vendor/stathat.com/c/ramcache.(*Ramcache).cleanup(0xc42013ede0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/stathat.com/c/ramcache/ramcache.go:164 +0x13f
created by github.com/keybase/client/go/vendor/stathat.com/c/ramcache.New
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/stathat.com/c/ramcache/ramcache.go:44 +0x179

goroutine 23 [select]:
github.com/keybase/client/go/libkb.(*LinkCache).handle(0xc42013f0e0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/link_cache.go:136 +0x110d
created by github.com/keybase/client/go/libkb.NewLinkCache
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/link_cache.go:49 +0x2d4

goroutine 24 [select]:
github.com/keybase/client/go/libkb.(*LinkCache).periodic(0xc42013f0e0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/link_cache.go:204 +0x123
created by github.com/keybase/client/go/libkb.NewLinkCache
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/link_cache.go:50 +0x2f6

goroutine 25 [select]:
github.com/keybase/client/go/vendor/stathat.com/c/ramcache.(*Ramcache).cleanup(0xc42013f1a0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/stathat.com/c/ramcache/ramcache.go:164 +0x13f
created by github.com/keybase/client/go/vendor/stathat.com/c/ramcache.New
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/stathat.com/c/ramcache/ramcache.go:44 +0x179

goroutine 26 [select]:
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.(*framedMsgpackEncoder).writerLoop(0xc4202d6200)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/codec.go:141 +0x1a4
created by github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.newFramedMsgpackEncoder
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/codec.go:76 +0x18e

goroutine 27 [select]:
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.(*receiveHandler).taskLoop(0xc42013f920)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/receiver.go:55 +0x32b
created by github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.newReceiveHandler
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/receiver.go:48 +0x23d

goroutine 28 [IO wait]:
net.runtime_pollWait(0x7ff028273390, 0x72, 0x4)
	/usr/local/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc42026f4f0, 0x72, 0xc42004db08, 0xc420014210)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc42026f4f0, 0x1675d40, 0xc420014210)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).Read(0xc42026f490, 0xc4202dc000, 0x1000, 0x1000, 0x0, 0x1675d40, 0xc420014210)
	/usr/local/go/src/net/fd_unix.go:243 +0x1a1
net.(*conn).Read(0xc420132198, 0xc4202dc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:173 +0x70
bufio.(*Reader).fill(0xc42013f380)
	/usr/local/go/src/bufio/bufio.go:97 +0x10c
bufio.(*Reader).ReadByte(0xc42013f380, 0xb9a1cd, 0xc420264c70, 0x2)
	/usr/local/go/src/bufio/bufio.go:231 +0x51
github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec.(*ioDecReader).readn1(0xc420264c70, 0x42e53b)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec/decode.go:286 +0x37
github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec.(*msgpackDecDriver).readNextBd(0xc42012cfa0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec/msgpack.go:560 +0x34
github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec.(*msgpackDecDriver).TryDecodeAsNil(0xc42012cfa0, 0xc4200001a0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec/msgpack.go:587 +0x51
github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec.(*Decoder).decode(0xc420264c00, 0xe5eb60, 0xc420296308)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec/decode.go:1512 +0x66
github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec.(*Decoder).Decode(0xc420264c00, 0xe5eb60, 0xc420296308, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-codec/codec/decode.go:1421 +0x84
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.(*packetHandler).loadNextFrame(0xc4202d6280, 0x166fc00, 0xc4202d4a00, 0xc4202ad3e0, 0xc4202ad440, 0xc42004df08)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/packetizer.go:61 +0x7a
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.(*packetHandler).NextFrame(0xc4202d6280, 0x0, 0xc4202e8201, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/packetizer.go:34 +0x40
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.(*transport).receiveFramesLoop(0xc420139380)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/transport.go:145 +0x62
github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.(*transport).receiveFrames.func1(0xc420139380)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/transport.go:117 +0x2b
created by github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc.(*transport).receiveFrames
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/vendor/github.com/keybase/go-framed-msgpack-rpc/rpc/transport.go:118 +0x87
```

**Comment by maxtaco** [comment]
Do you have a very small amount of memory on this machine?

**Comment by Flat** [comment]
I have 32GB of RAM. 
```
flat@kuroe  ~  free -h
              total        used        free      shared  buff/cache   available
Mem:            31G        3.0G         23G        280M        4.8G         27G
Swap:          6.7G          0B        6.7G

```

**Comment by Flat** [comment]
Rebooting allowed me to submit a log. ID: ```822e339c3e4d6929a303041c```

**Comment by strib** [comment]
@maxtaco: Looks like the service crashed first, a few hours before KBFS:

```
4317 2016-11-08T10:28:05.843107 ▶ [DEBU keybase util.go:391] 146 + IdentityTable::populate
4318 unexpected fault address 0x5b20b696e220
4319 fatal error: fault
4320 [signal SIGSEGV: segmentation violation code=0x1 addr=0x5b20b696e220 pc=0x45be64]
4321
4322 goroutine 18 [running]:
4323 runtime.throw(0x1065302, 0x5)
4324 /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc42037b468 sp=0xc42037b448
4325 runtime.sigpanic()
4326 /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc42037b4c0 sp=0xc42037b468
4327 runtime.aeshashbody()
4328 /usr/local/go/src/runtime/asm_amd64.s:912 +0x514 fp=0xc42037b4c8 sp=0xc42037b4c0
4329 runtime.mapassign1(0xef1460, 0xc420476390, 0xc42037b618, 0xc42037b628)
4330 /usr/local/go/src/runtime/hashmap.go:463 +0x87 fp=0xc42037b5b0 sp=0xc42037b4c8
4331 github.com/keybase/client/go/libkb.(*RemoteProofLinks).Insert(0xc4205f2290, 0x1689c40, 0xc420284b40, 0x0, 0x0)
4332 /root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/remote_proof_links.go:39 +0x19c fp=0xc42037b650 sp=0xc42037b5b0
4333 github.com/keybase/client/go/libkb.(*IdentityTable).insertRemoteProof(0xc420095080, 0x1689c40, 0xc420284b40)
4334 /root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/id_table.go:1110 +0x55 fp=0xc42037b688 sp=0xc42037b650
4335 github.com/keybase/client/go/libkb.remoteProofInsertIntoTable(0x1689c40, 0xc420284b40, 0xc420095080)
4336 /root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/id_table.go:383 +0x89 fp=0xc42037b6c0 sp=0xc42037b688
4337 github.com/keybase/client/go/libkb.(*SocialProofChainLink).insertIntoTable(0xc420284b40, 0xc420095080)
4338 /root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/id_table.go:224 +0x41 fp=0xc42037b6e8 sp=0xc42037b6c0
4339 github.com/keybase/client/go/libkb.(*IdentityTable).populate(0xc420095080, 0x0, 0x0)
4340 /root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/id_table.go:1096 +0x489 fp=0xc42037b7c8 sp=0xc42037b6e8
4341 github.com/keybase/client/go/libkb.NewIdentityTable(0xc420158a00, 0xc42065f310, 0x46, 0xc420465340, 0xc420394600, 0xc420158a00, 0x0, 0xc4205d9630)
4342 /root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/id_table.go:1077 +0x1fd fp=0xc42037b828 sp=0xc42037b7c8
4343 github.com/keybase/client/go/libkb.(*User).MakeIDTable(0xc420620420, 0x1, 0x0)
4344 /root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/user.go:410 +0x72 fp=0xc42037b888 sp=0xc42037b828
4345 github.com/keybase/client/go/libkb.LoadUser(0xc420158a00, 0xc4202ceae0, 0x20, 0x0, 0x0, 0x10000, 0x1687b80, 0xc4201d2360, 0x0, 0x0, ...)
4346 /root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/loaduser.go:204 +0xaa1 fp=0xc42037baf8 sp=0xc42037b888
4347 github.com/keybase/client/go/libkb.LoadMe(0xc420158a00, 0x0, 0x0, 0x0, 0x0, 0x10000, 0x1687b80, 0xc4201d2360, 0x0, 0x0, ...)
4348 /root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/loaduser.go:118 +0x45 fp=0xc42037bb70 sp=0xc42037baf8
4349 github.com/keybase/client/go/libkb.(*Account).UserInfo(0xc4201d2360, 0x16a7501, 0x0, 0x0, 0xc42000d6c0, 0x36, 0x36, 0xc420c6dd30, 0x44579e, 0xc42000d6c0, ...)
4350 /root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/account.go:398 +0xba fp=0xc42037bc90 sp=0xc42037bb70
4351 github.com/keybase/client/go/service.(*SessionHandler).CurrentSession.func1(0xc4201d2360)
4352 /root/build/gopaths/amd64/src/github.com/keybase/client/go/service/session.go:47 +0xcc fp=0xc42037bd88 sp=0xc42037bc90
4353 github.com/keybase/client/go/libkb.(*LoginState).requests(0xc42022f380)
4354 /root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/login_state.go:918 +0x610 fp=0xc42037bf88 sp=0xc42037bd88
4355 runtime.goexit()
4356 /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42037bf90 sp=0xc42037bf88
4357 created by github.com/keybase/client/go/libkb.NewLoginState
4358 /root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/login_state.go:112 +0x242
```

The KBFS stack definitely looks memory-related:

```
1809 2016-11-08T12:11:24.126900 ▶ [DEBU keybase socket.go:73] 3b9 | empty socket wrapper; need a new one
1810 2016-11-08T12:11:24.126913 ▶ [DEBU keybase socket_nix.go:96] 3ba Dialing unix:/run/user/1000/keybase/keybased.sock
1811 2016-11-08T12:11:24.126948 ▶ [DEBU keybase socket.go:88] 3bb | DialSocket -> ERROR: dial unix /run/user/1000/keybase/keybased.sock: connect: connection refused
1812 2016-11-08T12:11:24.126962 ▶ [WARN kbfs connection.go:354] 3bc (CONN KeybaseDaemonRPC 5313f510) Connection: error dialing transport: dial unix /run/user/1000/keybase/keybased.sock: connect: connection refused
1813 2016-11-08T12:11:24.126978 ▶ [WARN kbfs connection.go:519] 3bd KeybaseDaemonRPC: connection error: "dial unix /run/user/1000/keybase/keybased.sock: connect: connection refused"; retrying in 1m3.563546944s
1814 runtime: nelems=512 nfree=437 nalloc=75 previous allocCount=74 nfreed=65535
1815 fatal error: sweep increased allocation count
1816
1817 runtime stack:
1818 runtime.throw(0x1049692, 0x20)
1819 /usr/local/go/src/runtime/panic.go:566 +0x95
1820 runtime.(*mspan).sweep(0x7f4b5c259fa8, 0x6900000000, 0xc400000001)
1821 /usr/local/go/src/runtime/mgcsweep.go:287 +0x7ab
1822 runtime.sweepone(0x4340b6)
1823 /usr/local/go/src/runtime/mgcsweep.go:112 +0xfe
1824 runtime.gosweepone.func1()
1825 /usr/local/go/src/runtime/mgcsweep.go:124 +0x2b
1826 runtime.systemstack(0xc420020000)
1827 /usr/local/go/src/runtime/asm_amd64.s:298 +0x79
1828 runtime.mstart()
1829 /usr/local/go/src/runtime/proc.go:1079
1830
```

**Comment by maxtaco** [comment]
Never seen this one before. Seems very strange.

**Comment by cjb** [comment]
@Flat I'm reluctant to say this because it's a strong claim, but I suspect your machine has RAM corruption issues.  Perhaps try running a memory tester?

**Comment by Flat** [comment]
@cjb Just ran Memtest86+ for an hour, no errors. I understand that isn't a full pass of all tests on that short amount of time, but I find it unlikely to be a memory issue. This is a pretty consistent problem I have with keybase/KBFS. I also don't have any other issues with other programs crashing due to anything memory related. I will let Memtest86+ run overnight when I head to bed just to make sure, but I don't believe that to be the cause.

**Comment by cjb** [comment]
@Flat Interesting, I'm sorry it looks like I might be wasting your time! We've not had any other reports like this one.

**Comment by Flat** [comment]
@cjb Not wasting my time at all! After all, the more you rule out the easier it is to solve no?

**Comment by Flat** [comment]
Another log if there's any differentiating data. ID:```46a4b44369847bd4c8048c1c```

**Comment by adamhotep** [comment]
I also suffer from this (log id: `cb8b5b42e862bd25c755071c`, plenty of free memory, swap, and disk, using fuse 2.9.7 and keybase 1.0.18 on Debian Testing). It's possible that a reboot will solve this; I may have a kernel mismatch and/or similar issues from various upgrades, but I tend to let those lie since rebooting is such a time sink.

I wonder if it's a segfault issue in keybase and/or a bug in fuse as hinted at [this StackOverflow question](https://stackoverflow.com/questions/24966676/transport-endpoint-is-not-connected) on another piece of software getting the same error from fuse.  That question's second (yet highest rated) answer mentioned `fusermount -uz /keybase` but I didn't get that working before or after killing the keybase daemon (there's no "stop" command, "start" is implied by "status").

There may or may not be valuable information in the main.c of the [mhddfs-nosegfault code](https://github.com/vdudouyt/mhddfs-nosegfault) as compared to the [original](http://svn.uvw.ru/mhddfs/tags/release_0.1.39/) (sorry, I can't help there).

**Comment by adamhotep** [comment]
I also suffer from this (log id: `cb8b5b42e862bd25c755071c`, plenty of free memory, swap, and disk, using fuse 2.9.7 and keybase 1.0.18 on Debian Testing). It's possible that a reboot will solve this; I may have a kernel mismatch and/or similar issues from various upgrades, but I tend to let those lie since rebooting is such a time sink.

<pre>$ ls /keybase/public/chris
ls: cannot access '/keybase/public/chris': Transport endpoint is not connected</pre>

I wonder if it's a segfault issue in keybase and/or a bug in fuse as hinted at [this StackOverflow question](https://stackoverflow.com/questions/24966676/transport-endpoint-is-not-connected) on another piece of software getting the same error from fuse.  That question's second (yet highest rated) answer mentioned `fusermount -uz /keybase` but I didn't get that working before or after killing the keybase daemon (there's no "stop" command, "start" is implied by "status").

There may or may not be valuable information in the main.c of the [mhddfs-nosegfault code](https://github.com/vdudouyt/mhddfs-nosegfault) as compared to the [original](http://svn.uvw.ru/mhddfs/tags/release_0.1.39/) (sorry, I can't help there).

After some meddling, now I can't even _try_ to get kbfs working; it refuses to run and/or mount.  I'll probably revisit this next year after my next reboot.

**Comment by adamhotep** [comment]
Rebooted.  It works now.  I assume this was due to a kernel update or two that happened a while back.

I see from the photo of the memory test that Flat has tried rebooting.  Maybe it's kernel related?  I'm on the latest Debian Testing (now fully up to date) with Linux 4.8.0-1-amd64 if that helps.

Good luck and thanks to the keybase team for their wonderful work.

**Comment by Flat** [comment]
Seems like the issue hasn't reappeared for a while. Since it seems to be non-reproducible at this point I'm going to go ahead and close this.
