### ISSUE TITLE
KBFS client wasn't found

### ISSUE THREAD

**Issue by alexbrothman** [keybase/client#4899]
I'm seeing the following when I launch Keybase:

Error: KBFS client wasn't found at t.Error (native) at new t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:11:5254) at a (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:11:4885) at o (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:11:4810) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:5:23565 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:53:23817 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:35:1893) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:35:2044 at c (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:35:1671) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:35:2003)

I've performed an uninstall and reinstallation and continue to see it. I submitted a log earlier, ID: ef631dd85228e292506ce71c

Thanks

**Comment by jonbackhaus** [comment]
Same issue. My log ID: 3109636284f4cfe59297fd1c

**Comment by murshid1988** [comment]
Any fix to this?

**Comment by maxtaco** [comment]
@murshid1988 should all be fixed, can you send a `keybase log send?`

**Comment by murshid1988** [comment]
@maxtaco I just sent.

**Comment by JKatzwinkel** [comment]
b4dabd54d1c5bc2757e2e71c

**Comment by Phaiax** [comment]
#7385 
I guess if you run `upd.exe check` it should be fixed now.
