### ISSUE TITLE
Failed at the Keybase@0.0.1 gobuild-ios script './gobuild.sh ios'.

### ISSUE THREAD

**Issue by djdesign** [keybase/client#5217]
Getting Build error unable to get successful build  from latest repo pull as of 12/28/2016  commit `e11b4821cc37364cf5934f2b78817a08948057d2` with latest npm/node, also attempted earlier version combinations no success.

Any suggestions would be appreciated as I am, stumped by this searched but did not see anyone else with this error.

—Thank you in advance.

OS:     macOS 10.12.2
Node: v7.3.0
NPM:  v3.10.9 
<details><summary>Bash output:</summary><p>

```bash

bash-3.2$ npm run gobuild-ios

> Keybase@0.0.1 gobuild-ios /Users/DJ/projects/active/keybase/client/react-native
> ./gobuild.sh ios

Using temp GOPATH: /tmp/go-ios
Clearing /tmp/go-ios/src
Getting client (using local GOPATH)... To use git master, set LOCAL_CLIENT=0
Getting KBFS (via git clone)... To use local copy, set LOCAL_KBFS=1
Cloning into 'kbfs'...
remote: Counting objects: 29102, done.
remote: Compressing objects: 100% (761/761), done.
remote: Total 29102 (delta 516), reused 5 (delta 5), pack-reused 28336
Receiving objects: 100% (29102/29102), 37.51 MiB | 10.40 MiB/s, done.
Resolving deltas: 100% (21827/21827), done.
Re-vendoring...
Build gomobile...
Doing gomobile init (to skip, set SKIP_GOMOBILE_INIT=1)
Building for iOS (/Users/DJ/projects/active/keybase/client/react-native/ios/keybase.framework)...
/tmp/go-ios/bin/gomobile: go install -pkgdir=/tmp/go-ios/pkg/gomobile/pkg_darwin_arm -tags="ios" -ldflags -X github.com/keybase/client/go/libkb.PrereleaseBuild=20161228135003+e11b4821c github.com/keybase/client/go/bind failed: exit status 2
# github.com/keybase/kbfs/libkbfs
/tmp/go-ios/src/github.com/keybase/kbfs/libkbfs/identify_util.go:23: undefined: keybase1.TLFIdentifyFailure
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/Users/DJ/bin/npm" "run" "gobuild-ios"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! Keybase@0.0.1 gobuild-ios: `./gobuild.sh ios`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Keybase@0.0.1 gobuild-ios script './gobuild.sh ios'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the Keybase package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./gobuild.sh ios
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Keybase
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls Keybase
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/DJ/projects/active/keybase/client/react-native/npm-debug.log
```
</p></details>

<details><summary>npm-debug.log output:</summary><p>

```npm

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.3.0/bin/node',
1 verbose cli   '/Users/DJ/bin/npm',
1 verbose cli   'run',
1 verbose cli   'gobuild-ios' ]
2 info using npm@3.10.9
3 info using node@v7.3.0
4 verbose run-script [ 'pregobuild-ios', 'gobuild-ios', 'postgobuild-ios' ]
5 info lifecycle Keybase@0.0.1~pregobuild-ios: Keybase@0.0.1
6 silly lifecycle Keybase@0.0.1~pregobuild-ios: no script for pregobuild-ios, continuing
7 info lifecycle Keybase@0.0.1~gobuild-ios: Keybase@0.0.1
8 verbose lifecycle Keybase@0.0.1~gobuild-ios: unsafe-perm in lifecycle true
9 verbose lifecycle Keybase@0.0.1~gobuild-ios: PATH: /Users/DJ/lib/node_modules/npm/bin/node-gyp-bin:/Users/DJ/projects/active/keybase/client/react-native/node_modules/.bin:/usr/local/Cellar/node/7.3.0/bin:/Users/DJ/bin:/usr/local/bin:/usr/local/bin:/Users/DJ/.composer/vendor/bin:/Users/DJ/.nvm/bin:/Users/DJ/.nvm/:/Users/DJ/.nvm/nvm.sh:NVM_DIR=~/.nvm:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin
10 verbose lifecycle Keybase@0.0.1~gobuild-ios: CWD: /Users/DJ/projects/active/keybase/client/react-native
11 silly lifecycle Keybase@0.0.1~gobuild-ios: Args: [ '-c', './gobuild.sh ios' ]
12 silly lifecycle Keybase@0.0.1~gobuild-ios: Returned: code: 1  signal: null
13 info lifecycle Keybase@0.0.1~gobuild-ios: Failed to exec gobuild-ios script
14 verbose stack Error: Keybase@0.0.1 gobuild-ios: `./gobuild.sh ios`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/DJ/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/DJ/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid Keybase@0.0.1
16 verbose cwd /Users/DJ/projects/active/keybase/client/react-native
17 error Darwin 16.3.0
18 error argv "/usr/local/Cellar/node/7.3.0/bin/node" "/Users/DJ/bin/npm" "run" "gobuild-ios"
19 error node v7.3.0
20 error npm  v3.10.9
21 error code ELIFECYCLE
22 error Keybase@0.0.1 gobuild-ios: `./gobuild.sh ios`
22 error Exit status 1
23 error Failed at the Keybase@0.0.1 gobuild-ios script './gobuild.sh ios'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the Keybase package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     ./gobuild.sh ios
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs Keybase
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls Keybase
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
</p></details>

**Comment by cjb** [comment]
@djdesign We might have just broken just broken the build temporarily. I suspect you're the only person building iOS who doesn't work for Keybase, hence no other reports. Is it still happening?

**Comment by djdesign** [comment]
Yes it is.

**Comment by djdesign** [comment]
@cjb is there any updates that resolve this?

**Comment by cjb** [comment]
@djdesign I think you're the only person hitting the error. We've moved to yarn now instead of npm, that might be part of it. It's hard to debug three
