### ISSUE TITLE
"Got nil RMD for ..." when trying to group chat

### ISSUE THREAD

**Issue by yogsototh** [keybase/client#5729]
On macOS Sierra, Keybase Version 1.0.18-20170207120017+ce0f90d ,

I can chat 1-to-1 but when I try to make a group chat, I receive this cryptic error message.

~~~
Error: Got nil RMD for fd0da84303ce8a0dc11347dd3e4ae816 at t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:15:31264) at new t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:16:80) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:15:31660) at i (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:15:31588) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:12:14407 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:78:27307 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:56:29684) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:56:29835 at c (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:56:29462) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:56:29794)
~~~

Maybe, the two other people I try to talk with aren't following each other, or something like that, or it may be something else.

**Comment by maxtaco** [comment]
Can you do a `keybase log send`?

Cc: @mmaxim

**Comment by strib** [comment]
Likely this is already fixed in master and will be in the next release, but it would be good to have a `log send` to confirm the original error.

**Comment by yogsototh** [comment]
done my log id is 073d3116c73659d4c577161c

**Comment by mmaxim** [comment]
Both service and KBFS side should have improvements here in the next release (happening imminently), so hopefully we'll have a better story here soon.

**Comment by mmaxim** [comment]
Also @yogsototh the problem here is that someone you are trying to chat with reset their account recently, which is a case that is tricky for us and we are actively working on making better.

**Comment by BrandonIngalls** [comment]
Same issue when attempting to start a chat with one person.

Log: **7c3a968b7c3856814003251c**

**Comment by strib** [comment]
@BrandonIngalls I think you need to run `run_keybase` to update your background processes to the new versions.  They're all pretty old.

**Comment by BrandonIngalls** [comment]
> @BrandonIngalls I think you need to run run_keybase to update your background processes to the new versions. They're all pretty old.

That fixed it for me so never mind.
