### ISSUE TITLE
fatal error: out of memory

### ISSUE THREAD

**Issue by algv** [keybase/client#5845]
Sign file: `keybase sign -b -i largefile.in -d -o largefile.in.sig`
Verify file: `keybase verify -i largefile.in.sig -d largefile.in`

File size 1,91 GB (2 054 160 384 bytes)

Verify crash with error log:
```
runtime: out of memory: cannot allocate 536870912-byte block (538968064 in use)
fatal error: out of memory

runtime stack:
runtime.throw(0x1124a8a, 0xd)
        C:/Go/src/runtime/panic.go:566 +0x7f
runtime.largeAlloc(0x1ffffe00, 0x12ae0101, 0x12fbfa80)
        C:/Go/src/runtime/malloc.go:776 +0xb7
runtime.mallocgc.func1()
        C:/Go/src/runtime/malloc.go:669 +0x31
runtime.systemstack(0x12bac200)
        C:/Go/src/runtime/asm_386.s:323 +0x5e
runtime.mstart()
        C:/Go/src/runtime/proc.go:1079

goroutine 1 [running]:
runtime.systemstack_switch()
        C:/Go/src/runtime/asm_386.s:277 fp=0x12fbf9f0 sp=0x12fbf9ec
runtime.mallocgc(0x1ffffe00, 0xfc1660, 0x12fbfa01, 0x44f690)
        C:/Go/src/runtime/malloc.go:670 +0x7b2 fp=0x12fbfa58 sp=0x12fbf9f0
runtime.makeslice(0xfc1660, 0x1ffffe00, 0x0, 0x1ffffe00, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/runtime/slice.go:57 +0xd0 fp=0x12fbfa80 sp=0x12fbfa58
bytes.makeSlice(0x1ffffe00, 0x0, 0x0, 0x0)
        C:/Go/src/bytes/buffer.go:198 +0x67 fp=0x12fbfab0 sp=0x12fbfa80
bytes.(*Buffer).ReadFrom(0x12fbfb50, 0x16f9750, 0x12a259a8, 0xffffe00, 0x0, 0x0, 0x0)
        C:/Go/src/bytes/buffer.go:170 +0xa7 fp=0x12fbfb08 sp=0x12fbfab0
io/ioutil.readAll(0x16f9750, 0x12a259a8, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/io/ioutil/ioutil.go:33 +0x136 fp=0x12fbfbac sp=0x12fbfb08
io/ioutil.ReadFile(0x12bb80c0, 0x32, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/src/io/ioutil/ioutil.go:70 +0x147 fp=0x12fbfc14 sp=0x12fbfbac
github.com/keybase/client/go/client.(*CmdVerify).ParseArgv(0x12b730b0, 0x12b7c480, 0x0, 0x0)
        C:/Jenkins/workspace/windows-installer_0/src/github.com/keybase/client/go/client/cmd_verify.go:89 +0x33e fp=0x12fbfcc0 sp=0x12fbfc14
github.com/keybase/client/go/libcmdline.(*CommandLine).Parse(0x12b87c80, 0x12a04360, 0x6, 0x6, 0x16fefa0, 0x12b730b0, 0x0, 0x0)
        C:/Jenkins/workspace/windows-installer_0/src/github.com/keybase/client/go/libcmdline/cmdline.go:565 +0x166 fp=0x12fbfd1c sp=0x12fbfcc0
main.mainInner(0x12a5d1e0, 0x0, 0x0)
        C:/Jenkins/workspace/windows-installer_0/src/github.com/keybase/client/go/keybase/main.go:105 +0x52d fp=0x12fbff38 sp=0x12fbfd1c
main.main()
        C:/Jenkins/workspace/windows-installer_0/src/github.com/keybase/client/go/keybase/main.go:56 +0x199 fp=0x12fbffa8 sp=0x12fbff38
runtime.main()
        C:/Go/src/runtime/proc.go:183 +0x1ee fp=0x12fbffd0 sp=0x12fbffa8
runtime.goexit()
        C:/Go/src/runtime/asm_386.s:1612 +0x1 fp=0x12fbffd4 sp=0x12fbffd0

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        C:/Go/src/runtime/sigqueue.go:116 +0x11e
os/signal.loop()
        C:/Go/src/os/signal/signal_unix.go:22 +0x1a
created by os/signal.init.1
        C:/Go/src/os/signal/signal_unix.go:28 +0x36

goroutine 7 [select]:
github.com/keybase/client/go/libkb.(*LoginState).requests(0x12b7ff40)
        C:/Jenkins/workspace/windows-installer_0/src/github.com/keybase/client/go/libkb/login_state.go:927 +0x61a
created by github.com/keybase/client/go/libkb.NewLoginState
        C:/Jenkins/workspace/windows-installer_0/src/github.com/keybase/client/go/libkb/login_state.go:111 +0x22b

goroutine 8 [chan receive]:
main.HandleSignals()
        C:/Jenkins/workspace/windows-installer_0/src/github.com/keybase/client/go/keybase/main.go:296 +0x13b
created by main.main
        C:/Jenkins/workspace/windows-installer_0/src/github.com/keybase/client/go/keybase/main.go:55 +0x18d
```
Windows 10 x64
Keybase version:  1.0.18-20170208085140+dc66461

**Comment by maxtaco** [comment]
We should make this cleaner, but I believe you reversed the arguments.  I think you want this:

```
keybase verify -i largefile.in -d largefile.in.sig
```

**Comment by algv** [comment]
Yes, my error. Work nice.

**Comment by maxtaco** [comment]
cool glad that fixed it.  We'll still change the app so it gives a nice error here.
