### ISSUE TITLE
After upgrade to macOS Sierra, keybase doesn't mount anymore

### ISSUE THREAD

**Issue by am-jo-zt** [keybase/client#5934]
I already un- and reinstalled it, but it didn't help.

In the keybase client, following message shows up:

```
KBFS client wasn't found

Error: KBFS client wasn't found at t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:15:31264) at new t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:16:80) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:15:31660) at i (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:15:31588) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:12:14327 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:78:27307 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:56:29476) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:56:29627 at c (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:56:29254) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:56:29586)
```

see my log id: 39f061ad0f42ade826f07f1c

**Comment by tsturzl** [comment]
Also getting this. Keybase doesn't respond at all, even when I fully uninstall(`keybase uninstall`) and reinstall.

**Comment by strib** [comment]
@tsturzl please open a new issue and include a log ID (which you get after running `keybase log send`).  This issue is so old that your problem is probably something else.
