### ISSUE TITLE
Unable to retrieve messages on macOS

### ISSUE THREAD

**Issue by colindean** [keybase/client#6066]
Keybase GUI Version: 1.0.18-20170209165653+17b641d

I opened it and seemed stuck at the "Disconnected" loading screen. I quit and restarted it, greeted with `KextManager failed to load with status: -603946985`

```
Installer: 1.1.46
Privileged Helper: Installed, Bundle Version: 1.0.29, Version: 1.0.29
Updater: Installed, PID: 61305
Service: Installed, Version: 1.0.18-20170209165653+17b641d, PID: 61314
Fuse: Install, Install Error: KextManager failed to load with status: -603946985, Not Installed, Bundle Version: 3.5.2
Mount directory: Unknown, 
KBFS: Unknown, 
CLI: Unknown, 

Log:
Version: 1.1.46
Installables: (
    "Privileged Helper",
    Updater,
    Service,
    Fuse,
    "Mount directory",
    KBFS,
    CLI
)
Install: Privileged Helper
Removing /Library/PrivilegedHelperTools/keybase.Helper
Installing helper tool via SMJobBless
Helper tool installed
Connecting to keybase.Helper (privileged=1)
Connected
Helper version: {
    build = 2;
    version = "1.0.29";
}
Install: Updater
Task: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater --timeout=30s
Task EOF
Completed
Task (err): 2017-02-28T12:51:01.837700 ▶ [DEBU keybase globals.go:353] 001 Created Identify2Cache, max age: 5m0s
2017-02-28T12:51:01.840428 ▶ [DEBU keybase globals.go:356] 002 Created LinkCache, max size: 65536, clean dur: 1m0s
2017-02-28T12:51:01.840612 ▶ [DEBU keybase globals.go:358] 003 Created CardCache, max age: 5m0s
2017-02-28T12:51:01.840640 ▶ [DEBU keybase globals.go:360] 004 made a new full self cache
2017-02-28T12:51:01.840654 ▶ [DEBU keybase globals.go:362] 005 made a new cached UPAK loader (timeout=10m0s)
2017-02-28T12:51:01.845585 ▶ [DEBU keybase ui.go:571] 006 Can't set GPG_TTY; discover failed
2017-02-28T12:51:01.845758 ▶ [DEBU keybase globals.go:336] 007 Keybase CLI 1.0.18-20170209165653+17b641d
2017-02-28T12:51:01.846059 ▶ [DEBU keybase globals.go:336] 008 - Built with go1.7.5
2017-02-28T12:51:01.846085 ▶ [DEBU keybase globals.go:336] 009 - Visit https://keybase.io for more details
2017-02-28T12:51:01.846128 ▶ [DEBU keybase main.go:147] 00a + configureProcesses
2017-02-28T12:51:01.846200 ▶ [DEBU keybase main.go:245] 00b + configureLogging
2017-02-28T12:51:01.846221 ▶ [DEBU keybase main.go:254] 00c Disabling log forwarding
2017-02-28T12:51:01.846233 ▶ [DEBU keybase main.go:247] 00d - configureLogging
2017-02-28T12:51:01.846245 ▶ [DEBU keybase main.go:149] 00e - configureProcesses -> <nil>
2017-02-28T12:51:01.849207 ▶ [DEBU keybase install_osx.go:405] 00f Installing components: [updater]
2017-02-28T12:51:01.851422 ▶ [DEBU keybase install_osx.go:945] 010 Using updater path: /Applications/Keybase.app/Contents/SharedSupport/bin/updater
2017-02-28T12:51:01.863413 ▶ [DEBU keybase launchd.go:141] 011 Output (launchctl remove): 
2017-02-28T12:51:01.863558 ▶ [DEBU keybase launchd.go:146] 012 Nothing to stop (keybase.updater)
2017-02-28T12:51:01.863615 ▶ [DEBU keybase install_osx.go:955] 013 Installing updater service (keybase.updater, timeout=30s)
2017-02-28T12:51:01.864070 ▶ [INFO keybase launchd.go:270] 014 Saving /Users/colin/Library/LaunchAgents/keybase.updater.plist
2017-02-28T12:51:01.864441 ▶ [DEBU keybase util.go:181] 015 + Writing to /Users/colin/Library/LaunchAgents/keybase.updater.plist
2017-02-28T12:51:01.865263 ▶ [DEBU keybase util.go:183] 016 | Temporary file generated: /Users/colin/Library/LaunchAgents/keybase.updater.plist.P2WYZUCKWRSMEHGMOHPQ7ZIZWUZJVTCU
2017-02-28T12:51:01.865422 ▶ [DEBU keybase util.go:202] 017 - Wrote to /Users/colin/Library/LaunchAgents/keybase.updater.plist -> ok
2017-02-28T12:51:01.865502 ▶ [INFO keybase launchd.go:95] 018 Starting keybase.updater
2017-02-28T12:51:01.871196 ▶ [DEBU keybase launchd.go:98] 019 Output (launchctl load): 
2017-02-28T12:51:01.871274 ▶ [INFO keybase launchd.go:176] 01a Waiting for keybase.updater to be loaded...
2017-02-28T12:51:02.382658 ▶ [DEBU keybase launchd.go:111] 01b Service status: &launchd.ServiceStatus{label:"keybase.updater", pid:"61305", lastExitStatus:""}
2017-02-28T12:51:02.896829 ▶ [DEBU keybase out_of_date.go:14] 01c + PrintOutOfDateWarnings
2017-02-28T12:51:02.896980 ▶ [DEBU keybase util.go:402] 01d + GetSocket
2017-02-28T12:51:02.897118 ▶ [DEBU keybase util.go:403] 01e - GetSocket -> ok
2017-02-28T12:51:02.897207 ▶ [DEBU keybase socket.go:73] 01f | empty socket wrapper; need a new one
2017-02-28T12:51:02.898121 ▶ [DEBU keybase socket_nix.go:96] 020 Dialing unix:/Users/colin/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
2017-02-28T12:51:02.899423 ▶ [DEBU keybase socket_nix.go:96] 021 Dialing unix:/Users/colin/Library/Caches/Keybase/keybased.sock
2017-02-28T12:51:02.899761 ▶ [DEBU keybase socket.go:88] 022 | DialSocket -> ERROR: There were multiple errors: dial unix /Users/colin/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/colin/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
2017-02-28T12:51:02.899803 ▶ [DEBU keybase out_of_date.go:19] 023 Ignoring error in printOutOfDateWarnings: There were multiple errors: dial unix /Users/colin/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/colin/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
2017-02-28T12:51:02.899902 ▶ [DEBU keybase out_of_date.go:20] 024 - PrintOutOfDateWarnings
2017-02-28T12:51:03.002136 ▶ [DEBU keybase globals.go:424] 025 Calling shutdown first time through
2017-02-28T12:51:03.002846 ▶ [DEBU keybase login_state.go:1045] 026 + Account "LoginState - Shutdown"
2017-02-28T12:51:03.002962 ▶ [DEBU keybase login_state.go:958] 027 - LoginState: Leaving request loop
2017-02-28T12:51:03.002984 ▶ [DEBU keybase login_state.go:1047] 028 - Account "LoginState - Shutdown"
2017-02-28T12:51:03.003085 ▶ [DEBU keybase globals.go:481] 029 exiting shutdown code=0; err=<nil>

Task (out): {
  "componentResults": [
    {
      "name": "updater",
      "status": {
        "code": 0,
        "name": "OK",
        "desc": "OK",
        "fields": null
      }
    }
  ],
  "status": {
    "code": 0,
    "name": "OK",
    "desc": "OK",
    "fields": null
  },
  "fatal": false
}

Checking launchd status for updater
Task: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase --log-format=file launchd status --format=json updater
Task EOF
Completed
Task (err): 
Task (out): {
  "version": "",
  "label": "keybase.updater",
  "pid": "61305",
  "lastExitStatus": "",
  "bundleVersion": "",
  "installStatus": 4,
  "installAction": 1,
  "status": {
    "code": 0,
    "name": "OK",
    "desc": "OK",
    "fields": null
  }
}

Install: Service
Task: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=service --timeout=30s
Task EOF
Completed
Task (err): 2017-02-28T12:51:03.561875 ▶ [DEBU keybase globals.go:353] 001 Created Identify2Cache, max age: 5m0s
2017-02-28T12:51:03.561946 ▶ [DEBU keybase globals.go:356] 002 Created LinkCache, max size: 65536, clean dur: 1m0s
2017-02-28T12:51:03.562006 ▶ [DEBU keybase globals.go:358] 003 Created CardCache, max age: 5m0s
2017-02-28T12:51:03.562031 ▶ [DEBU keybase globals.go:360] 004 made a new full self cache
2017-02-28T12:51:03.562046 ▶ [DEBU keybase globals.go:362] 005 made a new cached UPAK loader (timeout=10m0s)
2017-02-28T12:51:03.563632 ▶ [DEBU keybase ui.go:571] 006 Can't set GPG_TTY; discover failed
2017-02-28T12:51:03.563662 ▶ [DEBU keybase globals.go:336] 007 Keybase CLI 1.0.18-20170209165653+17b641d
2017-02-28T12:51:03.563675 ▶ [DEBU keybase globals.go:336] 008 - Built with go1.7.5
2017-02-28T12:51:03.563684 ▶ [DEBU keybase globals.go:336] 009 - Visit https://keybase.io for more details
2017-02-28T12:51:03.563697 ▶ [DEBU keybase main.go:147] 00a + configureProcesses
2017-02-28T12:51:03.563725 ▶ [DEBU keybase main.go:245] 00b + configureLogging
2017-02-28T12:51:03.563738 ▶ [DEBU keybase main.go:254] 00c Disabling log forwarding
2017-02-28T12:51:03.563745 ▶ [DEBU keybase main.go:247] 00d - configureLogging
2017-02-28T12:51:03.563753 ▶ [DEBU keybase main.go:149] 00e - configureProcesses -> <nil>
2017-02-28T12:51:03.563845 ▶ [DEBU keybase install_osx.go:405] 00f Installing components: [service]
2017-02-28T12:51:03.564207 ▶ [DEBU keybase install_osx.go:512] 010 Using binPath: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase
2017-02-28T12:51:03.568120 ▶ [DEBU keybase launchd.go:141] 011 Output (launchctl remove): 
2017-02-28T12:51:03.568164 ▶ [DEBU keybase launchd.go:146] 012 Nothing to stop (keybase.service)
2017-02-28T12:51:03.572298 ▶ [DEBU keybase launchd.go:141] 013 Output (launchctl remove): 
2017-02-28T12:51:03.572356 ▶ [DEBU keybase launchd.go:146] 014 Nothing to stop (homebrew.mxcl.keybase)
2017-02-28T12:51:03.572367 ▶ [DEBU keybase install_osx.go:521] 015 Installing service (keybase.service, timeout=30s)
2017-02-28T12:51:03.572509 ▶ [INFO keybase launchd.go:270] 016 Saving /Users/colin/Library/LaunchAgents/keybase.service.plist
2017-02-28T12:51:03.572549 ▶ [DEBU keybase util.go:181] 017 + Writing to /Users/colin/Library/LaunchAgents/keybase.service.plist
2017-02-28T12:51:03.573011 ▶ [DEBU keybase util.go:183] 018 | Temporary file generated: /Users/colin/Library/LaunchAgents/keybase.service.plist.VVNWBT4RG5XIAXLKJECCSLR7SB7VOD2P
2017-02-28T12:51:03.573195 ▶ [DEBU keybase util.go:202] 019 - Wrote to /Users/colin/Library/LaunchAgents/keybase.service.plist -> ok
2017-02-28T12:51:03.573251 ▶ [INFO keybase launchd.go:95] 01a Starting keybase.service
2017-02-28T12:51:03.577949 ▶ [DEBU keybase launchd.go:98] 01b Output (launchctl load): 
2017-02-28T12:51:03.578022 ▶ [INFO keybase launchd.go:176] 01c Waiting for keybase.service to be loaded...
2017-02-28T12:51:04.092954 ▶ [DEBU keybase launchd.go:111] 01d Service status: &launchd.ServiceStatus{label:"keybase.service", pid:"61314", lastExitStatus:""}
2017-02-28T12:51:04.609366 ▶ [DEBU keybase service_info.go:92] 01e Looking for service info file (timeout=30s)
2017-02-28T12:51:05.013938 ▶ [DEBU keybase service_info.go:104] 01f Found service info: libkb.ServiceInfo{Version:"1.0.18-20170209165653+17b641d", Label:"keybase.service", Pid:61314}
2017-02-28T12:51:05.014238 ▶ [DEBU keybase out_of_date.go:14] 020 + PrintOutOfDateWarnings
2017-02-28T12:51:05.014271 ▶ [DEBU keybase util.go:402] 021 + GetSocket
2017-02-28T12:51:05.014289 ▶ [DEBU keybase util.go:403] 022 - GetSocket -> ok
2017-02-28T12:51:05.014307 ▶ [DEBU keybase socket.go:73] 023 | empty socket wrapper; need a new one
2017-02-28T12:51:05.014330 ▶ [DEBU keybase socket_nix.go:96] 024 Dialing unix:/Users/colin/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
2017-02-28T12:51:05.014442 ▶ [DEBU keybase socket.go:88] 025 | DialSocket -> ok
2017-02-28T12:51:05.015247 ▶ [DEBU keybase out_of_date.go:28] 026 Got OutOfDateInfo: keybase1.OutOfDateInfo{UpgradeTo:"", UpgradeURI:"", CustomMessage:"", CriticalClockSkew:0}
2017-02-28T12:51:05.015282 ▶ [DEBU keybase out_of_date.go:44] 027 - PrintOutOfDateWarnings
2017-02-28T12:51:05.116179 ▶ [DEBU keybase globals.go:424] 028 Calling shutdown first time through
2017-02-28T12:51:05.116252 ▶ [DEBU keybase login_state.go:1045] 029 + Account "LoginState - Shutdown"
2017-02-28T12:51:05.116359 ▶ [DEBU keybase login_state.go:958] 02a - LoginState: Leaving request loop
2017-02-28T12:51:05.116383 ▶ [DEBU keybase login_state.go:1047] 02b - Account "LoginState - Shutdown"
2017-02-28T12:51:05.116481 ▶ [DEBU keybase globals.go:481] 02c exiting shutdown code=0; err=<nil>

Task (out): {
  "componentResults": [
    {
      "name": "service",
      "status": {
        "code": 0,
        "name": "OK",
        "desc": "OK",
        "fields": null
      }
    }
  ],
  "status": {
    "code": 0,
    "name": "OK",
    "desc": "OK",
    "fields": null
  },
  "fatal": false
}

Checking launchd status for service
Task: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase --log-format=file launchd status --format=json service
Task EOF
Completed
Task (err): 
Task (out): {
  "version": "1.0.18-20170209165653+17b641d",
  "label": "keybase.service",
  "pid": "61314",
  "lastExitStatus": "",
  "bundleVersion": "1.0.18-20170209165653+17b641d",
  "installStatus": 4,
  "installAction": 1,
  "status": {
    "code": 0,
    "name": "OK",
    "desc": "OK",
    "fields": null
  }
}

Install: Fuse
Task: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file fuse status --bundle-version=3.5.2
Task EOF
Completed
Task (err): 2017-02-28T12:51:06.128065 ▶ [DEBU keybase globals.go:353] 001 Created Identify2Cache, max age: 5m0s
2017-02-28T12:51:06.128163 ▶ [DEBU keybase globals.go:356] 002 Created LinkCache, max size: 65536, clean dur: 1m0s
2017-02-28T12:51:06.128192 ▶ [DEBU keybase globals.go:358] 003 Created CardCache, max age: 5m0s
2017-02-28T12:51:06.128206 ▶ [DEBU keybase globals.go:360] 004 made a new full self cache
2017-02-28T12:51:06.128218 ▶ [DEBU keybase globals.go:362] 005 made a new cached UPAK loader (timeout=10m0s)
2017-02-28T12:51:06.130335 ▶ [DEBU keybase ui.go:571] 006 Can't set GPG_TTY; discover failed
2017-02-28T12:51:06.130409 ▶ [DEBU keybase globals.go:336] 007 Keybase CLI 1.0.18-20170209165653+17b641d
2017-02-28T12:51:06.130431 ▶ [DEBU keybase globals.go:336] 008 - Built with go1.7.5
2017-02-28T12:51:06.130447 ▶ [DEBU keybase globals.go:336] 009 - Visit https://keybase.io for more details
2017-02-28T12:51:06.130473 ▶ [DEBU keybase main.go:147] 00a + configureProcesses
2017-02-28T12:51:06.130494 ▶ [DEBU keybase main.go:245] 00b + configureLogging
2017-02-28T12:51:06.130509 ▶ [DEBU keybase main.go:254] 00c Disabling log forwarding
2017-02-28T12:51:06.130521 ▶ [DEBU keybase main.go:247] 00d - configureLogging
2017-02-28T12:51:06.130532 ▶ [DEBU keybase main.go:149] 00e - configureProcesses -> <nil>
2017-02-28T12:51:06.131316 ▶ [DEBU keybase out_of_date.go:14] 00f + PrintOutOfDateWarnings
2017-02-28T12:51:06.131388 ▶ [DEBU keybase util.go:402] 010 + GetSocket
2017-02-28T12:51:06.131419 ▶ [DEBU keybase util.go:403] 011 - GetSocket -> ok
2017-02-28T12:51:06.131437 ▶ [DEBU keybase socket.go:73] 012 | empty socket wrapper; need a new one
2017-02-28T12:51:06.131455 ▶ [DEBU keybase socket_nix.go:96] 013 Dialing unix:/Users/colin/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
2017-02-28T12:51:06.131600 ▶ [DEBU keybase socket.go:88] 014 | DialSocket -> ok
2017-02-28T12:51:06.132539 ▶ [DEBU keybase out_of_date.go:28] 015 Got OutOfDateInfo: keybase1.OutOfDateInfo{UpgradeTo:"", UpgradeURI:"", CustomMessage:"", CriticalClockSkew:0}
2017-02-28T12:51:06.132585 ▶ [DEBU keybase out_of_date.go:44] 016 - PrintOutOfDateWarnings
2017-02-28T12:51:06.236395 ▶ [DEBU keybase globals.go:424] 017 Calling shutdown first time through
2017-02-28T12:51:06.236481 ▶ [DEBU keybase login_state.go:1045] 018 + Account "LoginState - Shutdown"
2017-02-28T12:51:06.236572 ▶ [DEBU keybase login_state.go:958] 019 - LoginState: Leaving request loop
2017-02-28T12:51:06.236624 ▶ [DEBU keybase login_state.go:1047] 01a - Account "LoginState - Shutdown"
2017-02-28T12:51:06.236676 ▶ [DEBU keybase globals.go:481] 01b exiting shutdown code=0; err=<nil>

Task (out): {
  "version": "",
  "bundleVersion": "3.5.2",
  "kextID": "",
  "path": "",
  "kextStarted": false,
  "installStatus": 2,
  "installAction": 4,
  "mountInfos": null,
  "status": {
    "code": 0,
    "name": "",
    "desc": "",
    "fields": null
  }
}

Helper: kextInstall({
    destination = "/Library/Filesystems/kbfuse.fs";
    kextID = "com.github.kbfuse.filesystems.kbfuse";
    kextPath = "/Library/Filesystems/kbfuse.fs/Contents/Extensions/10.10/kbfuse.kext";
    source = "/Applications/Keybase.app/Contents/Resources/KeybaseInstaller.app/Contents/Resources/kbfuse.bundle";
})
Install complete
Privileged Helper: Installed, Bundle Version: 1.0.29
Version: 1.0.29
Updater: Installed, PID: 61305
Service: Installed, Version: 1.0.18-20170209165653+17b641d
PID: 61314
Fuse: Install Error: KextManager failed to load with status: -603946985
Not Installed, Bundle Version: 3.5.2
```

Now that I'm back in the app, I cannot open chat - it said something _once_ about not being able to load the filesystem driver. It yields no further information.

So, I quit from the menu bar again and started it again. Now, it's just sitting at the Loading screen. If I use the menu bar applet to look at chat, it pops up and has the error I saw:

```
Error: error unboxing chat message: KBFS client wasn't found at t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:15:31264) at new t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:16:80) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:15:31660) at i (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:15:31588) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:12:14327 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:78:27307 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:56:29476) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:56:29627 at c (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:56:29254) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:56:29586)
```

So I decided to reinstall. I quit it and deleted `/Applications/Keybase.app` and executed `brew cask install keybase` at the command line. I receive the same KextManager failure. Removed that one and tried downloading from Keybase.io. I put that app in place and started it.

Now I've got nothing in chat except a blinking `securing...`. Nothing happens when I try to open a folder.

```
$ cd /keybase/
-bash: cd: /keybase/: Permission denied
```

I'm now stuck and I've got some messages in my chat queue, according to an email I received that started me on this journey.

**Comment by colindean** [comment]
Folders are not working.

**Comment by maxtaco** [comment]
S3 outage is affecting keybase

**Comment by colindean** [comment]
TIL there is an S3 outage.
