### ISSUE TITLE
Chat doesn't work in the macOS app

### ISSUE THREAD

**Issue by djpeter2** [keybase/client#6339]
Keybase GUI Version: 1.0.20-20170317000044+73c5db6

Error: Unknown RPC Error at t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:17:31890) at new t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:18:701) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:18:277) at i (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:18:205) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:12:23905 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:76:27307 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:42:11313) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:42:11464 at c (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:42:11091) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:42:11423)

**Comment by maxtaco** [comment]
Can you do a `keybase log send`? Thanks

cc: @mmaxim  and @chrisnojima

**Comment by djpeter2** [comment]
I think I have:

log ID 2f3f603b32ff0452d66b8e1c

https://github.com/keybase/client/issues/new?body=[write%20something%20useful%20and%20descriptive%20here]%0A%0Amy%20log%20id:%202f3f603b32ff0452d66b8e1c

Daniel Peters
Product Development Chemist
+1 888 266 3916 ext 412

**Comment by mmaxim** [comment]
@strib I see KBFS panicing in these logs, which I think is hosing chat for this guy. 

```
104839 panic(0x4bc5de0, 0xc420014060)
104840 /usr/local/Cellar/go/1.7.5/libexec/src/runtime/panic.go:500 +0x1a1
104841 github.com/keybase/kbfs/libkbfs.(*RootMetadata).Revision(0x0, 0x4e2a088)
104842 /Users/test/go/src/github.com/keybase/kbfs/libkbfs/root_metadata.go:634 +0x22
104843 github.com/keybase/kbfs/libkbfs.(*folderBranchOps).SetInitialHeadFromServer.func2.1(0xc42023ac00, 0xc420531e50, 0x68583f0, 0xc427ab3d00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
104844 /Users/test/go/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:1528 +0xa3
104845 github.com/keybase/kbfs/libkbfs.(*folderBranchOps).SetInitialHeadFromServer.func2(0x0, 0x0)
104846 /Users/test/go/src/github.com/keybase/kbfs/libkbfs/folder_branch_ops.go:1529 +0x993
104847 github.com/keybase/kbfs/libkbfs.runUnlessCanceled.func1(0xc427aeef60, 0xc427aabe30)
104848 /Users/test/go/src/github.com/keybase/kbfs/libkbfs/util.go:25 +0x27
104849 created by github.com/keybase/kbfs/libkbfs.runUnlessCanceled
104850 /Users/test/go/src/github.com/keybase/kbfs/libkbfs/util.go:26 +0x7c
```

**Comment by mmaxim** [comment]
This is what it looks like from chat's side:

```
++Chat: - TlfHandler: CryptKeys(tlf=djpeter2,katepeters,mode=CHAT_GUI,handler=false) -> ERROR: EOF (149.396843ms) [tags:chat-trace=vJEL0pmNGx40]
```

**Comment by strib** [comment]
Yes, this is a KBFS bug.  It seems like this new folder was created locally in the journal, and it was never flushed to the server.  It's failing on squashing the journal, because of a bug where it doesn't work when there hasn't been anything flushed to the server yet.

We will fix the bug.  You can work around this in the meantime with the steps below.  *NOTE:* that this will erase any data you've written into the shared folder so far, so if it's important, you should back it up somewhere to your local drive before you run these steps.

# Completely shutdown all Keybase processes.
# run this command: `rm -rf /Users/danielpeters/Library/Application Support/Keybase/kbfs_journal/v1/0120ab7ef92c69200f0fcaa527b0e62b7c17-0d4eb7ee44fbc71d`
# Restart Keybase

Sorry for the inconvenience.  Please let us know if this fixes things for you.

**Comment by strib** [comment]
(Note that I edited the above command to include quotes around the pathname, since it has a space in it.)

**Comment by mmaxim** [comment]
This won't affect all new convos will it?

**Comment by mmaxim** [comment]
I just created a new one and it worked, so I guess this was a weird case?

**Comment by strib** [comment]
It was only for that particular conversation, because the folder was in a broken state locally.  Basically it could happen for any new folder that's initialized by writing a bunch of stuff into it via KBFS at once, before the journal has a chance to flush for the first time.
