### ISSUE TITLE
client hang opening old chat log

### ISSUE THREAD

**Issue by bboutkov** [keybase/client#6459]
Recently my client was stuck 'digging ancient messages' for a chat I was participating in with another user. This problem persisted a while yet I was able to send messages at the time, and even see some of the responses using a client on a different computer. After being sent an image in the chat yesterday, this mornings client refuses to even show the chat with said user and just displays the api network error below.

Error: API network error: Get https://api.keybase.io/_/api/1.0/user/lookup.json?fields=profile&usernames=my_username_here%2Cother_username_here: net/http: request canceled (Client.Timeout exceeded while awaiting headers) at t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:17:31890) at new t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:18:701) at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:18:277) at i (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:18:205) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:14:16466 at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:76:27307 at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:42:11313) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:42:11464 at c (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:42:11091) at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:42:11423)

my log id: 5d999037a0158674bec4841c

**Comment by bboutkov** [comment]
Havent seen this issue for a long time now so closing as its likely outdated.
