### ISSUE TITLE
Unknown RPC Error

### ISSUE THREAD

**Issue by n8kowald** [keybase/client#6796]
I get an "Unknown RPC Error" when I try to start a chat with someone I just followed.

my log id: 50672e123f55fdd15813531c

Following supported by the OS X application:

`Error: Unknown RPC Error at t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:18:6316) at new t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:18:7136) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:18:6712) at i (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:18:6640) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:14:20529 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:76:27386 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:42:19061) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:42:19212 at c (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:42:18839) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:42:19171)`

**Comment by maxtaco** [comment]
Thanks for the report. CC: @chrisnojima

**Comment by zero4byss** [comment]
I am having this same issue, it worked before, but when I reinstalled, it wouldn't connect to chat.
here is the code it gives me:
`Error: connection auth error: msg: failed to check logged in status shouldRetry: false at t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:20:12982) at new t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:20:13802) at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:20:13378) at i (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:20:13306) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:15:20518 at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:80:27386 at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:46:18700) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:46:18851 at c (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:46:18478) at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:46:18810)`
