### ISSUE TITLE
Error when Logging in "Unknown RPC Error"

### ISSUE THREAD

**Issue by robsmallridge** [keybase/client#6946]
[write something useful and descriptive here]

my log id: 1a496ae4117420fa5e51f81c

**Comment by swalladge** [comment]
I had the same issue. The new device was created successfully (can see it in the devices view from desktop), but the app still acts as though it hasn't logged in and wants me set it up again. This was connecting the phone via scanning the qr code from desktop.

**Comment by maxtaco** [comment]
Thanks for the report

Cc @cjb and @chrisnojima

**Comment by stubbetje** [comment]
Trying the keybase application for the first time (on OSX) and also getting the "Unknown RPC Error".

**Comment by maxtaco** [comment]
Cc: @mmaxim

**Comment by maxtaco** [comment]
@chrisnojima i think we should make this error more descriptive so we known which RPC is causing the problem, since I think we're catching a number of different bugs under this same issue.

**Comment by chrisnojima** [comment]
investigating, tnx

**Comment by patrickxb** [comment]
@robsmallridge the problem is that you have a GPG key associated with your account, but it is not on the device that you are provisioning:

    460 2017-05-11T15:10:49.253762+01:00 - [DEBU keybase engine.go:67] 1cc - RunEngine(loginProvision) -> ERROR: No private GPG keys found on this device that match account PGP keys 2D57 7749 BD68 E957 5358 6F5B F01F A2B3 E609 1458

Do you still have that key?  If so, can you install it on the device and try again?

**Comment by patrickxb** [comment]
@swalladge and @stubbetje could you do `keybase log send` so we can investigate?

As @maxtaco said, it's hard to tell from the error message what the issue is, and a log would be very helpful.

Thanks!

**Comment by patrickxb** [comment]
@chrisnojima the unknown error in @robsmallridge case is SCKeyNoMatchingGPG.  It is fully exported, including the fingerprints, so should be available to the UI without service changes.

**Comment by swalladge** [comment]
@patrickxb unfortunately this was on an android phone, and I had cleared the app data before trying to login again... Don't know if the debug logs will have survived, but sending anyway. :\

I do have a gpg key associated with my account, but don't keep the private key saved in keybase. Perhaps it could be related to @robsmallridge's error?

**Comment by stubbetje** [comment]
@patrickxb I have executed the `keybase log send` command as requested.
My log id: `994162204e240fa782ff731c` and `6b1043522de077b6a534861c`

(first log is without keybase application running, second log is with keybase application running)

**Comment by patrickxb** [comment]
@swalladge yes, you are probably in the same boat as @robsmallridge then.  Sorry for the issue, we are working on handling that error better, but what you will then see is that you need to provision a desktop device with that GPG key before you will be able to provision your android phone.

**Comment by patrickxb** [comment]
@stubbetje do you have access to PGP key 1D400EBE161BA202?  If so, if you can get it onto that desktop device, you will be able to provision with it.

**Comment by swalladge** [comment]
@patrickxb what if I don't want to store my private gpg keys in keybase? Currently (i think) I just have my public key stored in keybase, and I manage private keys myself. I'm not sure what you mean by provisioning a desktop device with the gpg key?

**Comment by jzila** [comment]
@swalladge: you shouldn't need to store the keys in Keybase. It should be enough for the `gpg` application on the device you're trying to provision to have the key loaded. Keybase provisioning can then call the appropriate `gpg` commands to do the crypto it needs to provision (without loading the private key into Keybase itself).

**Comment by boardwalk** [comment]
I'm having a similar issue with 'Unknown RPC Error' upon trying to log in (after entering my password). I do have a PGP key and was poked on the webpage to install the client. I have gpg and the (private) key on this device. Happy to help debug this any way I can. Log id: f36828c20413d652bcec821c

**Comment by jzila** [comment]
cc @patrickxb: any ideas re boardwalk's issue?

**Comment by patrickxb** [comment]
@boardwalk the service ran this command:

    /usr/local/bin/gpg2 --no-tty --with-colons --fingerprint -K

it was looking for PGP key 5833 8E74 63AA 4CD8 2BE8 16BF 03F8 5694 D880 7521 and didn't find it in the output of that command.

Do you have that key on this device?  Since it is associated with your account, you will need to use it to provision your first device.  Or if you have lost access to it, you can reset your account and start from scratch.

**Comment by boardwalk** [comment]
That makes sense, that that's just the PGP key I believe keybase generated when I first signed up. I definitely don't have that and I'll have to reset. Thanks for your help.

**Comment by aramboi** [comment]
I got this error in the Settings screen, after I changed my password and restarted the Keybase MacOS app:
```
Error: Unknown RPC Error
 at t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:20:15838)
 at new t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:20:16658)
 at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:20:16234)
 at i (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:20:16162)
 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:15:20518 
 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:80:27386 
 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:46:18742)
 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:46:18893
 at c (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:46:18520)
 at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:46:18852)
```

Got rid of it by doing a `keybase login` in the terminal. Hope this helps.
