### ISSUE TITLE
Could not load Completely when I start the App.

### ISSUE THREAD

**Issue by kephny** [keybase/client#7188]
Keybase GUI Version: 1.0.22-20170502110012+a3c4856

```
Error: 

Error: API network error: doRetry failed, attempts: 1, timeout 7.5s, last err: context deadline exceeded at t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:18:8047) at new t (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:18:8867) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:18:8443) at i (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:18:8371) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:14:19678 at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:76:27386 at e.t.Deferrals.e._call (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:42:18846) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:42:18997 at c (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:42:18624) at e.t.Deferrals.e._fulfill (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:42:18956)
```

**Comment by Jb1230** [comment]
Similar issue:


Installer: 1.1.55
Privileged Helper: Installed, Bundle Version: 1.0.29, Version: 1.0.29
Updater: Unknown, Install Error: open /Users/default/Library/LaunchAgents/keybase.updater.plist.YGGYK3W4DUUL722ORVPVLZB572R5W5DE: permission denied (updater)
Service: Unknown, 
Fuse: Unknown, 
Mount directory: Unknown, 
KBFS: Unknown, 
CLI: Unknown, 
KBNM: Unknown, 

Log:
Version: 1.1.55
Installables: (
    "Privileged Helper",
    Updater,
    Service,
    Fuse,
    "Mount directory",
    KBFS,
    CLI,
    KBNM
)
Install: Privileged Helper
Connecting to keybase.Helper (privileged=1)
Connected
Helper version: {
    build = 2;
    version = "1.0.29";
}
Helper version: {
    build = 2;
    version = "1.0.29";
}
Install: Updater
Task: /Applications/Keybase.app/Contents/SharedSupport/bin/keybase -d --log-format=file install --format=json --components=updater --timeout=30s
Task EOF
Completed
Task (err): 2017-05-30T16:44:28.826990-07:00 ▶ [DEBU keybase globals.go:383] 001 Created Identify2Cache, max age: 5m0s
2017-05-30T16:44:28.827165-07:00 ▶ [DEBU keybase globals.go:386] 002 Created LinkCache, max size: 65536, clean dur: 1m0s
2017-05-30T16:44:28.827195-07:00 ▶ [DEBU keybase globals.go:388] 003 Created CardCache, max age: 5m0s
2017-05-30T16:44:28.827213-07:00 ▶ [DEBU keybase globals.go:390] 004 made a new full self cache
2017-05-30T16:44:28.827227-07:00 ▶ [DEBU keybase globals.go:392] 005 made a new cached UPAK loader (timeout=10m0s)
2017-05-30T16:44:28.829824-07:00 ▶ [DEBU keybase ui.go:580] 006 Can't set GPG_TTY; discover failed
2017-05-30T16:44:28.829900-07:00 ▶ [DEBU keybase globals.go:366] 007 Keybase CLI 1.0.23-20170522181119+8a8aea0
2017-05-30T16:44:28.829919-07:00 ▶ [DEBU keybase globals.go:366] 008 - Built with go1.8.1
2017-05-30T16:44:28.829931-07:00 ▶ [DEBU keybase globals.go:366] 009 - Visit https://keybase.io for more details
2017-05-30T16:44:28.829946-07:00 ▶ [DEBU keybase main.go:156] 00a + configureProcesses
2017-05-30T16:44:28.829975-07:00 ▶ [DEBU keybase main.go:254] 00b + configureLogging
2017-05-30T16:44:28.829990-07:00 ▶ [DEBU keybase main.go:263] 00c Disabling log forwarding
2017-05-30T16:44:28.830002-07:00 ▶ [DEBU keybase main.go:256] 00d - configureLogging
2017-05-30T16:44:28.830014-07:00 ▶ [DEBU keybase main.go:158] 00e - configureProcesses -> <nil>
2017-05-30T16:44:28.830385-07:00 ▶ [DEBU keybase install_darwin.go:405] 00f Installing components: [updater]
2017-05-30T16:44:28.830526-07:00 ▶ [DEBU keybase install_darwin.go:1098] 010 Using updater path: /Applications/Keybase.app/Contents/SharedSupport/bin/updater
2017-05-30T16:44:28.839706-07:00 ▶ [DEBU keybase launchd.go:141] 011 Output (launchctl remove): 
2017-05-30T16:44:28.839780-07:00 ▶ [DEBU keybase launchd.go:146] 012 Nothing to stop (keybase.updater)
2017-05-30T16:44:28.839814-07:00 ▶ [DEBU keybase install_darwin.go:1108] 013 Installing updater service (keybase.updater, timeout=30s)
2017-05-30T16:44:28.839980-07:00 ▶ [INFO keybase launchd.go:270] 014 Saving /Users/default/Library/LaunchAgents/keybase.updater.plist
2017-05-30T16:44:28.840018-07:00 ▶ [DEBU keybase util.go:181] 015 + Writing to /Users/default/Library/LaunchAgents/keybase.updater.plist
2017-05-30T16:44:28.840527-07:00 ▶ [DEBU keybase util.go:183] 016 | Temporary file generated: /Users/default/Library/LaunchAgents/keybase.updater.plist.YGGYK3W4DUUL722ORVPVLZB572R5W5DE
2017-05-30T16:44:28.840550-07:00 ▶ [ERRO keybase standard.go:230] 017 Error installing updater service: open /Users/default/Library/LaunchAgents/keybase.updater.plist.YGGYK3W4DUUL722ORVPVLZB572R5W5DE: permission denied
2017-05-30T16:44:28.840588-07:00 ▶ [ERRO keybase standard.go:230] 018 Error installing updater: open /Users/default/Library/LaunchAgents/keybase.updater.plist.YGGYK3W4DUUL722ORVPVLZB572R5W5DE: permission denied
2017-05-30T16:44:28.840826-07:00 ▶ [DEBU keybase out_of_date.go:14] 019 + PrintOutOfDateWarnings
2017-05-30T16:44:28.840862-07:00 ▶ [DEBU keybase util.go:414] 01a + GetSocket
2017-05-30T16:44:28.840895-07:00 ▶ [DEBU keybase util.go:415] 01b - GetSocket -> ok
2017-05-30T16:44:28.840914-07:00 ▶ [DEBU keybase socket.go:73] 01c | empty socket wrapper; need a new one
2017-05-30T16:44:28.840943-07:00 ▶ [DEBU keybase socket_nix.go:96] 01d Dialing unix:/Users/default/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock
2017-05-30T16:44:28.841207-07:00 ▶ [DEBU keybase socket_nix.go:96] 01e Dialing unix:/Users/default/Library/Caches/Keybase/keybased.sock
2017-05-30T16:44:28.841312-07:00 ▶ [DEBU keybase socket.go:88] 01f | DialSocket -> ERROR: There were multiple errors: dial unix /Users/default/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/default/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
2017-05-30T16:44:28.841336-07:00 ▶ [DEBU keybase out_of_date.go:19] 020 Ignoring error in printOutOfDateWarnings: There were multiple errors: dial unix /Users/default/Library/Group Containers/keybase/Library/Caches/Keybase/keybased.sock: connect: no such file or directory; dial unix /Users/default/Library/Caches/Keybase/keybased.sock: connect: no such file or directory
2017-05-30T16:44:28.841364-07:00 ▶ [DEBU keybase out_of_date.go:20] 021 - PrintOutOfDateWarnings
2017-05-30T16:44:28.943742-07:00 ▶ [DEBU keybase globals.go:464] 022 Calling shutdown first time through
2017-05-30T16:44:28.943832-07:00 ▶ [DEBU keybase login_state.go:1070] 023 + Account "LoginState - Shutdown"
2017-05-30T16:44:28.943921-07:00 ▶ [DEBU keybase login_state.go:983] 024 - LoginState: Leaving request loop
2017-05-30T16:44:28.943938-07:00 ▶ [DEBU keybase login_state.go:1072] 025 - Account "LoginState - Shutdown"
2017-05-30T16:44:28.944012-07:00 ▶ [DEBU keybase globals.go:518] 026 exiting shutdown code=0; err=<nil>

Task (out): {
  "componentResults": [
    {
      "name": "updater",
      "status": {
        "code": 1804,
        "name": "ERROR",
        "desc": "open /Users/default/Library/LaunchAgents/keybase.updater.plist.YGGYK3W4DUUL722ORVPVLZB572R5W5DE: permission denied",
        "fields": null
      }
    }
  ],
  "status": {
    "code": 1804,
    "name": "ERROR",
    "desc": "open /Users/default/Library/LaunchAgents/keybase.updater.plist.YGGYK3W4DUUL722ORVPVLZB572R5W5DE: permission denied (updater)",
    "fields": null
  },
  "fatal": false
}

Install complete
Privileged Helper: Installed, Bundle Version: 1.0.29
Version: 1.0.29
Updater: Install Error: open /Users/default/Library/LaunchAgents/keybase.updater.plist.YGGYK3W4DUUL722ORVPVLZB572R5W5DE: permission denied (updater)

**Comment by maxtaco** [comment]
cc: @gabriel 

@Jb1230 it's some sort of permission problem

**Comment by gabriel** [comment]
@ghost It might be that your `~/Library/LaunchAgents` directory has the wrong permissions.

What is the output of:

```sh
ls -al ~/Library | grep LaunchAgents
```

**Comment by gabriel** [comment]
Can you try with latest version from https://keybase.io/docs/the_app/install_macos and re-open if the issue still exists?
