### ISSUE TITLE
getting 'cannot read property 'response' of undefined...

### ISSUE THREAD

**Issue by peterhallen** [keybase/client#7189]
log id = b64c107b30225b2ff59f381c
keybase version 1.0.24-20170526160108+83e1e9f
LinuxMint 18
4.8.0-34-generic #36~16.04.1-Ubuntu

TypeError: Cannot read property 'response' of undefined at 

> file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:136:11373 at o (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:114:31370) at i._invoke (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:115:448) at i.e.(anonymous function) [as next] (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:114:31549) at y (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:43:3496) at Object.n [as cont] (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:43:4237) at b (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:43:4055) at Object.e.cont (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:43:2472) at y (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:43:3541) at n (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:43:4237)

**Comment by wolfgang42** [comment]
I'm not sure if this is the same issue you're having, but I'm also getting a similar error message. I just upgraded my keybase client from something ancient, and now have a GUI. However, the state of the GUI seems to be a bit confused by the fact that I was logged in on the CLI when I upgraded; I have to poke it a bit before it takes me to the login screen, and when I type my passphrase I get this error in a  bar at the top of the screen. I've submitted the logs with ID `50040806fd4a5c866a21cd1c`.

**Comment by jzila** [comment]
@patrickxb (for peterhallen's log): 
```
100621 2017-05-29T10:47:15.011963-04:00 ▶ [DEBU keybase keyring.go:196] 2d2 - GetSecretKeyLocked() -> ok
100622 2017-05-29T10:47:15.011984-04:00 ▶ [DEBU keybase skb.go:463] 2d3 | unlockSecretKeyFromSecretRetriever -> ERROR: No secret found for user
100623 2017-05-29T10:47:15.011995-04:00 ▶ [DEBU keybase skb.go:495] 2d4 | No 3Sec or PassphraseStream in UnlockNoPrompt
100624 2017-05-29T10:47:15.012010-04:00 ▶ [DEBU keybase keyring.go:324] 2d5 - GetSecretKeyWithoutPrompt() -> ERROR: unlock not possible
100625 2017-05-29T10:47:15.012021-04:00 ▶ [DEBU keybase login_state.go:517] 2d6 - pubkeyLoginHelper() -> ERROR: unlock not possible
100626 2017-05-29T10:47:15.012029-04:00 ▶ [DEBU keybase login_state.go:646] 2d7 | Public key login failed, falling back: unlock not possible
100627 2017-05-29T10:47:15.012040-04:00 ▶ [DEBU keybase login_state.go:727] 2d8 + LoginState#passphraseLogin (username=<redacted>)
```

**Comment by jzila** [comment]
And wolfgang42's log seems to be looping on the session handler every 5 seconds, not sure if these two issues are related.

**Comment by maxtaco** [comment]
Try 'keybase logout' and then 'keybase login' from the prompt

**Comment by peterhallen** [comment]
@maxtaco I attempted this via the `cli` and It just hangs. Here's a snippet from `/home/pete/.cache/keybase/keybase.service.log`
```
2017-06-01T09:54:03.994152-04:00 ▶ [DEBU keybase config.go:285] 143b No path changes needed
2017-06-01T09:54:03.994474-04:00 ▶ [DEBU keybase engine.go:66] 143c + RunEngine(Login)
2017-06-01T09:54:03.994543-04:00 ▶ [DEBU keybase util.go:414] 143d + UIRouter#GetSecretUI
2017-06-01T09:54:03.994592-04:00 ▶ [DEBU keybase ui_router.go:148] 143e | returning delegated SecretUI with sessionID = 0
2017-06-01T09:54:03.994630-04:00 ▶ [DEBU keybase util.go:415] 143f - UIRouter#GetSecretUI -> ok
2017-06-01T09:54:03.994660-04:00 ▶ [DEBU keybase engine.go:95] 1440 using delegated secret UI for engine "Login" (session id = 0)
2017-06-01T09:54:03.994717-04:00 ▶ [DEBU keybase engine.go:66] 1441 + RunEngine(LoginProvisionedDevice)
2017-06-01T09:54:03.994745-04:00 ▶ [DEBU keybase util.go:414] 1442 + UIRouter#GetSecretUI
2017-06-01T09:54:03.994822-04:00 ▶ [DEBU keybase ui_router.go:148] 1443 | returning delegated SecretUI with sessionID = 0
2017-06-01T09:54:03.994849-04:00 ▶ [DEBU keybase util.go:415] 1444 - UIRouter#GetSecretUI -> ok
2017-06-01T09:54:03.994874-04:00 ▶ [DEBU keybase engine.go:95] 1445 using delegated secret UI for engine "LoginProvisionedDevice" (session id = 0)
```
I'm going to kill the processes and reload them to see if anything changes. Let me know if you need any additional data from me. 

Thanks for the help with this!

**Comment by maxtaco** [comment]
Can you send `keybase log send`.  Hopefully @patrickxb  can take a look.

**Comment by peterhallen** [comment]
@maxtaco Here's the log info `e96c6b4076e2b3737d77801c`

However, I killed the `keybase` process and issued a login at the `cli` and now I'm back in. 

Please let me know if there's anything else you need to troubleshoot. Thanks!

**Comment by patrickxb** [comment]
@jzila those session requests are just coming from the gui, nothing to be concerned about.

@peterhallen first log shows service asking UI for a passphrase:

```2017-05-29T10:47:15.063383-04:00 ▶ [DEBU keybase login_state.go:829] 2dd | stretchPassphraseIfNecessary: getting keybase passphrase via ui
2017-05-29T10:47:15.063394-04:00 ▶ [DEBU keybase handler.go:63] 2de SecretUI:GetPassphrase, sessionID = 138
2017-05-29T10:48:00.997508-04:00 ▶ [DEBU keybase login_state.go:1070] 2df + Account "LoggedInProvisionedCheck"
2017-05-29T10:48:05.997776-04:00 ▶ [DEBU keybase login_state.go:920] 2e0 timed out sending acct request "LoggedInProvisionedCheck"
2017-05-29T10:48:05.997841-04:00 ▶ [DEBU keybase login_state.go:921] 2e1 active request: Login Request: "loginWithPromptHelper"```

but it never got a response.  I don't know what the JS stack trace in the initial report pertains to.

**Comment by cjb** [comment]
Hi folks, sorry for missing this thread earlier -- we think we fixed this on the JS side yesterday.  No need to look into it further right now.

**Comment by peterhallen** [comment]
Thanks guys!

**Comment by patrickxb** [comment]
@peterhallen it seems as though you are on a laptop that is sometimes behind a corporate proxy, which won't work with keybase.

I see lots of network errors in your logs:

```2017-05-24T12:01:56.812385-04:00 ▶ [WARN keybase connection.go:246] 6be (CONN keybase service 0b0142fd) Connection: error dialing transport: x509: certificate is valid for instant.arubanetworks.com, not gregord.kbfs.keybase.io
2017-05-24T12:01:56.812432-04:00 ▶ [DEBU keybase standard.go:176] 6bf ++Chat: | PushHandler: should retry on connect, err x509: certificate is valid for instant.arubanetworks.com, not gregord.kbfs.keybase.io```

and also to api.keybase.io.

I'm guessing it works when you are on a different network?

**Comment by peterhallen** [comment]
@patrickxb Actually the network made no difference. The login / logout would just hang, whether I was on my local network at home or remote. The killing of the processes was the only thing that worked.
