### ISSUE TITLE
Can't Revoke Paper Key off Windows

### ISSUE THREAD

**Issue by glenyee** [keybase/client#7884]
Error Message: Can't Remove Device

Error: Can't remove device at r (file:///C:/Users/Glen/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:20:192884) at r.throw (<anonymous>) at f (file:///C:/Users/Glen/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:20:161536) at a (file:///C:/Users/Glen/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:20:162369) at file:///C:/Users/Glen/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:20:163292 at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by glenyee** [comment]
Looks like it did remove it, but there's something wrong with showing/syncing what it did.
