### ISSUE TITLE
renaming sub-team leads to UI confusion and inability to leave channel

### ISSUE THREAD

**Issue by williamkray** [keybase/client#8514]
running keybase 1.0.31-20170917003451+ed4bf6a71 on arch linux
i created a team:
`[~] ▶ keybase team create wkray_test_team1                                                                
Success!`

i then create a subteam:
`[~] ▶ keybase team create wkray_test_team1.subteam1                                                       
Success!                                                                     
                                                                                                          
NOTE: you can administer wkray_test_team1.subteam1, but you won't see its files or chats                  unless you add yourself explicitly with `keybase team add-member`.`

then i add myself to the team:
`[~] ▶ keybase team add-member wkray_test_team1.subteam1 -u williamkray -r admin
Success! A keybase chat message has been sent to williamkray.`

at this point the UI is now showing that i'm a member of this subteam. however if i rename the sub-team:
`[~] ▶ keybase team rename wkray_test_team1.subteam1 wkray_test_team1.newteamname
`

the UI still shows the old name, even after restarting the application fully with `run_keybase`

if i create a new channel in the subteam after renaming it, both subteams show up in the UI as separate teams in my sidebar, each with its own set of channels.
`[~] ▶ keybase chat create-channel wkray_test_team1.newteamname newchannel
Success!`
screenshot: https://imgur.com/Xw1Fcis

if i attempt to leave the team from the CLI with either the new name or the old name, i receive an error:
`[~] ▶ keybase chat leave-channel wkray_test_team1.newteamname general                                    
▶ ERROR server conversation TLF name mismatch: wkray_test_team1.subteam1, expected wkray_test_team1.newteamname
[~] ▶ keybase chat leave-channel wkray_test_team1.subteam1 general                                        
▶ ERROR You are not a member of this team (code 2623)
`
with two channels now, i cannot simply rename the team and leave the general channel:
`[~] ▶ keybase team rename wkray_test_team1.newteamname wkray_test_team1.subteam1                         
[~] ▶ keybase chat leave-channel wkray_test_team1.subteam1 general                                       
▶ ERROR server conversation TLF name mismatch: wkray_test_team1.newteamname, expected wkray_test_team1.subteam1
`
and even after renaming and attempting to leave the secondary channel, i have clearly broken something:
`[~] ▶ keybase team rename wkray_test_team1.subteam1 wkray_test_team1.newteamname                         
[~] ▶ keybase chat leave-channel wkray_test_team1.newteamname newchannel                                 
▶ ERROR server conversation TLF name mismatch: wkray_test_team1.subteam1, expected wkray_test_team1.newteamname
`

**Comment by williamkray** [comment]
as a follow-on statement to this, it also causes some havoc with KBFS... i have since deleted this subteam, but it still is listed in my `/keybase/team/` directory:
```
[team] ▶ ls                                                                                              
ls: cannot access 'wkray_test_team1.subteam1': Input/output error                                        
keybasefriends   wkray_test_team1  wkray_test_team1.subteam1  
```

and i am unable to remove this directory unless i re-create the subteam, and then `rm -rf` the folder.

**Comment by eparejatobes** [comment]
Same here, I just had all sort of issues after renaming a team; had to create a new team with the old name, delete both, and create a new one with the desired name.

I'm on version `2.1.0-20180611201732+3d3e869c2c`.

**Comment by maxtaco** [comment]
@eparejatobes: can you be more specific?  the issue that @williamkray hit is likely resolved by now.

**Comment by eparejatobes** [comment]
Thanks for the quick reply!

> can you be more specific?

Sure:

1. create a subteam `era7.test` using the desktop app
2. rename it `keybase team rename era7.test era7.test2`

After that in the desktop app the name shows OK under "Teams". If I click on its chat I get (added LFs for readability here)

```
Error: ERROR CODE 218 - server conversation TLF name mismatch: 
  era7.test, expected era7.test2 in method chat.1.local.findConversationsLocal 
    at new o (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:428431) 
    at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:428960 
    at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:428999) 
    at _rpcClient.invoke.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:225929) 
    at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1886360 
    at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1765733) 
    at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1765884 
    at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1765513) 
    at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1765843) 
    at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:1765047)
```

I was seeing similar issues elsewhere. I just found out that going to "Chats" and writing something on the corresponding chat, which has the old name, will make it display the new one. After that it looks like I can access it from the team view and everything works smoothly.

**Comment by maxtaco** [comment]
ok thanks, we'll take a look

cc @mmaxim

**Comment by eparejatobes** [comment]
forgot to mention I'm on linux if that makes any difference.
