### ISSUE TITLE
e.startsWith is not a function

### ISSUE THREAD

**Issue by Heliosmaster** [keybase/client#8557]
My contact has recently reset his keys.

I saw the notice of that in our chat and, after clicking `Jump to new conversation` nothing was happening (or it looked like so), so I clicked again a couple of times and then this error appeared at the top of the Keybase client window.

`TypeError: e.startsWith is not a function at Object.m [as isPendingConversationIDKey] (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:1:205342) at d (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:82435) at d.next (<anonymous>) at n (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:162150) at s (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:167747) at k (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:163838) at x (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:164445) at y (file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:163393) at file:///Applications/Keybase.app/Contents/Resources/app/desktop/dist/index.bundle.js:6:165943 at Array.forEach (native)
`

**Comment by Heliosmaster** [comment]
Still happens with the new version 1.33, FYI

**Comment by maxtaco** [comment]
Thanks @Heliosmaster; we've gotten similar complaints in a post-reset state. We're going to put some effort in the coming weeks against fixing the experience after reset, which is quite rough.

Cc: @keybase/react-hackers
