### ISSUE TITLE
Can't delete an account - 'AccountDelete is a devel-only RPC'

### ISSUE THREAD

**Issue by endorse** [keybase/client#8639]
`Error: AccountDelete is a devel-only RPC at l.t (file:///C:/Users/Jono/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:248031) at l (file:///C:/Users/Jono/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:248635) at s (file:///C:/Users/Jono/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:248326) at t.convertToError (file:///C:/Users/Jono/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:248513) at _rpcClient.invoke.e (file:///C:/Users/Jono/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:1:235405) at file:///C:/Users/Jono/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:11:267380 at e.t.Deferrals.e._call (file:///C:/Users/Jono/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:6:251079) at file:///C:/Users/Jono/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:6:251230 at s (file:///C:/Users/Jono/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:6:250859) at e.t.Deferrals.e._fulfill (file:///C:/Users/Jono/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:6:251189)`

**Comment by zapu** [comment]
We are working on redoing user deletion - some issues have arose lately. Meanwhile, if you have never used Keybase teams feature, you can try to delete on the keybase.io website.

**Comment by lim-daniel** [comment]
On webpage :-1: 

```
Error In Deletion: Account deletion of users who are or once were in teams is temporarily disabled; please bear with us while we fix a bug here
```
