### ISSUE TITLE
Error: “/keybase is unavailable. Please try again.”

### ISSUE THREAD

**Issue by chris-morgan** [keybase/client#8827]
Windows 10, 64-bit. I installed Keybase over a year ago, used it for a couple of things I wanted to use it for at the time, then ceased using it. Somewhere along the way I disabled the startup items that it installs.

Just now I wanted to start using it again; I tried starting it (without the background startup items having been started), but it got stuck on “Loading…” when I started it. After one attempt to start the background task, I decided to just uninstall it and install the new version of it. I did so.

I seem to be logged in already (despite uninstalling Keybase), though I wasn’t storing anything in kbfs before. The K: drive seems to be working.

I started the GUI, switched screens a few times. When I wound up in Settings, some seconds later an error popped up:

> /keybase is unavailable. please try again.
>
> Error: /keybase is unavailable. please try again. at b.default.readdir (file:///C:/Users/me/AppData/Local/Keybase/Gui/resources/app/desktop/dist/index.bundle.js:11:561202) at FSReqWrap.oncomplete (fs.js:114:15)

I don’t know if this is significant or not at this stage. But it’s worth mentioning here, at the least.

**Comment by strib** [comment]
Thanks for the report.  If you do a `keybase log send` from the Keybase Shell, and let us know the resulting ID here, that would be very helpful.

cc: @zanderz
