### ISSUE TITLE
Keybase crashes on attempt to drop PGP key

### ISSUE THREAD

**Issue by Snawoot** [keybase/client#9076]
OS: GNU/Linux (Debian 9)

Steps to reproduce:

```
user@dt1:~$ keybase pgp drop 01016fc6f9dfbea894856b86a98f9df9b15bbe2376d9c55e1e43fa7a19042cc87c020a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xc9b8a2]

goroutine 1 [running]:
github.com/keybase/client/go/libkb.(*GlobalContext).Trace(0x0, 0x15e2262, 0x9, 0xc420040f10, 0xc4206e7980)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/util.go:498 +0x22
github.com/keybase/client/go/libkb.(*GlobalContext).GetSocket(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x14be400, 0x0, 0x6002027e6d8)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/libkb/socket.go:64 +0xef
github.com/keybase/client/go/client.getSocket(0x0, 0xc420106300, 0x458090, 0xc420106380, 0xc420011340, 0xc4200aeb40)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/rpc.go:24 +0x3b
github.com/keybase/client/go/client.getSocketNoRetry(0x0, 0x15da764, 0x4, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/rpc.go:19 +0x30
github.com/keybase/client/go/client.GetRPCClientWithContext(0x0, 0xb85b77, 0xc4202f3140, 0x186a0, 0xc420011340, 0x413796)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/rpc.go:32 +0x2f
github.com/keybase/client/go/client.GetRevokeClient(0x0, 0xc420106380, 0xc4200aeb40, 0xc420126500, 0x21b5c60)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/rpc.go:164 +0x2b
github.com/keybase/client/go/client.(*CmdPGPDrop).Run(0xc4202eaa20, 0xc4200b01c0, 0x22c53b0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/client/cmd_pgp_drop.go:35 +0x38
main.mainInner(0xc420284700, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/keybase/main.go:159 +0x71b
main.main()
	/root/build/gopaths/amd64/src/github.com/keybase/client/go/keybase/main.go:64 +0xa6
```

This bug always reproduces for me.

**Comment by maxtaco** [comment]
thank you for the report, I'll take a look asap

**Comment by maxtaco** [comment]
Sorry about that, we'll have this fix live in the next release. If you're on Linux, that should be available tomorrow.

**Comment by Snawoot** [comment]
Thank you!

**Comment by Snawoot** [comment]
BTW, key revokation works normally in keybase GUI
