### ISSUE TITLE
Keybase's UI doesn't appear on Windows  7

### ISSUE THREAD

**Issue by wladiolo** [keybase/client#9150]
OS: Windows 7 Enterprise Service Pack 1
When I start Keybase from the start menu, an icon appears in the icon tray near the clock. But when I click on this icon, nothing happens. I can't open the UI. I need to wait a new message in order to click on the desktop notification to access the UI.

my log id: 0cafb45b63490a253be3e51c

**Comment by maxtaco** [comment]
cc: @zanderz

**Comment by aeridus** [comment]
I've had this problem since February, and gave up trying to use Keybase on my PC. I did a reinstall more recently (it was uninstalled for a few months and I've rebooted my computer several times since then) and the problem still exists. I'm on Windows 7 64-bit with 7+ Taskbar Tweaker.

**Comment by zanderz** [comment]
Do any of you have multiple monitors? Or have you had them hooked to your system in the past?

@wladiolo , given the following, it sounds as though you only see the tray icon but never the tray menu?
![virtualbox_win7 32_23_10_2017_16_29_59](https://user-images.githubusercontent.com/862397/31918239-8e086fa2-b810-11e7-9a22-9be5cd36faf4.png)

In this state, are you able to run "Keybase" from the start/run menu?

Another question: this is to test whether the tray menu might simply be displayed outside the visible area of your screen. When you click the icon and expect to see the tray menu, hit Alt-Space, then "M", then wiggle your mouse around. Does any menu appear?

@aeridus which of the above elements are missing for you?

**Comment by wladiolo** [comment]
Hi @zanderz 
I never use multiple monitor, but I usually connect/disconnect the laptopo from the docking station.

I have the Tray Icon; when I click on the Tray Icon in the task bar an icon appears, but it's not the one with red hairs and blue background (see image)
![keybase1](https://user-images.githubusercontent.com/26803014/31941948-ee7bfb84-b8c3-11e7-8dc4-1e779a43b2c0.png)
If I click on that task bar icon, it suddenly disappears.

When I start Keybase from the start menu, only the tray icon appears, and then the same behavior described above happens.

If I hit Alt-Space, then "M" (with Alt-Space pressed) the behavior is not always the same.
few times I get:

![keybase2](https://user-images.githubusercontent.com/26803014/31942535-e2b07896-b8c5-11e7-90b5-d5015ba46dd8.png)

more often I get:
![keybase3](https://user-images.githubusercontent.com/26803014/31942544-ea90bf94-b8c5-11e7-90e7-e248f0180762.png)

I can't understand why the behavior changes... I hit the same keys...

Let me know if you need more test!

thank you

**Comment by wladiolo** [comment]
@zanderz 
I understood that when the Move/Minimize/Close popup appears (see last image in may previous post), under it there is the tray menu (see second image in my previous post), but it is "transparent".
In fact, moving mouse around sometimes the arrow becomes a hand and, if I click, Windows Explorer pops up pointing to my private folder (e.g. K:\private\wladiolo) like when I click on "private" folder icon.

Sometimes I can guess where the chat icon is and so I can open the chat UI.

**Comment by zanderz** [comment]
There have been some fixes which may help with these problems.
Also, we discovered that in some cases, Electron windows are invisible on Windows 7: https://github.com/electron/libchromiumcontent/pull/503
but there seems to be a fix coming soon, finally.

@Oddyza I am curious what you see if you do the following at the CLI:
`cd %localappdata%\Keybase`
`keybase ctl stop`
`Gui\Keybase.exe`
could you do those and copy+paste the results? Thanks.

**Comment by Oddyza** [comment]
Hi @zanderz 

Here are the results:

C:\Users\GLITE\AppData\Local\Keybase>keybase ctl stop

C:\Users\GLITE\AppData\Local\Keybase>gui\keybase.exe

C:\Users\GLITE\AppData\Local\Keybase>
Error loading state: { Error: C:\Users\GLITE\AppData\Roaming\Keybase\installer.json: ENOENT: no such file or directory, open 'C:\Users\GLITE\AppData\Roaming\Keybase\installer.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Object.readFileSync (C:\Users\GLITE\AppData\Local\Keybase\gui\resources\app\desktop\dist\main.bundle.js:1:549643)
    at p.default.promptedForCLI.t.default (C:\Users\GLITE\AppData\Local\Keybase\gui\resources\app\desktop\dist\main.bundle.js:1:548781)
    at p.default.promptedForCLI (C:\Users\GLITE\AppData\Local\Keybase\gui\resources\app\desktop\dist\main.bundle.js:1:432753)
    at Object.defineProperty.value (C:\Users\GLITE\AppData\Local\Keybase\gui\resources\app\desktop\dist\main.bundle.js:1:432749)
    at t (C:\Users\GLITE\AppData\Local\Keybase\gui\resources\app\desktop\dist\main.bundle.js:1:256)
    at Object.defineProperty.value (C:\Users\GLITE\AppData\Local\Keybase\gui\resources\app\desktop\dist\main.bundle.js:1:334039)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\GLITE\\AppData\\Roaming\\Keybase\\installer.json' }
Version: 1.0.47-20180404145836+0fe66b9
Check bounds: { height: 600, width: 800, x: 400, y: 226 } { x: 0, y: 0, width: 1280, height: 1024 } { x: 0, y: 0, width: 1280, height: 1024 }
Setting login item due to user pref
Opened at login: false
Is restore: true
Open hidden: false
Hide main window: true
Hide dock icon: false
