### ISSUE TITLE
Error while trying to login

### ISSUE THREAD

**Issue by webkernel** [keybase/client#9173]
Please help me. I get this error trying to log in:

Error: Unknown RPC Error at l.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:237583) at l (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:238111) at u (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:238025) at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:237950) at _rpcClient.invoke.e (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:219059) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:83:46589 at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:8:28805) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:8:28956 at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:8:28585) at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:8:28915)

**Comment by maxtaco** [comment]
Please send feedback from the app
