### ISSUE TITLE
Thread Exhaustion

### ISSUE THREAD

**Issue by benkietzman** [keybase/client#9259]
KBFS keeps crashing.  It runs for a while (maybe two hours), eventually begins to eat up the CPU, and then crashes after a few more minutes.

I see the following error message in the keybase.kbfs.log at the start of the crash:

runtime: program exceeds 10000-thread limit
fatal error: thread exhaustion

my log id: 78521b7a2d47cca548699b1c

**Comment by strib** [comment]
@jzila: we don't have the full logs here, but it seems like there are ~5K goroutines stuck trying to read disk block sizes out of the cache.  Any ideas, other than faulty hardware?

```
goroutine 94750 [runnable]:
syscall.Syscall(0x4, 0xc42b1bc0a0, 0xc430505e48, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.Stat(0xc42b1bc000, 0x94, 0xc430505e48, 0xc42b1bc000, 0x94)
	/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1492 +0x97
os.Stat(0xc42b1bc000, 0x94, 0xc42b1bc000, 0x94, 0xc42a9a6908, 0xd5ff36)
	/usr/local/go/src/os/stat_unix.go:32 +0x5c
github.com/keybase/kbfs/ioutil.Stat(0xc42b1bc000, 0x94, 0x21, 0xc42b1bc000, 0x94, 0xc42a9a6918)
	/root/build/gopaths/amd64/src/github.com/keybase/kbfs/ioutil/os_wrap.go:55 +0x42
github.com/keybase/kbfs/libkbfs.(*blockDiskStore).getDataSize(0xc42048c6c0, 0xc422ff8d20, 0x21, 0xc42a9a69b8, 0xc42a9a69c0, 0xc420022000)
	/root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/block_disk_store.go:305 +0x5b
github.com/keybase/kbfs/libkbfs.(*blockJournal).getDataSize(0xc42040e500, 0xc422ff8d20, 0x21, 0xe90c39, 0xc42a9a6a00, 0xc42a9a6a08)
	/root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/block_journal.go:394 +0x43
github.com/keybase/kbfs/libkbfs.(*tlfJournal).getBlockSize(0xc420496900, 0xc422ff8d20, 0x21, 0x0, 0x0, 0x0)
	/root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/tlf_journal.go:1884 +0xcb
github.com/keybase/kbfs/libkbfs.journalBlockServer.getBlockSizeFromJournal(0xc420088000, 0x1e4fc00, 0xc420142e80, 0x0, 0xe80c6dcc3e6550de, 0x1618feb4f1cee03b, 0xc422ff8d20, 0x21, 0x0, 0x0, ...)
	/root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/journal_block_server.go:59 +0xd6
github.com/keybase/kbfs/libkbfs.(*BlockOpsStandard).GetEncodedSize(0xc420284510, 0x1e47880, 0xc43bcc4000, 0x1e4e940, 0xc44a228000, 0xc422ff8d20, 0x21, 0x2, 0x1, 0x1, ...)
	/root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/block_ops.go:90 +0x294
github.com/keybase/kbfs/libkbfs.(*folderBlockOps).getCleanEncodedBlockSizeLocked(0xc423a207f8, 0x1e47880, 0xc43bcc4000, 0x0, 0x1e4e940, 0xc44a228000, 0xc422ff8d20, 0x21, 0x2, 0x1, ...)
	/root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/folder_block_ops.go:342 +0x2c6
github.com/keybase/kbfs/libkbfs.(*folderBlockOps).GetCleanEncodedBlocksSizeSum.func1(0x6563613800000008, 0x13ee678)
	/root/build/gopaths/amd64/src/github.com/keybase/kbfs/libkbfs/folder_block_ops.go:508 +0x101
github.com/keybase/kbfs/vendor/golang.org/x/sync/errgroup.(*Group).Go.func1(0xc43bcc4040, 0xc4327eb8c0)
	/root/build/gopaths/amd64/src/github.com/keybase/kbfs/vendor/golang.org/x/sync/errgroup/errgroup.go:58 +0x57
created by github.com/keybase/kbfs/vendor/golang.org/x/sync/errgroup.(*Group).Go
	/root/build/gopaths/amd64/src/github.com/keybase/kbfs/vendor/golang.org/x/sync/errgroup/errgroup.go:55 +0x66
```

**Comment by strib** [comment]
Oh @jzila, nevermind, this isn't the block cache, it's the block journal.  Hrmm.

**Comment by strib** [comment]
@benkietzman: The log send gets cut off in a more un-useful way, I'm hoping to get a look at your entire set of logs (`~/.cache/keybase/keybase.kbfs*`).  Though with KBFS not working, I'm not sure the best way to get them to me.  Any ideas?  They're semi-private, so probably posting them here isn't a good idea.

**Comment by strib** [comment]
Actually maybe I don't need the full logs, I have a theory and just posted a PR for a potential fix in keybase/kbfs.

**Comment by strib** [comment]
I've merged what I hope is a fix for this.  It will be out in tomorrow Linux build, or if you want to try it sooner let me know and we can make a special one.

**Comment by benkietzman** [comment]
Thank you for the quick turn around on this.  Very impressive.  I am installing the new version now and will let you know how it turns out.  Thanks again.

**Comment by strib** [comment]
The new version with the fix included won't be built until 9:00 am Pacific this morning, I think.

**Comment by benkietzman** [comment]
KBFS has been running for 3 and half hours.  Looks good so far.  Thank you again.
