### ISSUE TITLE
Trying to Open a Team Folder Chat Yields an Error

### ISSUE THREAD

**Issue by DeedleFake** [keybase/client#9568]
Keybase GUI Version: 1.0.35-20171114170030+d28b65dbe

Reproduction Steps:
1. Go to folders.
2. Click on a team.
3. Click 'Open in chat'.

Result:
```
t.split is not a function

TypeError: t.split is not a function
  at t.parseFolderNameToUsers (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:470163)
  at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:2450807)
  at s.next (<anonymous>)
  at n (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:509748)
  at n (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:510414)
  at T (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:513571)
  at y (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:511061)
  at n (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:509811)
  at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:515498)
  at v (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:511384)
```

**Comment by maxtaco** [comment]
thanks, sorry about that

cc @chrisnojima / @keybase/react-hackers
