### ISSUE TITLE
Error unboxing chat message, Linux Mint 18.2

### ISSUE THREAD

**Issue by vollumc** [keybase/client#9678]
Two of my chats (one with an individual, one with a group) now show "error unboxing chat message" in the left sidebar (along with what appears to be the correct timestamp for the most recent message), and show "secure connection established", but no other text, in the main window. All other chats still seem to work OK. When viewed on my Phone, all chats are normal. A popup shows the following error message:
Error: multiple errors while loading team list at l.t (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:287066) at l (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:287670) at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:287361) at t.convertToError (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:287548) at _rpcClient.invoke.e (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:275420) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:739429 at e.t.Deferrals.e._call (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:527143) at file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:527294 at s (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:526923) at e.t.Deferrals.e._fulfill (file:///opt/keybase/resources/app/desktop/dist/index.bundle.js:1:527253)

**Comment by vollumc** [comment]
Reinstalling the app seems too have fixed the issue. Fast work, guys!
